### ISSUE TITLE
[Routing] missing route to Z3.A002B at ODC node

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#10]
And hi again,
alright, I have one more routing issue, this time for Z3.A002B at ODC node. Again, direct request works fine, routed request fails. This is the last one I found for now ;)

```
from obspy.clients.fdsn import Client
from obspy.clients.fdsn import RoutingClient
from obspy import UTCDateTime

direct = Client('ODC', debug=True, eida_token='/home/fuchs/.eidatoken')
routed = RoutingClient('eida-routing', debug=True, credentials={'EIDA_TOKEN': '/home/fuchs/.eidatoken'})
```
```

direct.get_waveforms(network='Z3', station='A002B', channel='LHZ', location='*', starttime=UTCDateTime('2
   ...: 017-05-06'), endtime=UTCDateTime('2017-05-07'))
```
-> 1 Trace(s) in Stream: Z3.A002B.00.LHZ ....

```
routed.get_waveforms(network='Z3', station='A002B', channel='LHZ', location='*', starttime=UTCDateTime('
    ...: 2017-05-06'), endtime=UTCDateTime('2017-05-07'))
```
-> FDSNNoDataException: No data available for request. Detailed response of server: No Content --

**Comment by javiquinte** [comment]
@Jollyfant solved it and I can see the changes in the GEOFON Routing Service.

http://geofon.gfz-potsdam.de/eidaws/routing/1/query?format=post&net=Z3&sta=A002*

> http://www.orfeus-eu.org/fdsnws/dataselect/1/query
Z3 A002B * * 2015-01-01T00:00:00 2019-04-30
Z3 A002A * * 2015-01-01T00:00:00 2019-04-30

We should see the station appear when they restart the web service.

**Comment by Jollyfant** [comment]
Confirmed: http://www.orfeus-eu.org/eidaws/routing/1/query?station=A002B
