### ISSUE TITLE
[Federator] Unmatched eidaws/wfcatalog and fdsnws/dataselect

### ISSUE THREAD

**Issue by Ryan-isc** [EIDA/userfeedback#106]
Queries to eidaws/wfcatalog for a given network/station/time period return no metadata whereas the same query to fdsnws/dataselect returns data. As the website states "The WFCatalog can serve as an index for data discovery" this seems like an issue.

In python using the requests module:

>>> requests.get("http://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?network=HU&station=PSZ&start=2015-01-01T11:02:10&end=2015-01-01T11:02:40")
<Response [204]>
>>> requests.get("http://eida-federator.ethz.ch/fdsnws/dataselect/1/query?network=HU&station=PSZ&start=2015-01-01T11:02:10&end=2015-01-01T11:02:40")
<Response [200]>

Response [200] indicates data available, Response [204] indicates no metadata available.

I have coded around this issue for my purposes but I figured it probably required investigation. I am fairly sure this is not the only station that has this issue.

Ryan

**Comment by damb** [comment]
Thanks for your report.

**TLTR;** There is simply no waveform metadata provided by the corresponding endpoint (i.e. GFZ). I.e. this is an issue at GFZ.

A direct request to GFZ returns HTTP status code **204**, too:

```
$ curl -v -o - "http://geofon.gfz-potsdam.de/eidaws/wfcatalog/1/query?network=HU&station=PSZ&start=2015-01-01T11:02:10&end=2020-01-01T11:02:40"
*   Trying 139.17.3.177...
* TCP_NODELAY set
* Connected to geofon.gfz-potsdam.de (139.17.3.177) port 80 (#0)
> GET /eidaws/wfcatalog/1/query?network=HU&station=PSZ&start=2015-01-01T11:02:10&end=2020-01-01T11:02:40 HTTP/1.1
> Host: geofon.gfz-potsdam.de
> User-Agent: curl/7.58.0
> Accept: */*
> 
< HTTP/1.1 204 No Content
< Server: nginx/1.18.0
< Date: Wed, 28 Jul 2021 14:00:51 GMT
< Content-Type: application/json
< Connection: keep-alive
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: X-Requested-With
< Content-Disposition: attachment; filename=GFZ-WFCATALOG-2021-07-28T14:00:48.127Z.json
< 
* Connection #0 to host geofon.gfz-potsdam.de left intact
```

`eidaws-federator`'s internal routing with regard to `eidaws-wfcatalog` reveals that data should be available for the query filter parameters specified:

```
http://geofon.gfz-potsdam.de/eidaws/wfcatalog/1/query
HU PSZ -- BHE 1995-01-01T00:00:00
HU PSZ -- BHN 1995-01-01T00:00:00
HU PSZ -- BHZ 1995-01-01T00:00:00
HU PSZ -- HHE 2002-06-20T00:00:00
HU PSZ -- HHN 2002-06-20T00:00:00
HU PSZ -- HHZ 2002-06-20T00:00:00
HU PSZ -- LHE 1995-01-01T00:00:00
HU PSZ -- LHN 1995-01-01T00:00:00
HU PSZ -- LHZ 1995-01-01T00:00:00
HU PSZ -- SHE 1995-01-01T00:00:00
HU PSZ -- SHN 1995-01-01T00:00:00
HU PSZ -- SHZ 1995-01-01T00:00:00
HU PSZ -- VHE 1995-01-01T00:00:00
HU PSZ -- VHN 1995-01-01T00:00:00
HU PSZ -- VHZ 1995-01-01T00:00:00
```

which agrees with the routing localconfig configuration:

```
<ns0:route networkCode="HU" stationCode="*" locationCode="*" streamCode="*">
<ns0:station address="http://geofon.gfz-potsdam.de/fdsnws/station/1/query" priority="1" start="1992-01-01T00:00:00" end=""/>
<ns0:wfcatalog address="http://geofon.gfz-potsdam.de/eidaws/wfcatalog/1/query" priority="1" start="1992-01-01T00:00:00" end=""/>
<ns0:dataselect address="http://geofon.gfz-potsdam.de/fdsnws/dataselect/1/query" priority="1" start="1992-01-01T00:00:00" end=""/>
</ns0:route>
```

However, the result is the same: the endpoint simply doesn't return any data and this is forwarded by `eidaws-federator` to its client.

**Comment by Ryan-isc** [comment]
Thanks for the feedback. I figured it was an issue with the metadata not being provided rather than it not being accessible. It might be worth changing that line ("The WFCatalog can serve as an index for data discovery") on the webpage (https://www.orfeus-eu.org/data/eida/webservices/wfcatalog/) as clearly, through no ones fault, wfcatalog is not data complete to the same level as the waveforms from the dataselect are.

Ryan

**Comment by damb** [comment]
AFAIK `eidaws-wfcatalog` should be data complete.

Let's keep this issue open until @javiquinte or someone else from GFZ clarifies the situation.

**Comment by javiquinte** [comment]
Dear @Ryan-isc ,
thanks a lot for your feedback! We are checking this right now and we hope it will be solved ASAP. I'll post here when this is finished.
BTW, of course the idea is that WFCatalog could be queried to check availability **without** querying/downloading dataselect. From time to time it could happened that both services are not consistent for a particular stream/timewindow. However, the benefits of being able to check availability in milliseconds should be much larger than downloading huge volumes of data without even knowing if it is going to be useful or not.
Thanks again!

**Comment by Ryan-isc** [comment]
Again thanks for getting back to me. For my purposes I can just query the dataselect function but for larger searches it would probably be prohibitively slow. I came across the issue as the IRIS fdsnws availability tool registers that station as having data available but dataselect doesn't. Sort of the inverse problem from what you are seeing.

I think stations from network CZ also had the issue. The stations and time period I looked at were completely random which makes me wonder how widespread this is. I might just have got unlucky/lucky.

Ryan

**Comment by javiquinte** [comment]
Hi @Ryan-isc 
We have found the cause of this issue. Actually, the PSZ station is archived in two different networks (HU and GE). This means that if you do a station discovery you could probably get both stations. For dataselect there is a mapping active, so that whenever you request HU.PSZ you get actually what we have at GE.PSZ. For WFCatalog there is no mapping, so you get a 204 NoData.
It is definitely not clean enough, as it could be confusing, but in the end you will get no repeated data if you do the filter through WFCatalog.

```
% curl -v -o - "http://geofon.gfz-potsdam.de/eidaws/wfcatalog/1/query?network=GE&station=PSZ&start=2015-01-01T11:02:10&end=2020-01-01T11:02:40"
*   Trying 139.17.3.177...
* TCP_NODELAY set
* Connected to geofon.gfz-potsdam.de (139.17.3.177) port 80 (#0)
> GET /eidaws/wfcatalog/1/query?network=GE&station=PSZ&start=2015-01-01T11:02:10&end=2020-01-01T11:02:40 HTTP/1.1
> Host: geofon.gfz-potsdam.de
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 200 OK
< Server: nginx/1.18.0
< Date: Thu, 29 Jul 2021 10:34:21 GMT
< Content-Type: application/json
< Transfer-Encoding: chunked
< Connection: keep-alive
< X-Powered-By: Express
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Headers: X-Requested-With
< Content-Disposition: attachment; filename=GFZ-WFCATALOG-2021-07-29T10:34:21.254Z.json
<
[{"version":"1.0.0","producer":{"name":"GFZ","agent":"ObsPy mSEED-QC","created":"2016-12-29T01:06:05.557Z"},"station":"PSZ","network":"GE",
...
...
...
```

**Comment by damb** [comment]
@javiquinte, this is an interesting *workaround* ;).

**Comment by Ryan-isc** [comment]
That makes sense now, thanks for looking into it.
