### ISSUE TITLE
Test suite for waveform and meta data availability on EIDA available

### ISSUE THREAD

**Issue by jojomale** [EIDA/userfeedback#110]
At BGR, we developed small Python library and command line tool that allows to regularly test the availability of meta and waveform data on EIDA.
The package is available on GitHub:
https://github.com/jojomale/eidaQC
The documentation is here:
https://eidaqc.readthedocs.io/
Feedback, especially on documentation and usability, is greatly welcome.

Best regards,
Johanna

**Comment by jschaeff** [comment]
@all lets review this documentation and make suggestions in this issue.

**Comment by jschaeff** [comment]
Hello @jojomale , sorry for the late reply.
I've went through the documentation and I must say it's excellent. Clear, with examples, and well written.
I couldn't test all the commands.
I've noted a Pipfile in your repository, maybe add installation instruction with `pipenv` as it's the simplest installation framework now (from my point of view). I think you have to add the Pipfile.lock in the repository.

**Comment by jojomale** [comment]
> 

@jschaeff: I added support for pipenv. I hope it works, but since I am not familiar with it, I don't want to promise too much.

**Comment by petrrr** [comment]
What about moving (or cloning) the repo to the EIDA namespace and closing this issue. All future developments or issues to be track in the dedicated repo.

**Comment by jschaeff** [comment]
@jojomale Thank you for implementing this :)
If you wish to support more versions of python (I advise to do so), remove the 2 last lines from the Pipfile and remove Pipfile.lock from versionning

https://pipenv.pypa.io/en/latest/basics/#specifying-versions-of-python
https://pipenv.pypa.io/en/latest/basics/#general-recommendations-version-control

Also from @petrrr suggestion we would:

1. create a new repo in EIDA group that you would manage
2. move you repo to this new one

What would be the name of this repo ? eidaqc ? Any other suggestion ?
Quality Check is a bit too generic. I would prefer something that reflects the reporting functionality.

eida-availability-reports is somewhat cumbersome.

I suggest:
- `eida-owl` with the idea that the owl watches the details 
![image](https://user-images.githubusercontent.com/1147747/153587951-1942b0a7-2c68-48d3-b621-224292955682.png)

I don't have any better idea for now. Someone ?

Then, with a nice name, you should change the command line name. `eida` as a command does not suit.



Besides, I suggest you change the command line name from `eida` to `eidaqc`

**Comment by jojomale** [comment]
@jschaeff , @petrrr Yes, I agree, that moving eidaqc to the official EIDA channel would make sense. Can I do this or does someone with more power has to do it? 

The idea with the owl sounds cute:-) Although eida-availability-report could be abbreviated by EAR, which listens to the EIDA data...

Regarding the allowed Python versions: I didn't test for Python >3.6. and I am not entirely sure that all components will work for lower versions. That's why I put in the limit. But of course, we can remove it and see what happens.

**Comment by jschaeff** [comment]
I will create the repo as soon as we agree on a name.
`ear` for the command line is OK for me, it does'nt confict with any cli name I know of. 

For the pipfile, let it as it is.

**Comment by jschaeff** [comment]
Hello, are we ready to create a repo now ?

**Comment by jojomale** [comment]
Hi, sorry for the late reply. From my side, we can move to the repo to 
the EIDA page. Do you need anything from me?

Greetings, Johanna

---
Msc. Johanna Lehr
Institute of Geosciences, Kiel University
Otto-Hahn-Platz 1
24118 Kiel
Tel. +49 (0)431 880 3913

Am 2022-10-28 14:23, schrieb Jonathan Schaeffer:

**Comment by jschaeff** [comment]
Hello @jojomale 

what is the name of the project ? I need this to create the repository.
