### ISSUE TITLE
Routing problem in availability report

### ISSUE THREAD

**Issue by sheimers** [EIDA/userfeedback#111]
The availability report shows a routing error for our ETH fdsnws instance, section "Failure rate of inventory requests"

Direct requests work fine, but routed requests produce some errors since a few weeks:

[https://www.szgrf.bgr.de/eida_availability_report.html](https://www.szgrf.bgr.de/eida_availability_report.html)

I have tried to debug this and found some network start- and end dates did not match between the inventory and our routing.xml. I have fixed the issues, but unfortunately the error persists.

I have also done some test requests with the obspy routing client myself, and found no problems downloading our metadata.

I have downloaded the logfiles from [ftp://www.szgrf.bgr.de/pub/EidaAvailability](ftp://www.szgrf.bgr.de/pub/EidaAvailability), it looks like the test still requests data from after the close date of our networks.

Is it possible to get more detailed logs on what requests actually fail? And how are the test requests generated, is it possible the fix to our routing.xml is ignored for some reason? Are the test requests generated on the fly considering the current routing configuration, or is it maybe hardcoded in the test ignoring updates to routing?

**Comment by javiquinte** [comment]
Hi @sheimers
Could you show which dates have you changed? On which networks/stations? Was the Routing Service at ODC updated after your change?

**Comment by sheimers** [comment]
It was the OR, VI, 2C and Z9 networks.

I first updated the Seiscomp inventory and forgot to also adjust routing.xml. I did this later after the errors in the test appeared.

OR and VI are networks not exclusively used by us, for VI there are stations from two datacenters. This could be part of the problem but I don't think so, for OR we currently are the only provider in the eida network, and for VI I only have our stations in routing.xml.

For Z9, there was an overlap of our network with a foreign network that started after ours was closed. I have also fixed this in our routing.xml.

Looking at
www.orfeus-eu.org/eidaws/routing/1/globalconfig?format=fdsn , the changes have correctly propagated to ODC.

Stefan

**Comment by sheimers** [comment]
I did more debugging. The obsPy Client and RoutingClient look similar, but work quite differently. 

The direct Client does a http get request like this:

`http://eida.ethz.ch/fdsnws/station/1/query?starttime=2020-12-17T13%3A42%3A44.299734&endtime=2021-12-17T13%3A42%3A44.299765&network=CH&channel=HHZ%2CBHZ%2CEHZ%2CSHZ&level=station&includerestricted=false`

Whereas the RoutingClient uses the POST method. It sends the following request:

```
level=station
includerestricted=False
CH * * HHZ,BHZ,EHZ,SHZ 2020-12-17T13:44:05.142795 2021-12-17T13:44:05.142825
```


I could reproduce both on the commandline with wget. 

```
wget --post-file=request_rou.txt -O test.xml http://eida.ethz.ch/fdsnws/station/1/query
wget -O test_dir.xml 'http://eida.ethz.ch/fdsnws/station/1/query?starttime=2020-12-17T13%3A42%3A44.299734&endtime=2021-12-17T13%3A42%3A44.299765&network=CH&channel=HHZ%2CBHZ%2CEHZ%2CSHZ&level=station&includerestricted=false'
```


The get request above downloads a valid xml file, while the post request downloads an invalid xml file.

The invalid xml file has a corrupted part in the middle around a station with a long name containing french special characters (station code SONUG). The valid xml file using the get request does not include that station at all. 

I have to add that the valid file from the get request includes a suspiciously low number of stations, maybe it's not correct either, but exludes the problematic stations.

**Comment by sheimers** [comment]
I think I have solved the problem, but I still don't understand it.
First I upgraded fdsnws (Seiscomp 4.8.2 in stead of 4.5.0), but this did not help.
Then I have edited the inventory file of the suspicious station SONUG, with the french name 'Office des Nations Unies à Genève (ONUG), GE'. I have removed the accents, 'Office des Nations Unies a Geneve (ONUG), GE', this solved the problem, POST method download now is valid xml, and includes the station.
And now comes the really strange thing, I have re-added the french accents, reloaded the inventory, restarted fdsnws, and now POST method still produces valid xml, including the station with correct french accents.
My guess: character encoding for this station in the Seiscomp database was wrong, and only got updated once I have modified the inventory file before reloading the configuration. We run the same database for about 10 years, while doing lots of software updates. 

Now I did only local tests, let's wait until Monday if the "EIDA availability report" also shows the improvement.

**Comment by sheimers** [comment]
An other observation: The method get request still does not include station SONUG. And I checked, this is correct. SONUG only has HGN/E/Z channels that are not selected. The method POST request still does get the station, which means the selected channel codes are ignored.

This might be intended because of level=station. If I set level=channel instead, then also POST method will not return SONUG. But still it's strange the same fdsnws returns different results for the same request, depending on the method used.

**Comment by kaestli** [comment]
(On the accent issue: OUR DB is utf8, and has always been. Content (french special characters) seemed ok, but i could not actually check the byte values before Stefan updated the content)

**Comment by kaestli** [comment]
> An other observation: The method get request still does not include station SONUG. And I checked, this is correct. SONUG only has HGN/E/Z channels that are not selected. The method POST request still does get the station, which means the selected channel codes are ignored.
> 
> This might be intended because of level=station. If I set level=channel instead, then also POST method will not return SONUG. But still it's strange the same fdsnws returns different results for the same request, depending on the method used.

I would consider this as a bug (of the seiscomp/fdsn implementation) - the "level" is clearly defined as a selection of the response level, not affecting the interpretation of the request parameters. And the FDSN/station representation does not specify different behaviour of get and post.

**Comment by sheimers** [comment]
I have checked the SONUG.xml file was byte identical before and after the fix. I reloaded the same utf-8 again and it suddenly was correct. I don't know what went wrong, maybe previous versions of either Seiscomp or of PostgreSQL used a different internal encoding and failed to update the DB contents after the software update.

**Comment by sheimers** [comment]
This is the example code I have used for debugging. I got it from Klaus Stammler as an example for what his test does. Maybe it helps if you have to debug the same issue for your datacenter. 

```
#! /usr/bin/env python3

from obspy.clients.fdsn import RoutingClient
from obspy.clients.fdsn.client import Client
from obspy import UTCDateTime

invpar = {
    'level'              : 'station',
    'network'            : 'CH',
    'channel'            : 'HHZ,BHZ,EHZ,SHZ',
    'starttime'          : UTCDateTime()-86400*365,
    'endtime'            : UTCDateTime(),
    'includerestricted'  : False,
}

timeout = 240

print( "direct request" )
dclient = Client( 'ETH', timeout=timeout , debug=True)
dinv = dclient.get_stations( **invpar )
print( "routed request" )
invpar['timeout'] = timeout
rclient = RoutingClient( "eida-routing" , debug=True)
rinv = rclient.get_stations( **invpar )
print( dinv.get_contents()['networks'], rinv.get_contents()['networks'] )
```

**Comment by sheimers** [comment]
The problem is solved, the test for ETH is "green" again.

https://www.szgrf.bgr.de/eida_availability_report.html
