### ISSUE TITLE
[No Data] endbefore or endafter in routing is not working?

### ISSUE THREAD

**Issue by xrise75** [EIDA/userfeedback#113]
Using routing:

from obspy.clients.fdsn import RoutingClient
rsClient = RoutingClient("eida-routing")
st = rsClient.get_stations(network="HL", channel="HHZ", endbefore=UTCDateTime(2021, 12, 31, 0, 0, 0))
print(st)
>Inventory created at 2021-12-29T16:57:15.135104Z
	>Created by: ObsPy 1.2.2
	>	    https://www.obspy.org
	>Sending institution: ObsPy FDSN Routing 1.2.2
	>Contains:
	>	Networks (0):
	>	Stations (0):
	>	Channels (0):

Using direct access:
from obspy.clients.fdsn import Client
Client = Client("NOA")
st = Client.get_stations(network="HL", channel="HHZ", endbefore=UTCDateTime(2021, 12, 31, 0, 0, 0))
print(st)
>Inventory created at 2021-12-29T16:58:38.574745Z
	>Sending institution: SeisComP (NOA)
	>Contains:
	>	Networks (1):
	>		HL
	>	Stations (28):
	>		HL.ANDM (Andravida,Greece)
	>		HL.ASP (Asprokampos,Loutraki,Greece)
	>		HL.COR (Corinthos,Greece)
	> ....	
	>	Channels (0):

**Comment by jschaeff** [comment]
I can reproduce the problem here.
I can't see anything wrong with the routing : http://www.orfeus-eu.org/eidaws/routing/1/query?network=HL

@all, any idea on what to check now ?

**Comment by javiquinte** [comment]
Hi Christos.
`endbefore` is not one of the parameters included in Routing Service. I'll add a request to support it in the next version of the RS.
