### ISSUE TITLE
[Metadata / Webpage] eidaStationsKML.xml kml-file malformed and no stations on webpage map

### ISSUE THREAD

**Issue by flixha** [EIDA/userfeedback#115]
* Type of client used: Browser (Firefox)
* Time: 2022-01-30 17:15 CET

The map [on the EIDA webpage](https://www.orfeus-eu.org/data/eida/) currently doesn't display any stations as it used to.

The [merged KML-file](https://www.orfeus-eu.org/documents/eidaStationsKML.xml) of all EIDA stations that is linked further down under the above link gives the following error message:
```html
XML Parsing Error: not well-formed
Location: https://www.orfeus-eu.org/documents/eidaStationsKML.xml
Line Number 10, Column 54:
    <meta name="description" content="Observatories & Research Facilities for European Seismology">
-----------------------------------------------------^
```

**Comment by flixha** [comment]
The display on the webpage works again now, the merged KML file still displays the same error.

**Comment by jbienkowski** [comment]
Hi,

It should be fixed now.

Cheers,
Jarek
