### ISSUE TITLE
[WebDC3] Issues with Safari / contact page

### ISSUE THREAD

**Issue by jfclinton** [EIDA/userfeedback#118]
Using webdc http://orfeus-eu.org/webdc3/ on safari (v15.1), the map does not render. No problem using eg Chrome. I believe this issue is long-standing, and if it is not going to be fixed, the user should be alerted that safari is not supported, and the list of supported browsers provided.

More minor problem: the contact link at the bottom leads to the following page:
http://orfeus-eu.org/organization/contact/form/

Instead of a 404 Page not found, this should be changed to the GitHub link (actually available in the corner). Preferably fix the form?

**Comment by web-sys1** [comment]
ORFEUS website seems to be outdated. However, an update on website may be needed
