### ISSUE TITLE
[WFCatalog] very slow response from ETH and RESIF nodes

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#12]
Hi everyone,

I am playing around with accessing the WFCatalog through python. While this generally works well, I realized that requests are very slowly answered by ETH and RESIF nodes. While (for a 15 days test time window) I can usually parse tens of stations within seconds on most nodes, at ETH or RESIF node a single station query takes ~10 seconds to be answered. It's a bit cumbersome ... Do you have any idea why this is the case? KOERI node is also slightly slower than most of the other, but still acceptable.

**Comment by Jollyfant** [comment]
It could be a missing index perhaps @sheimers

**Comment by sheimers** [comment]
Sorry I was on vacation for two weeks, I am back now and will look into that this week.

**Comment by sheimers** [comment]
@Jollyfant was right, part of the indexes were misssing at ETH. It only had that for fileId. I have now added {ts: 1, net: 1, sta: 1}, {"files.name": 1} and {streamId: 1} as recommended at https://dev.knmi.nl/projects/eida/wiki/WFCatalog . 

Can you please check if the speed is acceptable now?

before:
```
> db.daily_streams.getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "wfrepo.daily_streams"
        },
        {
                "v" : 2,
                "key" : {
                        "fileId" : 1
                },
                "name" : "fileId_1",
                "ns" : "wfrepo.daily_streams"
        }
]
```

now:
```
> db.daily_streams.getIndexes()
[
        {
                "v" : 2,
                "key" : {
                        "_id" : 1
                },
                "name" : "_id_",
                "ns" : "wfrepo.daily_streams"
        },
        {
                "v" : 2,
                "key" : {
                        "fileId" : 1
                },
                "name" : "fileId_1",
                "ns" : "wfrepo.daily_streams"
        },
        {
                "v" : 2,
                "key" : {
                        "ts" : 1,
                        "net" : 1,
                        "sta" : 1
                },
                "name" : "ts_1_net_1_sta_1",
                "ns" : "wfrepo.daily_streams"
        },
        {
                "v" : 2,
                "key" : {
                        "files.name" : 1
                },
                "name" : "files.name_1",
                "ns" : "wfrepo.daily_streams"
        },
        {
                "v" : 2,
                "key" : {
                        "streamId" : 1
                },
                "name" : "streamId_1",
                "ns" : "wfrepo.daily_streams"
        }
]
```

**Comment by jschaeff** [comment]
Hi, sorry for the late reply, I didn't get the initial notification.
I made some time tests with the following request, and created the missing indices
```
http http://ws.resif.fr/eidaws/wfcatalog/1/query\?network\=FR\&station\=AJAC\&starttime\=2019-01-01\&endtime\=2019-01-30
```

Initial response time : 13s
After index ts, net, sta : 5.6s
After index files.name : 5.0s
After index streamId : 4,6s

I divided by 3 the response time. Is it now acceptable ?
If you still need better responsetime, I should look at the infrastructure hosting the database to speed things up. Let me know please.

**Comment by flofux** [comment]
Oh yes, RESIF and ETH node respond much faster now! Wonderful, thanks for looking into this. :)
KOERI node still somewhat slower, but I think no one was notified on their side ... ?

**Comment by javiquinte** [comment]
Great! Thanks @jschaeff and @sheimers !
I'll close the issue but send it in any case to the KOERI contact in a private message.

**Comment by comoglu** [comment]
KOERI node must be responding as the others by now.

**Comment by comoglu** [comment]
Sorry for late response by the way. I was not aware of the issue before. Is anyone able to test KOERI node as well? Should we restart Mongod after making changes?

**Comment by javiquinte** [comment]
Thanks @comoglu ! Let's keep this closed considering that you already check the existence of the index. In the case that something pops up we'll open a new issue.

> KOERI node must be responding as the others by now.
