### ISSUE TITLE
[Federator] Webservices are offline!

### ISSUE THREAD

**Issue by xrise75** [EIDA/userfeedback#122]
**Describe the problem**
From the webpage http://www.orfeus-eu.org/data/eida/webservices/ the webservices of Fdederator are offline. Calling the webservices fails.

 
**To Reproduce**
Provide URLs or something similar so that the error can be reproduced. Can you reproduce it?

**Screenshots**
Provide a copy of the errors/warning in text format or screenshots.

**Client**
Give details about the client used to query the service.

**Additional context**
When was the request executed (timestamp)?

**Comment by damb** [comment]
Hi @xrise75,

thanks for reporting.

The issue you're reporting is due to EIDA switching to HTTPS. Still `eidaws-federator` doesn't provide its API via HTTPS. However, accessing the service via HTTP should work. Also, the links under http://www.orfeus-eu.org/data/eida/nodes/FEDERATOR/ should be available.

Out of curiosity: how are you *calling* the web service?

Just in case you're using obspy:

```py
from obspy import UTCDateTime
from obspy.clients.fdsn import Client

c = Client("http://eida-federator.ethz.ch")
start = UTCDateTime("2020-01-01")
inv = c.get_stations(network="BW,CH", starttime=start)

print(inv)
```

.. which should print a list of all stations including both the `BW` and `CH` network.

**Comment by megies** [comment]
> c = Client("http://eida-federator.ethz.ch")

Out of curiosity.. is that internally using EIDAWS-routing and then assembling the data on top of that? So basically it would be like our `RoutingClient` just without the ability to use the token mechanism?

Should we add this service to our [list of FDSN nodes](https://docs.obspy.org/master/packages/obspy.clients.fdsn.html?highlight=URL_MAPPINGS#basic-fdsn-client-usage)?

**Comment by xrise75** [comment]
Thank you @damp,

I was calling through ObsPy. Then the EIDA webpage here (http://www.orfeus-eu.org/data/eida/webservices/) should change and point to http (not to https) because it is misleading.

@megies Personally I would add the service to the FDSN list of ObsPy

**Comment by damb** [comment]
> Out of curiosity.. is that internally using EIDAWS-routing and then assembling the data on top of that? So basically it would be like our `RoutingClient` just without the ability to use the token mechanism?

Yes and no. `eidaws-federator` uses it's dedicated routing API based on the underlying `eidaws-routing` configuration. But, yes, it is the federating API gateway of EIDA (though, still without restricted data access).

> Should we add this service to our [list of FDSN nodes](https://docs.obspy.org/master/packages/obspy.clients.fdsn.html?highlight=URL_MAPPINGS#basic-fdsn-client-usage)?

That sounds good. Do you want me to open a PR?

**Comment by damb** [comment]
> I was calling through ObsPy. 

So you were not using `eidaws-federator`, but ObsPy's client side federation mechanism.

> Then the EIDA webpage here (http://www.orfeus-eu.org/data/eida/webservices/) should change and point to http (not to https) because it is misleading.

It's currently WIP. So instead of changing the webpage, I'd leave it like that. `eidaws-federator` will soon make it's API accessible via HTTPS.

**Comment by megies** [comment]
> That sounds good. Do you want me to open a PR?

Sure! There's two places to add it. Besides `header.py` there's also a doctest in `__init__.py` what is showing it to the users on the FDSN API front page.

**Comment by jschaeff** [comment]
Closing this issue.
