### ISSUE TITLE
No info webpage at http://eida-federator.ethz.ch/fdsnws

### ISSUE THREAD

**Issue by megies** [EIDA/userfeedback#123]
Might be good to display the same webpage that is shown at
 - http://eida-federator.ethz.ch/  and
 - http://eida-federator.ethz.ch/fdsnws/dataselect

also at http://eida-federator.ethz.ch/fdsnws (which is just showing a generic "missing page")

**Comment by damb** [comment]
Thanks for your opening the issue.

Of course, we can configure a redirect.

CC @kaestli

**Comment by Forextrade234** [comment]
hi

**Comment by sheimers** [comment]
Done. Also for http://eida-federator.ethz.ch/eidaws

Diff for the http.conf file:

```
-    location ~ ^/(fdsnws/(dataselect|station))|(eidaws/wfcatalog)/1/$ {
+    location ~ ^/(fdsnws/(dataselect|station))|(fdsnws)|(eidaws)|(eidaws/wfcatalog)/1/$ {
       # redirect to landing page
       rewrite ^ / last;
     }
```
