### ISSUE TITLE
[Metadata] Multiple Issues with response files

### ISSUE THREAD

**Issue by Ryan-isc** [EIDA/userfeedback#124]
Hi,

I am a developer at the International Seismological Centre and was wondering who would be the correct person to contact regards a variety of issues that we have encountered with downloaded response files across multiple networks. I figure it might be better to have a general conversation about them rather than submit each one as a separate issue.

For context we believe we are in a position to discuss/help with these potential issues as we monthly download all available response files using obspy for B,H,S,E High Gain Seismometer channels.

Regards

Dr. Ryan Gallacher

**Comment by jbienkowski** [comment]
Issue continued in a mailing thread, closing it here. Thank you, @Ryan-isc!
