### ISSUE TITLE
Change from restricted to open access for network 2C COSEISMIQ

### ISSUE THREAD

**Issue by friva97** [EIDA/userfeedback#126]
Please provide the following information in the content of the issue:
I am using Orfeus client to get waveforms using the temporary network 2C belonging to the COSEISMIQ project. On the website I checked the station book and for 2C network thee data are "R" so restricted. Is it possible to open it in order to be able to download the waveforms ? 

Thank you

**Comment by friva97** [comment]
Hello. I would like to download data from the network 4Q (Island) for the
COSEISMIQ experiment. However it is said that "No data available for
request" wwhe I try to doownload them wwith obspy using client "ETH" . How
can I do?
thank you
Federica Riva

Il giorno lun 18 lug 2022 alle ore 19:21 jfclinton ***@***.***>
ha scritto:

**Comment by andres-h** [comment]
4Q is hosted at GFZ and has open access, so please use a routing client or download data from node "GFZ" directly.
