### ISSUE TITLE
Can't download MSEED data for stations `MANEM`, `KBL`

### ISSUE THREAD

**Issue by Qian-Zhou3** [EIDA/userfeedback#128]
I am trying to download mseed data from Networks TJ and IU, specifically from stations MANEM and KBL (IRIS dataclient), and I cannot get them. The error is the following:

"Received no routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query
did not receive routes to IU.KBL..BH?"

Similarly, when downloading TJ.MANEM.

Previously, I have downloaded data from GE.KBU (GFZ dataclient) and it worked fine.

Could you help me?

**Comment by damb** [comment]
Thanks for reporting.

Could you please explain more in detail how your're trying to download the MSEED data? Are you using obspy?

**Comment by Qian-Zhou3** [comment]
Thanks for your fast reply! Yes, I am using obspy. This are some of the error message that I have got:

load catalogue from  /home/zhouQ/Desktop/folder/fetch_rf_data-main/IU/PRF-EVENTS.txt

  /home/zhouQ/Desktop/folder/fetch_rf_data-main/IU/IU.KBL/KBL.MSEED already exist.

  You have 3 options to proceed:
  delete existing file and proceed with data-request (Y)
  Do not delete file and exit (N)
  Use existing file to generate Qfile (U)

  Default answer is Y, you have 10 seconds to reply

  Please select: (Y/N/U): Y
delete /home/zhouQ/Desktop/folder/fetch_rf_data-main/IU/IU.KBL/KBL.MSEED

create bulk request


Check inventory for available channels for station KBL

Inventory created at 2022-08-15T20:41:50.506000Z
    Created by: IRIS WEB SERVICE: fdsnws-station | version: 1.1.48
            
    Sending institution: IRIS-DMC (IRIS-DMC)
    Contains:
        Networks (1):
            IU
        Stations (1):
            IU.KBL (Kabul, Afghanistan)
        Channels (3):
            IU.KBL..BHZ, IU.KBL..BHN, IU.KBL..BHE

    BH channel is available --> request BH channels
create acrlinke file from bulk
send fdsnws_fetch request
received no routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query
did not receive routes to IU.KBL..BH?
/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/io/css/core.py:25: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b'c0': (b'S12', np.int),
/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/io/css/core.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  b'c#': (b'S12', np.int),
Traceback (most recent call last):
  File "get_data_single_station_bulk.py", line 374, in <module>
    st=obspy.read(directory+"/"+station+".MSEED")
  File "<decorator-gen-31>", line 2, in read
  File "/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 300, in _map_example_filename
    return func(*args, **kwargs)
  File "/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/core/stream.py", line 212, in read
    st = _generic_reader(pathname_or_url, _read, **kwargs)
  File "/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/core/util/base.py", line 702, in _generic_reader
    generic = callback_func(pathnames[0], **kwargs)
  File "<decorator-gen-32>", line 2, in _read
  File "/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/core/util/decorator.py", line 210, in uncompress_file
    result = func(filename, *args, **kwargs)
  File "/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/core/stream.py", line 256, in _read
    stream, format = _read_from_plugin('waveform', filename, format=format,
  File "/work/software/conda/2020.11/envs/seispy_env/lib/python3.8/site-packages/obspy/core/util/base.py", line 450, in _read_from_plugin
    raise TypeError('Unknown format for file %s' % filename)
TypeError: Unknown format for file /home/zhouQ/Desktop/folder/fetch_rf_data-main/IU/IU.KBL/KBL.MSEED
sys:1: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/zhouQ/Desktop/folder/fetch_rf_data-main/IU/IU.KBL/IU.KBL.log' mode='a' encoding='UTF-8'

**Comment by Qian-Zhou3** [comment]
I can get data without problem from other data clients but for IRIS is getting this error message.

**Comment by jschaeff** [comment]
I can see here http://fdsn.org/networks/detail/IU/ that IU is hosted by 3 datacenters: AUSPASS, IRIS and UIB

The routes should be published by the central routing system of EIDA, and collected from what provides UIB-NORSAR.

UIB-NORSAR publishes metadata for two stations in IU: https://eida.geo.uib.no/fdsnws/station/1/query?net=IU&level=station

My guess is that those station are not published on UIB routes. @jan-michalek could you take a look ?

**Comment by jan-michalek** [comment]
UIB-NORSAR is sharing only selected station from IU network (see below) which are located in Norway. IRIS is hosting IU network and should be used for getting data.

IU stations in UIB-NORSAR FDSNWS:
```
#Network|Station|Latitude|Longitude|Elevation|SiteName|StartTime|EndTime
IU|KBS|78.9154|11.9385|90.0|Ny-Alesund, Spitzbergen, Norway|2010-06-08T00:00:00|
IU|KONO|59.6491|9.5982|216.0|Kongsberg, Norway|2009-09-12T15:02:42|
```

**Comment by javiquinte** [comment]
Yes, as @jan-michalek said, IRIS is the authoritative data centre for IU. The reason to expose some years ago these few stations is a legacy thing. UiB can locally expose them because of whatever reason, but they don't come to EIDA anymore.

At least, AFAIC remember, this was the agreement when we started to check consistency/coherency with our US colleagues.
