### ISSUE TITLE
cannot dowmload mseed files from the center of 'ODC'

### ISSUE THREAD

**Issue by Tangxiaotian11** [EIDA/userfeedback#129]
**Describe the problem**
I used a different download methods  to get mseed files from the center of 'ODC',  for example 'Z3.A001A' and 'Z3.A002A', but failed.  Is there a problem with the servers in this data center, and if so, how do I get this mseed files ?

**To Reproduce**

**Screenshots**
Provide a copy of the errors/warning in text format or screenshots.

**Client**
Give details about the client used to query the service.

**Additional context**

**Comment by Tangxiaotian11** [comment]
> **Describe the problem** I used a different download methods to get mseed files from the center of 'ODC', for example 'Z3.A001A' and 'Z3.A002A', but failed. Is there a problem with the servers in this data center, and if so, how do I get this mseed files ?
> 
> **To Reproduce**
> 
> **Screenshots** Provide a copy of the errors/warning in text format or screenshots.
> 
> **Client** Give details about the client used to query the service.
> 
> **Additional context** Add any other context about the problem here.

**Comment by jschaeff** [comment]
Hello,

thank you for reporting your problem. 
Indeed, DC seems down or slow since yesterday. 

But this morning I'm able to get metadata (https://orfeus-eu.org/fdsnws/station/1/query?net=Z3) and data (https://orfeus-eu.org/fdsnws/dataselect/1/query?net=Z3&starttime=2020-01-01&endtime=2020-01-05).

@jbienkowski did you have any issue yesterday ?

**Comment by jbienkowski** [comment]
Dear @Tangxiaotian11 ,

It might be that you have experienced issues related to the infrastructure maintenance works performed by our hardware provider between 1:00 and 5:00 AM UTC. Right now performance of all services is back to normal.

Regards,
Jarek
