### ISSUE TITLE
[EIDA-availability web tool] Routing broken / federator web service not available?

### ISSUE THREAD

**Issue by flixha** [EIDA/userfeedback#130]
**Describe the problem**
When checking data availability with the [EIDA availability web tool](http://www.orfeus-eu.org/data/eida/quality/availability/), any request currently returns an `Error 500: Internal server error`.

**To Reproduce**
Try to request, e.g. "NS", "BER, "2018-01-01", 2018-12-31" in the [EIDA availability web tool](http://www.orfeus-eu.org/data/eida/quality/availability/)

- This is independent of the EIDA node, I tried stations from UIB-NORSAR, GFZ, NOA, RESIF...
- Occurs both when using http or https version of the above linked webpage

**Error report**
```html
OOPS! The WFCatalog returned the following error:


Error 500: Internal server error

Error while routing: 500, message='INTERNAL SERVER ERROR', url=URL('http://eidaws-stationlite:8089/eidaws/routing/1/query?service=wfcatalog&format=post&access=any&network=NS&station=BER&location=*&channel=?DF,HG?,?H?&starttime=2018-01-01T00:00:00&endtime=2018-12-31T00:00:00')

Usage details are available from http://www.fdsn.org/webservices/

Request:
http://federator.orfeus-eu.org/fedws/wfcatalog/json/1/query?include=sample&net=NS&sta=BER&start=2018-01-01&end=2018-12-31&cha=HG?,?H?,?DF

Request Submitted:
2022-08-24T16:02:42.064453

Service version:
0.12.1
```

**Client**
Firefox and Chrome webbrowsers

**Comment by kaestli** [comment]
i acknowledge the issue; i am looking into it...

**Comment by kaestli** [comment]
The issue is solved. It was a mis-administration on our side (docker container of one component restarted without network bindings)

all requests to the federator, and with this, the availability portal should be up and working again.

**Comment by flixha** [comment]
Yes it's working again, thanks for fixing!
