### ISSUE TITLE
[EIDA token]

### ISSUE THREAD

**Issue by rafa0110** [EIDA/userfeedback#131]
Hi!
I got access to an EIDA token to download waveforms from restricted data (network 4C). 
To get the token I have registered and established a month period validity on the website. Immediately,  a file called 'index.eidatoken' was downloaded. 

At the moment I am trying to get the data, but without success.  I have tried:

------------------------------------------------------------------------------------------------------------------------------------------------------------------
from obspy.clients.fdsn import Client
from obspy import UTCDateTime

start_time=UTCDateTime(2017,11,1,0,0,0) 
end_time= UTCDateTime(2019,1,1,0,5,0)
cl = Client("GFZ", debug=True)
cl.set_eida_token('index(4).eidatoken',validate=True)
st = cl.get_waveforms(network="4C", station="*", location="*", channel="*", starttime=start_time, endtime=end_time)
print(st)

-----------------------------------------------------------------------------------------------------------------------------------------------------------------
The error is the following:
-----------------------------------
FDSNBadGatewayException: Service responds: Bad gateway 
HTTP Status code: 502
Detailed response of server:
------------------------------------------------------------------------------------------------------------------------------------------------------------------
The header of the given token is:
ash: SHA1
{"valid_until": "2022-09-29T12:57:23.104045Z", "cn": "Rafael Acosta Marcano", "memberof": "/", "sn": "Acosta", "issued": "2022-08-30T12:57:23.104051Z", "mail": "rafael.acosta@student.kit.edu", "givenName": "Rafael", "expiration": "1m"}

It is my first time doing this procedure. Could someone help me?

**Comment by javiquinte** [comment]
Hi @rafa0110 .
GEOFON was experiencing severe problems last evening in the web services due to what we guess it was an "unintentional" attack from some IPs, putting our system under a lot of stress. We solved it this morning, so you should probably try again.

Please, let us know if you succeed or not.

BTW, I would suggest you to take a look at the documentation offered in the EAS page.
https://geofon.gfz-potsdam.de/eas/EIDAAuthenticationService.pdf

**Comment by jschaeff** [comment]
Closing this issue. If the problem persist, please open it again.
