### ISSUE TITLE
[Federator] Secure the eidaws-federator web page/service with HTTPS

### ISSUE THREAD

**Issue by web-sys1** [EIDA/userfeedback#134]
**Describe the problem**
I suggest switching the http://eida-federator.ethz.ch web domain protocol from HTTP to HTTPS.

**Screenshots**
![ORFEUS_EIDA  www orfeus-eu org_1668021684742](https://user-images.githubusercontent.com/61905565/200922985-d777cecb-2dbd-4fc0-a49d-9092b8bacaae.png)

**Additional context**
At http://www.orfeus-eu.org/data/eida/webservices/ the warning banner says that _**data centers which did not enable HTTPS yet might temporarily appear in table below as "Offline" while still being fully operational via HTTP**_.
![003 - ORFEUS - EIDA Webservices - www orfeus-eu org](https://user-images.githubusercontent.com/61905565/200923201-a09cf4e3-cfb8-42b1-b63c-d15f9465918c.png)

 I think Federator is the only website that doesn't even serve through SSL.

**Comment by web-sys1** [comment]
When try to go to https://eida-federator.ethz.ch/  I'm getting error mesage like Connection refused (__ERR_CONNECTION_REFUSED__)

**Comment by kaestli** [comment]
At the moment, the federator is not available under https. http (unencrypted) is the preferred protocol, as the federator provides open access data and does not require or support authentication.
