### ISSUE TITLE
Unable to source live data from Iceland on VI network on Swarm for 3days since 23/12/2022

### ISSUE THREAD

**Issue by muzzylivestream2** [EIDA/userfeedback#136]
**Unable to source live data from Iceland network VI using Swarm.
Checked that eida.orfeus-eu.org source was working by opening a station in Holland was just fine**

*Client**
USGS Swarm

![eida orfeus-eu orgscreenshot](https://user-images.githubusercontent.com/86986085/209447221-cefd23b4-49a6-4386-83a1-17df0a5ec4c5.jpg)

**Comment by flixha** [comment]
It looks like on 2022-12-22, the streaming (via Seedlink) of data for stations FAB, ADA, GIL, ISKR, ASB (those were generally openly available) stopped. Since then EIDA availability shows no data available in the archives for these stations.

**Comment by jbienkowski** [comment]
Hi,
The infrastructure at Icelandic Met Office is being upgraded, we expect the connection to be restored today in the afternoon.

**Comment by jbienkowski** [comment]
Good morning,
The VI network is online again with the exception of VI.GOD stations which is off due to hardware issues.
Regards,
J
