### ISSUE TITLE
Broken link for user feedback on EIDA page

### ISSUE THREAD

**Issue by ftilmann** [EIDA/userfeedback#137]
Note that on this webpage there is still a (defunct) link to the non-existing user feedback form 

http://www.orfeus-eu.org/data/eida/
(in the yellow box below the map)

A comment: Although most users are likely familiar with github, an alternative means of contacting EIDA should be provided for those users who do not want to make a github account. It could probably even be set up that a contact form entry automatically generates an issue.

**Comment by jbienkowski** [comment]
Link has been removed. We are indeed planning to add functionality to create a new issue directly from the website without the need for a GitHub account. Thank you, @ftilmann!
