### ISSUE TITLE
[Service] Station Book not showing any stations

### ISSUE THREAD

**Issue by ttezel1** [EIDA/userfeedback#138]
The station book page is not responding. I am wondering if there is a problem or changed something. 

<img width="1371" alt="Screenshot 2023-02-08 at 11 26 40" src="https://user-images.githubusercontent.com/124784974/217517031-4034a4b3-a0cb-4a61-8d35-69e96317f630.png">

Kind Regards

**Comment by jbienkowski** [comment]
Hi @ttezel1,
Thank you for reporting this. It was an issue with processing of timezone-aware timestamps as EIDA is moving away from naive ones. It has been fixed now.
Regards,
Jarek
