### ISSUE TITLE
Unable to retrive part of the data for 4C network 

### ISSUE THREAD

**Issue by Qian-Zhou3** [EIDA/userfeedback#139]
Hi!
I got a token to download restricted data from 4C* network in Afghanistan II.
I am supposed to get data starting from  about 2017-10  until 2019-12-31. However, I am getting data until 2019.02 and not to 2019-12-31.

I am getting the "http status code 204" for data from 02.2019 to 31.12.2019
Someone could help me?
Let me know if you require more details or a description of the token.
Thanks in advance!

**Comment by javiquinte** [comment]
Hi @Qian-Zhou3 !
You can check the real availability of the data from the following link
https://geofon.gfz-potsdam.de/waveform/archive/data.php?ncode=4C&year=2019

**Comment by Qian-Zhou3** [comment]
Thank you @javiquinte
