### ISSUE TITLE
GR.GRA1.BH* available via IRIS

### ISSUE THREAD

**Issue by tesch** [EIDA/userfeedback#14]
*Client*: ObsPy 1.1.1 FDSN Client, Python 3.7.3
*Station*: GR.GRA1
*Auth*: none
*Date*: 2019-05-22

The GR network is distributed exclusively via `http://eida.bgr.de`, except for GR.GRA1.BH*, which is also available via `http://service.iris.edu`, though GR.GRA1.[LH]H* exist as well, but only at BGR. Is that right, it seems somewhat random?

```
from obspy import UTCDateTime
from obspy.clients.fdsn import Client

network = 'GR'
station = '*'

channel = '*'
location = '*'

for url in ('http://eida.bgr.de', 'http://service.iris.edu'):
    client = Client(url)

    inventory = client.get_stations(
        network=network,
        station=station,

        starttime=UTCDateTime('2010-01-01'),
        endtime=UTCDateTime('2019-04-30'),

        level='channel')

    print(inventory)
```

**Comment by javiquinte** [comment]
Hi @tesch 
I'm transferring your question to the BGR admins. Let's wait for their answer.
Thanks for the feedback!

**Comment by bgr-mhoffmann** [comment]
@tesch : BGR will check the configuration ... thank you for the hint !

**Comment by bgr-mhoffmann** [comment]
Iris is subscribing/distrubuting only some channels for GR.GRA1.
