### ISSUE TITLE
[Service] No stations shown on odc realtime

### ISSUE THREAD

**Issue by paitor** [EIDA/userfeedback#140]
Hi

At present no stations are shown on the map at: 
[http://www.orfeus-eu.org/data/odc/realtime/](url)

![liveWaveform](https://user-images.githubusercontent.com/12034761/219899379-b2b1507a-5bd4-417e-9369-efce0d665180.png)

Making it a bit hard to click on a station to view the live waveform

Webpage visited 2023-02-18 21:00 UTC using Firefox 109.0.1 on ubuntu 18.04.6 LTS

**Comment by jbienkowski** [comment]
Hi @paitor,
It should be fixed now, there was an issue with the certificate.
