### ISSUE TITLE
No Data from 1Y at NOA

### ISSUE THREAD

**Issue by esokos** [EIDA/userfeedback#145]
Hello all,
i have problem retrieving data from EIDA@NOA using a token for network 1Y. 
I am using the following

* Type of client used
i am using a small python code and use_token.get_waveforms command

* Stations and time windows requested 
1Y.GR01, from 2023-01-01T00:00:00.00 to 2023-02-28T23:59:59.00 (availability plot depicts that data are present!)

* snippet of code if feasible (e.g. 2-3 important lines from Obspy or command from console)
use_token = Client('NOA', debug=True, eida_token='M:/eida_token/eidatoken')
t1 = UTCDateTime("2023-01-01T00:00:00.00")
t2 = UTCDateTime("2023-02-28T23:59:59.00")
stationlist=["GR01"]
net = "1Y"

for x in stationlist:
    print(x)
    sta=x
# Z
    st = use_token.get_waveforms(net, sta, "*", "HHZ", t1, t2, attach_response=True)
    inv = use_token.get_stations(network=net, station=sta, channel='HHZ', starttime=t1 ,endtime=t2, level="response")
......

* details about the authentication (e.g. using arclink user? using an EIDA token?) If a token is used, the user could copy-paste the readable part where all attributes are present. NOT the full token! (That is private)
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1
{"valid_until": "2023-06-14T10:41:43.862191Z", "cn": "Efthimios Sokos", "memberof": "/", "sn": "Sokos", "issued": "2023-05-15T10:41:43.862195Z", "mail": "esokos@upatras.gr", "givenName": "Efthimios", "expiration": "1m"}
-

* screenshot or copy/paste of the error
(output)

Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x00000193021A5A80>]
Base URL: http://eida.gein.noa.gr
Request Headers: {'User-Agent': 'ObsPy/1.4.0 (Windows-10-10.0.19044-SP0, Python 3.10.10)'}
Loading discovered services from cache.
Downloading https://eida.gein.noa.gr/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2023-06-14T10:41:43.862191Z", "cn": "Efthimios Sokos", "memberof": "/", "sn": "Sokos", "issued": "2023-05-15T10:41:43.862195Z", "mail": "esokos@upatras.gr", "givenName": "Efthimios", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
-----END PGP SIGNATURE-----
---------------------------------------------------------------------
Downloaded https://eida.gein.noa.gr/fdsnws/dataselect/1/auth with HTTP code: 200
Got temporary user/pw: 5N8cXHFyGlZbGNiEPpEUIA3u/OScr7X-BfGtTeaGd
Installed new opener with handlers: [<urllib.request.HTTPDigestAuthHandler object at 0x00000193021A51B0>, <obspy.clients.fdsn.client.NoRedirectionHandler object at 0x00000193021A5000>]
GR01
Downloading http://eida.gein.noa.gr/fdsnws/dataselect/1/queryauth?starttime=2023-01-01T00%3A00%3A00.000000&endtime=2023-02-28T23%3A59%3A59.000000&network=1Y&station=GR01&location=%2A&channel=HHZ without requesting gzip compression
Downloaded http://eida.gein.noa.gr/fdsnws/dataselect/1/queryauth?starttime=2023-01-01T00%3A00%3A00.000000&endtime=2023-02-28T23%3A59%3A59.000000&network=1Y&station=GR01&location=%2A&channel=HHZ with HTTP code: 204
Traceback (most recent call last):
  File ~\anaconda3\envs\obspy\lib\site-packages\spyder_kernels\py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~\comp_ppsd_1y.py:44
    st = use_token.get_waveforms(net, sta, "*", "HHZ", t1, t2, attach_response=True)

  File ~\anaconda3\envs\obspy\lib\site-packages\obspy\clients\fdsn\client.py:872 in get_waveforms
    data_stream = self._download(url, use_gzip=False)

  File ~\anaconda3\envs\obspy\lib\site-packages\obspy\clients\fdsn\client.py:1486 in _download
    raise_on_error(code, data)

  File ~\anaconda3\envs\obspy\lib\site-packages\obspy\clients\fdsn\client.py:1813 in raise_on_error
    raise FDSNNoDataException("No data available for request.",

FDSNNoDataException: No data available for request.
HTTP Status code: 204
Detailed response of server:

* when was this exactly done?
 15/5/2023

**Comment by javiquinte** [comment]
Hi @esokos 
Thanks for your feedback.
What I can see is that network "1Y" is not available at NOA. Check the list of *all* available networks at NOA.

https://eida.gein.noa.gr/fdsnws/station/1/query?format=text&level=network

```
#Network|Description|StartTime|EndTime|TotalStations
5S|Icelandic Strong-motion Arrays|2019-01-01T00:00:00|2022-12-31T00:00:00|56
CQ|Cyprus Broadband Seismological Network|2013-01-01T00:00:00||13
EG|EUROSEISTEST Strong Motion Network (SDGEE_AUTH)|1993-01-01T00:00:00||13
HA|National and Kapodistrian University of Athens, Seismological Laboratory (NKUA)|2008-01-01T00:00:00||40
HC|Seismological Network of Crete|2006-01-01T00:00:00||51
HI|Institute of Engineering Seismology and Earthquake Engineering (ITSAK) Strong Motion Network|1981-01-01T00:00:00||30
HL|Hellenic Seismic Network|1997-01-01T00:00:00||126
HP|University of Patras, Seismological Laboratory (PSLNET)|2000-01-01T00:00:00||28
HT|Aristotle University of Thessaloniki Seismological Network|1981-01-01T00:00:00||63
ME|Montenegrian Seismic Network|2008-01-01T00:00:00||6
X5|LF (Lefkada temporary network)|2015-11-18T00:00:00|2016-04-27T00:00:00|6
YB|Trichonis Lake network|2007-04-11T00:00:00|2007-05-03T00:00:00|8
```

**Comment by esokos** [comment]
Hello @javiquinte 
i didn't check this, you are right, it is not listed ....

i don't know if it is because data are restricted or due to an error. Since i have downloaded data in the past and the 1Y network is indicated in front page of EIDA @NOA (https://eida.gein.noa.gr/)i would say it is an error.

**Comment by javiquinte** [comment]
You are totally right. This network should be included as it was announced some weeks ago. Let's wait that someone from NOA clarifies this.

**Comment by kbouk** [comment]
Hello,
A routine step during the inventory preparation failed today for network 1Y, for no apparrent reason. I have the disabled this step and network 1Y is now available in our FDSNWS.
Thank you Thymios for brining it to our attention.
Best regards.

**Comment by javiquinte** [comment]
1Y seems to be there again.
https://eida.gein.noa.gr/fdsnws/station/1/query?format=text&level=network&network=1Y

```
#Network|Description|StartTime|EndTime|TotalStations
1Y|Greece / North Macedonia AdriaArray|1980-01-01T00:00:00||35
```
