### ISSUE TITLE
[Service] FDSN server eida-sc3.infp.ro goes down.

### ISSUE THREAD

**Issue by web-sys1** [EIDA/userfeedback#150]
I'm trying to fetch data from NIEP server (eida-sc3.infp.ro), but server is unreachable.

**To Reproduce**

https://eida-sc3.infp.ro/fdsnws/dataselect/1/
https://eida-sc3.infp.ro/fdsnws/station/1/
https://eida-sc3.infp.ro/eidaws/routing/1/
https://eida-sc3.infp.ro/eidaws/wfcatalog/1/
https://eida-sc3.infp.ro/fdsnws/availability/1/

**Screenshots**
![C012 - ORFEUS - EIDA Webservices - www orfeus-eu org](https://github.com/EIDA/userfeedback/assets/61905565/11168bf1-f1cc-4903-94a2-4192562f4689)

**Client**
EIDA NODE : [NIEP](https://www.orfeus-eu.org/data/eida/nodes/NIEP/)

**Additional context**

eida-sc3.infp.ro/fdsnws/dataselect/1/version:1     Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
eida-sc3.infp.ro/fdsnws/station/1/version:1     Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
eida-sc3.infp.ro/eidaws/wfcatalog/1/version:1     Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
eida-sc3.infp.ro/eidaws/routing/1/version:1     Failed to load resource: net::ERR_CONNECTION_TIMED_OUT
eida-sc3.infp.ro/fdsnws/availability/1/version:1     Failed to load resource: net::ERR_CONNECTION_TIMED_OUT

**Comment by web-sys1** [comment]
I was unable to fetch data archive using Python code through Obspy.

```
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x000001BB23728040>]
Base URL: http://eida-sc3.infp.ro
Request Headers: {'User-Agent': 'ObsPy/1.4.0 (Windows-10-10.0.19045-SP0, Python 3.10.12)'}
Downloading http://eida-sc3.infp.ro/fdsnws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://eida-sc3.infp.ro/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://eida-sc3.infp.ro/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://eida-sc3.infp.ro/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://eida-sc3.infp.ro/fdsnws/event/1/contributors with requesting gzip compression
Error while downloading: http://eida-sc3.infp.ro/fdsnws/dataselect/1/application.wadl
Error while downloading: http://eida-sc3.infp.ro/fdsnws/station/1/application.wadl
Error while downloading: http://eida-sc3.infp.ro/fdsnws/event/1/contributors
Error while downloading: http://eida-sc3.infp.ro/fdsnws/event/1/catalogs
Error while downloading: http://eida-sc3.infp.ro/fdsnws/event/1/application.wadl
Traceback (most recent call last):
  File "fetchfdsn.py", line 11, in <module>
    client = Client("NIEP", debug=True)
  File "D:\anaconda3\Lib\site-packages\obspy\clients\fdsn\client.py", line 277, in __init__
    self._discover_services()
  File "D:\anaconda3\Lib\site-packages\obspy\clients\fdsn\client.py", line 1638, in _discover_services
    raise FDSNNoServiceException(msg)
obspy.clients.fdsn.header.FDSNNoServiceException: No FDSN services could be discovered at 'http://eida-sc3.infp.ro'. This could be due to a temporary service outage or an invalid FDSN service address.
```

My code:

``` python
from obspy.clients.fdsn import RoutingClient
from obspy.signal.util import *
from obspy import UTCDateTime
from obspy.clients.fdsn import Client                                                                                                                                          

t1 = UTCDateTime.now()
t1.isoformat()
start = t1 - 60*60
end = start + 60*60

client = Client("NIEP", debug=True)  
st = rtClient.get_waveforms(
        network='RO',
        station='*',
        location='--',
        channel='?HZ',
        starttime=start - 60,
        endtime=end + 60,
    )
    
print(st)  
```

**Comment by web-sys1** [comment]
Not even [eida-federator](http://eida-federator.ethz.ch/) could fetch data archive.

```
Error 404: 

Usage details are available from http://www.fdsn.org/webservices/

Request:
http://eida-federator.ethz.ch/fedws/dataselect/miniseed/1/query?starttime=2023-09-19&endtime=2023-09-22T00%3A06%3A00&network=RO&station=%2A&location=%2A&channel=BH%3F&format=miniseed&nodata=404

Request Submitted:
2023-09-26T18:43:01.803220

Service version:
0.12.1
```

**Comment by jschaeff** [comment]
NIEP is down for a maintenance on disks that lasts longer than expected.

http://forum.orfeus-eu.org/t/niep-eida-node-down-for-maintenance/555

**Comment by web-sys1** [comment]
@jschaeff @javiquinte while NIEP FDSNWS services is experiecing issues, the Centre doesn't have seedlink server or it may be no longer active: venus.infp.ro:18000

**Comment by jschaeff** [comment]
Yes, this makes sense as it is powered by the same systems.

**Comment by web-sys1** [comment]
Possibly maintenance could last a week or more.

**Comment by javiquinte** [comment]
NIEP seems to be online again, but only the FDSN web services. To be checked!

**Comment by luvec** [comment]
Strangely, I cannot find network Y8 by FDSN web services now.

**Comment by javiquinte** [comment]
Hi @luvec !
It seems that Y8 is not even in the Station-WS of NIEP, so it is impossible that we can find it in EIDA.

https://eida-sc3.infp.ro/fdsnws/station/1/query?format=text&level=network 

> #Network|Description|StartTime|EndTime|TotalStations
BS|Bulgarian Seismic Network|1980-01-01T00:00:00||17
MD|Moldova Network|1980-01-01T00:00:00||3
RO|Romanian Seismic Network|1980-01-01T00:00:00||148
UD|UD network|1980-01-01T00:00:00||6

I'll open a new issue, as the problem is different from the one described here.

**Comment by cristianneagoe** [comment]
Hi all,

I am on the field installing the last stations from Adria. I will check the issue tomorrow morning when I will be back.

Best regards,

Cristian

**Comment by web-sys1** [comment]
Hi there,

Sorry I haven't been able to comment for a while. I would like to thank those who participated in solving the problem with connecting to the EIDA node of NIEP. Thanks @cristianneagoe for work done.

**Comment by web-sys1** [comment]
Hello @cristianneagoe @javiquinte @jschaeff

What is not working now on the FDSN node of [NIEP](https://eida-sc3.infp.ro/) are: [EIDAWS-WFCatalog](https://eida-sc3.infp.ro/eidaws/wfcatalog/1/), [EIDAWS-Routing](https://eida-sc3.infp.ro/eidaws/routing/1/), [FDSNWS-Availability](https://eida-sc3.infp.ro/fdsnws/availability/1/). 

![SC046 - ORFEUS - EIDA Webservices_20231211_T092240 orfeus-eu org](https://github.com/EIDA/userfeedback/assets/61905565/491aa256-47e7-46ff-a783-64a6685d3221)
![SC047 - eidaws_wfcatalog_ 20231211_0931 eida-sc3 infp ro](https://github.com/EIDA/userfeedback/assets/61905565/b16f9f51-7abe-4405-9073-b2b39973839f)
![SC048 - fdsnws_availability_20231211_0933T-eida-sc3 infp ro](https://github.com/EIDA/userfeedback/assets/61905565/c41325b1-a311-443e-99e4-c2dec58b0433)

I'm really worried about what happened to them since their FDSN server was down for a month.

**Comment by web-sys1** [comment]
Of 5 days ago I opened the issue of what is not working well on eida.infp.ro (WebDC). See issue #155

**Comment by cristianneagoe** [comment]
Hello,

We are now working to resolve the rest of the problems. If everything will go as expected everything will be online in maximum 2 weeks. I will keep you up to date. Sorry about the inconvenience.

Cristian

**Comment by web-sys1** [comment]
@cristianneagoe I hope it's solved with Seedlink as well.

**Comment by web-sys1** [comment]
Hello everyone.

Now it seems that **NIEP** servers were shut down. It says: **No route to host.**

Link: https://check-host.net/check-report/1403055ek494
![Screenshot_20231220_150855_Chrome](https://github.com/EIDA/userfeedback/assets/61905565/301031e8-a616-42e1-b952-3dfb8b639744)

**Comment by web-sys1** [comment]
Also [EIDA node server](https://eida-sc3.infp.ro/) down, not responding.

**Comment by javiquinte** [comment]
AFAICS the node is up, with the same status as last week (same services working, and same issues on some services).

@cristianneagoe Any updates?

**Comment by cristianneagoe** [comment]
Dear all,
There where some unexpected  issues with regional internet network (not locally at INFP). Now the node is up.
Now wfcatalog is scanning, as soon he will finish the first part we will put it online. The next issues are next.

**Comment by web-sys1** [comment]
Hello again.

More than two weeks have passed since his last message, @cristianneagoe promised that _if everything will go according to expectations, everything will be online in a maximum of 2 weeks_. The rest of the services, EIDAWS and fdsnws-availability, unlike FDSNWS (fdsnws-dataselect and fdsnws-station) which returned, remain unavailable/inaccessible. Last week, the NIEP operator reported that _wfcatalog is scanning, as soon as the first part is finished, we will put it online_.

**Comment by web-sys1** [comment]
@cristianneagoe
WFCatalog is back online, so late. It seems that there are problems with the data delivery service, the waveform cannot be collected on the BS, MD, or RO networks.

https://eida-sc3.infp.ro/fdsnws/dataselect/1/query?starttime=2024-01-05T00%3A00%3A00&station=*&channel=BH%3F,HH%3F&nodata=404 (**Broken pipe**, see [results](https://check-host.net/check-report/14666d44kf98))

**Comment by cristianneagoe** [comment]
Hi @web-sys1, (It would be nice if I could address you by your real name)

Thank you for pointing out this problem. Now Is resolved and FDSN is working.  Regarding WFcatalog, yes I know it was a little late, but unfortunately, there where some problems that were not expected. 
Best wishes in the New Year!!!
