### ISSUE TITLE
Y8 does not appear among the networks at NIEP

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#151]
It seems that Y8 is not even in the Station-WS of NIEP, so it is impossible that we can find it in EIDA.

https://eida-sc3.infp.ro/fdsnws/station/1/query?format=text&level=network 

> #Network|Description|StartTime|EndTime|TotalStations
BS|Bulgarian Seismic Network|1980-01-01T00:00:00||17
MD|Moldova Network|1980-01-01T00:00:00||3
RO|Romanian Seismic Network|1980-01-01T00:00:00||148
UD|UD network|1980-01-01T00:00:00||6

I'll open a new issue, as the problem is different from the one described here.

_Originally posted by @javiquinte in https://github.com/EIDA/userfeedback/issues/150#issuecomment-1784980852_

**Comment by web-sys1** [comment]
```
#Network|Description|StartTime|EndTime|TotalStations
BS|Bulgarian Seismic Network|1980-01-01T00:00:00||34
BS||2023-03-01T09:45:27||1
MD|Moldova Network|1980-01-01T00:00:00||3
RO|Romanian Seismic Network|1980-01-01T00:00:00||149
UD|UD network|1980-01-01T00:00:00||6
Y8|Adria Array Network|1980-01-01T00:00:00||49
Y8|IG CAS|2022-01-01T00:00:00||49
```
Looks it has been updated.

**Comment by javiquinte** [comment]
Hi @cristianneagoe !
Please, check that for Y8 and BS you have duplicated entries. For BS this seems to be wrong, as it is a permanent network.

In the case of Y8, remember that this network goes only from 2022 to 2026.

**Comment by web-sys1** [comment]
Data access to Y8 network have been restricted. Is there a solution to acquire the access to the network?

**Comment by cristianneagoe** [comment]
> Hi @cristianneagoe ! Please, check that for Y8 and BS you have duplicated entries. For BS this seems to be wrong, as it is a permanent network.
> 
> In the case of Y8, remember that this network goes only from 2022 to 2026.

Hi Javier, thank you for pointing this out. Now the problem is resolved.

**Comment by javiquinte** [comment]
> Data access to Y8 network have been restricted. Is there a solution to acquire the access to the network?

Dear user, to request access to restricted networks you should inform **at least** who you are, your institution, and if you have an ongoing cooperation with the PIs.

**Comment by javiquinte** [comment]
> > Hi @cristianneagoe ! Please, check that for Y8 and BS you have duplicated entries. For BS this seems to be wrong, as it is a permanent network.
> 
> > 
> 
> > In the case of Y8, remember that this network goes only from 2022 to 2026.
> 
> 
> 
> Hi Javier, thank you for pointing this out. Now the problem is resolved.

Thanks a lot @cristianneagoe !
I'll mark the issue as solved.
