### ISSUE TITLE
wrong example URL at ORFEUS web page

### ISSUE THREAD

**Issue by kaestli** [EIDA/userfeedback#152]
At the web page https://www.orfeus-eu.org/data/eida/nodes/FEDERATOR/, paragraph "disadvantages of the federator", the example URL 
 http://eida-federator.ethz.ch/fdsnws/station/query?network=*&station=*&channel=HHE,HHZ&start=2019-03-09&end=2019-03-10&level=response&format=xml
is lacking the fdsn service version number infix. It should be:
http://eida-federator.ethz.ch/fdsnws/station/1/query?network=*&station=*&channel=HHE,HHZ&start=2019-03-09&end=2019-03-10&level=response&format=xml

**Comment by jbienkowski** [comment]
Done!
