### ISSUE TITLE
[Federator] IP.PACT not present in the Federator

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#153]
I'm posting this on behalf of Susana Custodio. I haven't checked it myself.

> It was IP.PACT:
2007-01-24T092529.500000Z 	 PACT 	 BHE, BHN
I could get the data from ORFEUS but not through eida-federator (via obspy).
It’s a Portuguese station and I’m pretty sure it should be open

**Comment by kaestli** [comment]
At this time, I cannot replicate the issue on the federator (in general, station information is available and waveforms can be retrieved for this station and the time of interest mentioned.

I suppose either a transient issue, or an issue with the obspy request, maybe also a data gap, if you were requesting waveforms.
To verify the request, you can replicate the dataselect request i used below (network=IP&station=PACT&st2007-01-24T09:00:00&endtime=2007-01-24T10:00:00), and check whether you also retrieve 475kB of miniseed.

```
kaestli@schneckie:~$ curl 'http://eida-federator.ethz.ch/fdsnws/station/1/query?network=IP&station=PACT'
<?xml version="1.0" encoding="UTF-8"?><FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersionSource>EIDA-Federator</Source><Sender>EIDA</Sender><Created>2023-11-24T15:02:26.380473</Created><Network xmln//www.fdsn.org/xml/station/1" code="IP" startDate="1980-01-01T00:00:00" restrictedStatus="open"><Description>o Superior Tecnico Broadband Seismic</Description><Station code="PACT" startDate="2003-01-01T00:00:00" restrius="open"><Latitude>38.768</Latitude><Longitude>-8.833299</Longitude><Elevation>30</Elevation><Site><Name>ALCPORTUGAL</Name><Country>PORTUGAL</Country></Site><CreationDate>2003-01-01T00:00:00</CreationDate></Station></</FDSNStationXML>kaestli@schneckie:~$

kaestli@schneckie:~$ curl 'http://eida-federator.ethz.ch/fdsnws/dataselect/1/query?network=IP&station=PACT&st2007-01-24T09:00:00&endtime=2007-01-24T10:00:00' > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  696k    0  696k    0     0   475k      0 --:--:--  0:00:01 --:--:--  474k
kaestli@schneckie:~$

```

**Comment by megies** [comment]
Always remember to use `Client(..., debug=True)` in case of potential issues and it will show all URLs being downloaded etc. in obspy, which helps massively to see what's going on.

**Comment by jschaeff** [comment]
Self fixed issue :)
