### ISSUE TITLE
[Service] EIDAWS-Routing: no info from NOA node

### ISSUE THREAD

**Issue by luvec** [EIDA/userfeedback#156]
I'm not able to obtain any NOA station via the EIDAWS-Routing service. The routing for NOA stations was working last night, but not today.

No info from the routing service, direct service works:
https://www.orfeus-eu.org/eidaws/routing/1/query?service=station&network=HA
https://eida.gein.noa.gr/fdsnws/station/1/query?network=HA&format=text
A similar situation for other networks in NOA, e.g., 1Y, HC, HL, HP, HT, ME.

Webservices Status is green for the routing service in NOA:
![image](https://github.com/EIDA/userfeedback/assets/118819898/fc944eaf-30db-4002-be1f-0296043df200)

**Comment by javiquinte** [comment]
Hi @luvec !
NOA has published today an empty configuration for the routing service, and therefore you see no networks in EIDA.

@kbouk : Can you please fix the `routing.xml` file?

**Comment by kbouk** [comment]
Hello,

For some reason the daily update routing script returned only the virtual networks. Running it manually routed all the networks.
I'll investigate the reason of it.

Best regards,

Kostas

**Comment by kbouk** [comment]
@javiquinte 
How much time does it take for the routing service to be updated ?
routing.xml looks ok now.

**Comment by javiquinte** [comment]
> @javiquinte How much time does it take for the routing service to be updated ? routing.xml looks ok now.

That is a question for @jbienkowski  ;-)

**Comment by jbienkowski** [comment]
Hi all,

Routing update takes place nightly, it seems to be fixed already:

https://orfeus-eu.org/eidaws/routing/1/query?format=post

```
https://eida.gein.noa.gr/fdsnws/dataselect/1/query
YB * * * 2007-04-11T00:00:00 2007-05-03T00:00:00
X5 * * * 2015-11-18T00:00:00 2016-04-27T00:00:00
ME * * * 2008-01-01T00:00:00 2023-12-13
HT * * * 1981-01-01T00:00:00 2023-12-13
HP * * * 2000-01-01T00:00:00 2023-12-13
HL * * * 1997-01-01T00:00:00 2023-12-13
HI * * * 1981-01-01T00:00:00 2023-12-13
HC * * * 2006-01-01T00:00:00 2023-12-13
HA * * * 2008-01-01T00:00:00 2023-12-13
EG * * * 1993-01-01T00:00:00 2023-12-13
CQ * * * 2013-01-01T00:00:00 2023-12-13
5S * * * 2019-01-01T00:00:00 2022-12-31T00:00:00
5B * * * 2023-11-26T00:00:00 2027-12-31T00:00:00
1Y * * * 2022-01-01T00:00:00 2026-12-31T00:00:00
```

Cheers,
Jarek

**Comment by kbouk** [comment]
Hello,

I am not sure yet what caused the partial routing.xml file (no changes have been made and today the file is correct).
However I made two adjustments in our node:
1) Changed the update time of the routing.xml to take part during morning hours (so any possible problem, during update, won't be  propagated to orfeus eidaws.
2) Wrote a small script that checks the number of routes and sends a warning email if the number is small.

Best regards,

Kostas

**Comment by luvec** [comment]
My big thanks to you all, good job!
