### ISSUE TITLE
[Routing] Error when calling globalconfig

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#159]
The following URL gives an error for different users including FDSN Data Centre Registry.

http://www.orfeus-eu.org/eidaws/routing/1/globalconfig?format=fdsn

FDSN reports:
> This produced the following error:
Failed to retrieve the registry: 502 Server Error: Proxy Error for url: http://www.orfeus-eu.org/eidaws/routing/1/globalconfig?format=fdsn

From a browser:

> The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request [GET /eidaws/routing/1/globalconfig](http://orfeus-eu.org/eidaws/routing/1/globalconfig).
Reason: Error reading from remote server

**Comment by jbienkowski** [comment]
Hi,

Just for reference - discussion related to this issue continues in:
https://forum.orfeus-eu.org/t/odc-routing-service-update-on-january-15th-2024/804/8

Cheers,
Jarek
