### ISSUE TITLE
[No Data] No data from Alparray is received from INGV

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#16]
Using fdsnws_fetch with the normal example in the README page of this repository and from the User documentation INGV fails to send Alparray data. This command is run by many persons and the output is checked always for consistency so there is clearly an error there.

> authentication at https://webservices.ingv.it/fdsnws/dataselect/1/auth successful
getting data from http://webservices.ingv.it/fdsnws/dataselect/1/queryauth
received no data from http://webservices.ingv.it/fdsnws/dataselect/1/queryauth

This is *not* related to the DNS problem because the authentication works well.

The other four data centres send exactly the data which is expected.

This was run on May 24th at 10:10 AM.

**Comment by petrrr** [comment]
Reference for readability [README](https://github.com/EIDA/userfeedback/blob/master/README.md).

**Comment by petrrr** [comment]
@javiquinte:
From the example in the README, it looks like this has worked already.
Can you confirm this?

**Comment by petrrr** [comment]
@javiquinte: 
Could you post a current output of the example as seen in the README?

**Comment by petrrr** [comment]
@javiquinte: 
Are you manager of the AlpArray group?
Could you add me?

**Comment by javiquinte** [comment]
> @javiquinte:
> From the example in the README, it looks like this has worked already.
> Can you confirm this?

I said that in the description of the issue

> This command is run by many persons and the output is checked always for consistency so there is clearly an error there.

**Comment by javiquinte** [comment]
> @javiquinte:
> Could you post here a current output of the example as seen in the README?

The part related to INGV is in the description of the issue. The full output looks like this.

> $ fdsnws_fetch -vvv -N Z3 -C "HHZ" -s "2016-03-01" -e "2016-03-01T00:02:00" -o data.mseed
using token in /Users/javier/.eidatoken:
{"valid_until": "2019-06-23T08:08:26.591281Z", "cn": "Javier Quinteros", "memberof": "/epos/alparray;/epos;/", "sn": "Quinteros", "issued": "2019-05-24T08:08:26.591287Z", "mail": "javier@gfz-potsdam.de", "givenName": "Javier", "expiration": "1m"}
getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?endtime=2016-03-01T00%3A02%3A00&network=Z3&starttime=2016-03-01&channel=HHZ&format=post
authenticating at https://erde.geophysik.uni-muenchen.de/fdsnws/dataselect/1/auth
authenticating at https://webservices.ingv.it/fdsnws/dataselect/1/auth
authenticating at https://www.orfeus-eu.org/fdsnws/dataselect/1/auth
authentication at https://webservices.ingv.it/fdsnws/dataselect/1/auth successful
getting data from http://webservices.ingv.it/fdsnws/dataselect/1/queryauth
authentication at https://www.orfeus-eu.org/fdsnws/dataselect/1/auth successful
getting data from http://www.orfeus-eu.org/fdsnws/dataselect/1/queryauth
authentication at https://erde.geophysik.uni-muenchen.de/fdsnws/dataselect/1/auth successful
getting data from http://erde.geophysik.uni-muenchen.de/fdsnws/dataselect/1/queryauth
received no data from http://webservices.ingv.it/fdsnws/dataselect/1/queryauth
authenticating at https://eida.ethz.ch/fdsnws/dataselect/1/auth
authenticating at https://ws.resif.fr/fdsnws/dataselect/1/auth
record 786: blockette 1000 not found, stop reading
got 516608 bytes (application/vnd.fdsn.mseed) from http://erde.geophysik.uni-muenchen.de/fdsnws/dataselect/1/queryauth
authentication at https://ws.resif.fr/fdsnws/dataselect/1/auth successful
getting data from http://ws.resif.fr/fdsnws/dataselect/1/queryauth
authentication at https://eida.ethz.ch/fdsnws/dataselect/1/auth successful
getting data from http://eida.ethz.ch/fdsnws/dataselect/1/queryauth
got 906240 bytes (application/vnd.fdsn.mseed) from http://www.orfeus-eu.org/fdsnws/dataselect/1/queryauth
got 90112 bytes (application/vnd.fdsn.mseed) from http://ws.resif.fr/fdsnws/dataselect/1/queryauth
got 293888 bytes (application/vnd.fdsn.mseed) from http://eida.ethz.ch/fdsnws/dataselect/1/queryauth
did not receive data from Z3.A002B.*.HHZ, Z3.A015A.*.HHZ, Z3.A022A.*.HHZ, Z3.A023A.*.HHZ, Z3.A024B.*.HHZ, Z3.A025A.*.HHZ, Z3.A026A.*.HHZ, Z3.A027A.*.HHZ, Z3.A028A.*.HHZ, Z3.A028B.*.HHZ, Z3.A029A.*.HHZ, Z3.A030A.*.HHZ, Z3.A031A.*.HHZ, Z3.A032A.*.HHZ, Z3.A033A.*.HHZ, Z3.A034A.*.HHZ, Z3.A035A.*.HHZ, Z3.A036A.*.HHZ, Z3.A037A.*.HHZ, Z3.A038A.*.HHZ, Z3.A060A.*.HHZ, Z3.A060B.*.HHZ, Z3.A088B.*.HHZ, Z3.A100A.*.HHZ, Z3.A101A.*.HHZ, Z3.A102A.*.HHZ, Z3.A103A.*.HHZ, Z3.A103B.*.HHZ, Z3.A103D.*.HHZ, Z3.A104A.*.HHZ, Z3.A104B.*.HHZ, Z3.A105A.*.HHZ, Z3.A106A.*.HHZ, Z3.A107A.*.HHZ, Z3.A107B.*.HHZ, Z3.A107C.*.HHZ, Z3.A108A.*.HHZ, Z3.A109A.*.HHZ, Z3.A111A.*.HHZ, Z3.A112A.*.HHZ, Z3.A113A.*.HHZ, Z3.A113B.*.HHZ, Z3.A114A.*.HHZ, Z3.A115A.*.HHZ, Z3.A116A.*.HHZ, Z3.A117A.*.HHZ, Z3.A118A.*.HHZ, Z3.A118B.*.HHZ, Z3.A119A.*.HHZ, Z3.A121A.*.HHZ, Z3.A121B.*.HHZ, Z3.A122A.*.HHZ, Z3.A123A.*.HHZ, Z3.A124A.*.HHZ, Z3.A125A.*.HHZ, Z3.A126A.*.HHZ, Z3.A127A.*.HHZ, Z3.A128A.*.HHZ, Z3.A129A.*.HHZ, Z3.A140A.*.HHZ, Z3.A141A.*.HHZ, Z3.A148B.*.HHZ, Z3.A253A.*.HHZ, Z3.A254A.*.HHZ, Z3.A255A.*.HHZ, Z3.A268A.*.HHZ, Z3.A270A.*.HHZ, Z3.A273A.*.HHZ, Z3.A283B.*.HHZ, Z3.A300A.*.HHZ, Z3.A301A.*.HHZ, Z3.A302A.*.HHZ, Z3.A303A.*.HHZ, Z3.A304A.*.HHZ, Z3.A305A.*.HHZ, Z3.A306A.*.HHZ, Z3.A307A.*.HHZ, Z3.A308A.*.HHZ, Z3.A309A.*.HHZ, Z3.A313A.*.HHZ, Z3.A316A.*.HHZ, Z3.A317A.*.HHZ, Z3.A318A.*.HHZ, Z3.A319A.*.HHZ, Z3.A350A.*.HHZ, Z3.A351A.*.HHZ, Z3.A351B.*.HHZ, Z3.A352A.*.HHZ, Z3.A357B.*.HHZ, Z3.A364A.*.HHZ
retrieving network citation info
getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query
getting data from http://erde.geophysik.uni-muenchen.de/fdsnws/station/1/query
getting data from http://www.orfeus-eu.org/fdsnws/station/1/query
getting data from http://webservices.ingv.it/fdsnws/station/1/query
getting data from http://eida.ethz.ch/fdsnws/station/1/query
getting data from http://ws.resif.fr/fdsnws/station/1/query
got 151 bytes (text/plain) from http://www.orfeus-eu.org/fdsnws/station/1/query
got 144 bytes (text/plain) from http://webservices.ingv.it/fdsnws/station/1/query
got 115 bytes (text/plain) from http://erde.geophysik.uni-muenchen.de/fdsnws/station/1/query
got 136 bytes (text/plain) from http://ws.resif.fr/fdsnws/station/1/query
got 151 bytes (text/plain) from http://eida.ethz.ch/fdsnws/station/1/query
error parsing text format: need more than 1 value to unpack
You received seismic waveform data from the following network(s):
Z3_2015 AlpArray Seismic Network (AASN) temporary component
Acknowledgment is extremely important for network operators
providing open data. When preparing publications, please
cite the data appropriately. The FDSN service at
    http://www.fdsn.org/networks/citation/?networks=Z3_2015
provides a helpful guide based on available network
Digital Object Identifiers.
In case of problems with your request, plese use the contact form at
    http://www.orfeus-eu.org/organization/contact/form/?recipient=EIDA

**Comment by javiquinte** [comment]
> @javiquinte:
> Are you manager of the AlpArray group?
> Could you add me?

@sheimers is the Manager. Could you add @petrrr to the Alparray group, please?

**Comment by petrrr** [comment]
@javiquinte: Try to repeat my question from comment https://github.com/EIDA/userfeedback/issues/16#issuecomment-497098578in a bit clearer.

From the example in the README, it looks like query this has worked already for INGV as well some time back. It broke at a later stage after it was already confirmed to work.
Is this correct?

**Comment by sheimers** [comment]
> > @javiquinte:
> > Are you manager of the AlpArray group?
> > Could you add me?
> @sheimers is the Manager. Could you add @petrrr to the Alparray group, please?

Sorry, two problems. I don't know the real name of petrrr, and second I am only allowed to add people listed on the following table: http://alparray.ethz.ch/en/seismic_network/backbone/management/
So @petrrr, if you are on this list please tell me who you are, and if you are not yet on the list, the person from the column "Representative" of your institute has to inform me that you are a new member, then I'll add you to the list and also to the Alparray group on b2access.
Sorry for the inconvenience, it is not me who makes the rules.

**Comment by massimo1962** [comment]
Hi, actually seems that the auth mechanism is broken (it worked until a couple of weeks ago); we are investigating on it and will keep this thread update. 
Just to know, I have some issue with my personal b2access account but in meanwhile I'll use another working account.

**Comment by massimo1962** [comment]
after 1 day test, now the service is up and running; the access via group (epos/alparray) seems managed correctly. every feedback and further tests are welcome.

**Comment by javiquinte** [comment]
Thanks @massimo1962 !
