### ISSUE TITLE
[Service] Routing Client

### ISSUE THREAD

**Issue by doukutsu** [EIDA/userfeedback#160]
When trying to request data for the virtual network "_ADARRAY" from the routing client, the server gives a "no data available" response. This also seems to happen with other networks, for example:

```
from obspy.clients.fdsn import RoutingClient
from obspy import UTCDateTime
import os

token=os.path.expanduser('~/.eidatoken')
rsClient = RoutingClient("eida-routing",timeout=120,credentials={'EIDA_TOKEN': token})

t0 = UTCDateTime(2023, 9, 1)
t1 = t0 + 300

wf = rsClient.get_waveforms(starttime=t0,endtime=t0+300,network='GR',station='BFO',location='*',channel='*Z')
```
Gives the following error:

> Traceback (most recent call last):
>   File "testscript1.py", line 10, in <module>
>     wf = rsClient.get_waveforms(starttime=t0,endtime=t0+300,network='GR',station='BFO',location='*',channel='*Z')
>   File "<decorator-gen-55>", line 2, in get_waveforms
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 85, in _assert_filename_not_in_kwargs
>     return f(*args, **kwargs)
>   File "<decorator-gen-54>", line 2, in get_waveforms
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 92, in _assert_attach_response_not_in_kwargs
>     return f(*args, **kwargs)
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 341, in get_waveforms
>     return self.get_waveforms_bulk([bulk], **kwargs)
>   File "<decorator-gen-58>", line 2, in get_waveforms_bulk
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 85, in _assert_filename_not_in_kwargs
>     return f(*args, **kwargs)
>   File "<decorator-gen-57>", line 2, in get_waveforms_bulk
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 92, in _assert_attach_response_not_in_kwargs
>     return f(*args, **kwargs)
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/eidaws_routing_client.py", line 99, in get_waveforms_bulk
>     inv = self.get_stations_bulk(_b, level="channel", **kwargs)
>   File "<decorator-gen-61>", line 2, in get_stations_bulk
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 78, in _assert_format_not_in_kwargs
>     return f(*args, **kwargs)
>   File "<decorator-gen-60>", line 2, in get_stations_bulk
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 85, in _assert_filename_not_in_kwargs
>     return f(*args, **kwargs)
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/eidaws_routing_client.py", line 175, in get_stations_bulk
>     r = self._download(self._url + "/query", data=bulk_str,
>   File ".local/lib/python3.9/site-packages/obspy/clients/base.py", line 249, in _download
>     self._handle_requests_http_error(r)
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/routing/routing_client.py", line 310, in _handle_requests_http_error
>     raise_on_error(r.status_code, buf)
>   File ".local/lib/python3.9/site-packages/obspy/clients/fdsn/client.py", line 1813, in raise_on_error
>     raise FDSNNoDataException("No data available for request.",
> obspy.clients.fdsn.header.FDSNNoDataException: No data available for request.
> HTTP Status code: 204
> Detailed response of server:
> 
> No Content --

However, this specific request (GR.BFO, Z-comp, 2023-9-1 00:00-00:05) currently works with the BGR client, so I would suspect there is some problem with the routing client.

**Comment by javiquinte** [comment]
Hi @doukutsu !
I've just tried it and it seems to work. I copy/pasted the code and got samples from the three available streams (BH, HH, LH).
We did have problems with the Routing Service since yesterday, so this could have been related to that.
For the time being, I'll close this, but feel free to reopen it if you see that it does not work for you.
