### ISSUE TITLE
[StationWS] INGV returns wrong mime-type

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#161]
INGV StationWS is returning a wrong mime-type with the metadata.
Specification (page 4) says that it should be "application/xml"

https://www.fdsn.org/webservices/fdsnws-station-1.1.pdf

Instead of that the user receives a "text/xml".

This breaks software implementation downstream (e.g. fdsnwsscripts)

https://github.com/GEOFON/fdsnws_scripts/issues/10

```
wget "https://webservices.ingv.it/fdsnws/station/1/query?net=MN"
--2024-03-08 10:37:09--  https://webservices.ingv.it/fdsnws/station/1/query?net=MN
Resolving webservices.ingv.it (webservices.ingv.it)... 93.63.207.206
Connecting to webservices.ingv.it (webservices.ingv.it)|93.63.207.206|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/xml]
```

**Comment by ilpint** [comment]
Thank you, just fixed in codebase. 
Fix will be deployed next monday.

**Comment by ilpint** [comment]
Fixed in production service.
