### ISSUE TITLE
Station CPIS xml [Metadata]

### ISSUE THREAD

**Issue by StefaniaDanesi** [EIDA/userfeedback#165]
Please provide the following information in the content of the issue:
* Type of client used (Obspy, fdsnws_fetch, arclink_fetch)
sac, obspy
* Stations and time windows requested (try to keep it to a minimum)
station.xml downloaded from EIDA INGV
CPIS.IV 
* screenshot or copy/paste of the error
java -jar ~/Software/stationxml-seed-converter-stationxml-seed-converter-2.1.0/stationxml-validator-1.7.4.jar --input fdsn_station.xml
403,Error,IV,CPIS,HHN,,2023-11-23T00:00:00,,Stage [03] input unit V must equal stage [02] output unit count
403,Error,IV,CPIS,HHZ,,2023-11-23T00:00:00,,Stage [03] input unit V must equal stage [02] output unit count
403,Error,IV,CPIS,HHE,,2023-11-23T00:00:00,,Stage [03] input unit V must equal stage [02] output unit count
421,Error,IV,CPIS,HHN,,2010-01-29T00:00:00,2022-12-31T23:59:00,Chan:Samplerate 100.0 != [stage 02] Decimation:Frequency/Decimation:Factor 0.0
421,Error,IV,CPIS,HHE,,2010-01-29T00:00:00,2022-12-31T23:59:00,Chan:Samplerate 100.0 != [stage 02] Decimation:Frequency/Decimation:Factor 0.0
421,Error,IV,CPIS,HHZ,,2010-01-29T00:00:00,2022-12-31T23:59:00,Chan:Samplerate 100.0 != [stage 02] Decimation:Frequency/Decimation:Factor 0.0

* when was this exactly done?
Thu May 23 11:32:36 CEST 2024
* What is exactly wrong with the metadata?
Using response from user-specified file: (RESP.IV.CPIS..HHZ).
 Extracting evresp response for CPIS, HHZ...
Thu May 23 11:37:25 2024 [ERROR] IV.CPIS..HHZ: units mismatch between stages
 No transfer function applied! 
 ERROR 2118: No transfer function applied.

**Comment by luvec** [comment]
Moreover, the Guralp Poles&Zeros are in Hertz in IV.CPIS metadata but the PzTransferFunctionType attribute is set to radians/second:
`<PzTransferFunctionType>LAPLACE (RADIANS/SECOND)</PzTransferFunctionType>`

**Comment by massimo1962** [comment]
Hi all, sorry for late reply; now this station-xml should be correct. many thanks for your help.

**Comment by StefaniaDanesi** [comment]
Hi, thank you for your answer. Unfortunately, I still find the same error messages on the new XML file:

211,Error,IV,CPIS,,,2010-01-29T00:00:00,,Chan: HHE Loc:  2023-11-23T00:00:00 null epoch overlaps with HHE  2023-11-23T00:00:00 2023-11-23T00:00:00
310,Error,IV,CPIS,HHE,,2023-11-23T00:00:00,2023-11-23T00:00:00,EndDate 2023-11-23T00:00Z[UTC] must be greater than Start Time 2023-11-23T00:00Z[UTC]
310,Error,IV,CPIS,HHZ,,2023-11-23T00:00:00,2023-11-23T00:00:00,EndDate 2023-11-23T00:00Z[UTC] must be greater than Start Time 2023-11-23T00:00Z[UTC]
310,Error,IV,CPIS,HHN,,2023-11-23T00:00:00,2023-11-23T00:00:00,EndDate 2023-11-23T00:00Z[UTC] must be greater than Start Time 2023-11-23T00:00Z[UTC]
403,Error,IV,CPIS,HHE,,2023-11-23T00:00:00,2023-11-23T00:00:00,Stage [03] input unit V must equal stage [02] output unit count
403,Error,IV,CPIS,HHN,,2023-11-23T00:00:00,2023-11-23T00:00:00,Stage [03] input unit V must equal stage [02] output unit count
403,Error,IV,CPIS,HHZ,,2023-11-23T00:00:00,2023-11-23T00:00:00,Stage [03] input unit V must equal stage [02] output unit count
421,Error,IV,CPIS,HHN,,2010-01-29T00:00:00,2022-12-31T23:59:00,Chan:Samplerate 100.0 != [stage 02] Decimation:Frequency/Decimation:Factor 0.0
421,Error,IV,CPIS,HHZ,,2010-01-29T00:00:00,2022-12-31T23:59:00,Chan:Samplerate 100.0 != [stage 02] Decimation:Frequency/Decimation:Factor 0.0
421,Error,IV,CPIS,HHE,,2010-01-29T00:00:00,2022-12-31T23:59:00,Chan:Samplerate 100.0 != [stage 02] Decimation:Frequency/Decimation:Factor 0.0

**Comment by massimo1962** [comment]
Hi all, could you please try again now? many thanks in advance

**Comment by StefaniaDanesi** [comment]
Thank you, now it seems to be ok

**Comment by petrrr** [comment]
So I close this one!

/close
