### ISSUE TITLE
[Service] Station-WS at INGV failing with fdsnws_fetch

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#17]
INGV Station-WS seems not to be working for Alparray metadata with fdsnws_fetch and also not with Obspy. Examples below:

Fdsnws_fetch:

`fdsnws_fetch -vvvv -N Z3 -C "HHZ" -s "2016-03-01" -e "2016-03-01T00:02:00" -y station -o data.xml`

`HTTP Error 400: Bad Request
getting data from http://webservices.ingv.it/fdsnws/station/1/query failed with HTTP status code 400:`

Obspy:

`rsClient = RoutingClient("eida-routing", debug=True)`

`st = rsClient.get_stations(network="Z3", channel="HHZ", starttime=UTCDateTime(2016, 3, 1), endtime=UTCDateTime(2016, 3, 1, 0, 2, 0))`

`HTTP error 400, reason Bad Request, while downloading 'http://webservices.ingv.it/fdsnws/station/1/query'`

However, a request from a browser seems to be OK.

`http://webservices.ingv.it/fdsnws/station/1/query?net=Z3&start=2016-03-01&end=2016-03-01T00:02:00&cha=HHZ`

**Comment by massimo1962** [comment]
Hi, after some investigations, we have found that the problem is not related to the alparray but is a our station-ws bug. Actually the ws is able to take the parameters via get (browser is ok, indeed) but have some issues on post; I think that this issue (#17) is due to ths bug. in these days we try hard to solve this issue.

**Comment by petrrr** [comment]
Is this related to obspy/obspy#2364?

**Comment by massimo1962** [comment]
we are working on it, we'll update soon.

**Comment by massimo1962** [comment]
Hi, now the service it should be ok (here at INGV seems all ok), but before close this issue it would be great if someone outside INGV do some tests. Many thanks in advance.

**Comment by javiquinte** [comment]
I tested with Obspy and fdsnws_fetch and it seems to be working with both.
I haven't check the validity of the data received, but at least there are no errors and the inventory is received.

**Comment by javiquinte** [comment]
Thanks @massimo1962 !
