### ISSUE TITLE
[EIDA token] AdriaArray, problem to download ONLY from network Y8 

### ISSUE THREAD

**Issue by dbinGFZ** [EIDA/userfeedback#174]
I have a **valid token** for AdriaArray; using the token, I was able to download data from all AdriaArray temporary networks (see map below, red triangles are stations from which I got data) except from **Y8** (NIEP); request performed on September 13 and 14, 2024; I tried different tools (obspy, stream2segment,fdsnws_fetch, see figures below), considering different stations and time frames in 2023. Is there a specific procedure for Y8? 
Thanks, Dino

BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2024-10-11T11:03:36.152205Z", "cn": "Dino Bindi", "memberof": "/epos/Y0HBP;/;/epos", "sn": "Bindi", "issued": "2024-09-11T11:03:36.152209Z", "mail": "dino.bindi@gfz-potsdam.de", "givenName": "Dino", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----

![image](https://github.com/user-attachments/assets/6924fbcf-b9b5-40c2-98a5-16ac5251768f)

![scshot_overviewAAtmp](https://github.com/user-attachments/assets/9db36883-76e2-46c0-a1bf-1c1d3d3afbb7)

 ![scshot_s2s_2023](https://github.com/user-attachments/assets/068a32ca-fee6-4f1b-a151-8cc97cf3bf51)
![scshot_fdsnwsFetch](https://github.com/user-attachments/assets/c1507998-8b1f-41d6-bb8e-d0d4cb4103be)

**Comment by jschaeff** [comment]
Hello @dbinGFZ , as far as I know, tokens are mapped to single network codes.
Alparray corresponds to Z32015. 

If the restriction policy for Y8 is the same as the one from Z3, then NIEP can setup the same authorisation pattern. But they have to check this with the PI of Y8.

EIDA does not provide a global rights management system (yet), each node has it's own policies and procedures, but this is a good  place to ask for data access if someone does not know where the data is hosted (or if the data is hosted at several data centers).

I'm flagging this issue to NIEP.

**Comment by dbinGFZ** [comment]
Hi Jonathan, thank you for your reply and for adding the NIEP tag. Just a small clarification, I am speaking about Adria Array (not AlpArray) and the token that I used  is valid as proved by the fact that I was able to download from other temporary networks contributing to the Adria Array virtual network. Thanks again, Dino

**Comment by javiquinte** [comment]
> Hi Jonathan, thank you for your reply and for adding the NIEP tag. Just a small clarification, I am speaking about Adria Array (not AlpArray) and the token that I used is valid as proved by the fact that I was able to download from other temporary networks contributing to the Adria Array virtual network. Thanks again, Dino

Hi @dbinGFZ ! Don't worry about the misunderstanding between Alp and Adria array ;-)
NIEP is already taking a look at this and will get back to us as soon as this is clarified.
Thanks for the patience!

**Comment by cristianneagoe** [comment]
Hi @dbinGFZ, I made the modifications in my access files to accept the group and not individual email. It should work now.
 Can you please check now?

**Comment by dbinGFZ** [comment]
Hi @cristianneagoe , thanks for the quick reaction. I tried using fdsnws_fetch but still the request is Forbidden (Error 403). I run also a request for XP using the same token and it worked (screenshot).
the command is: 
fdsnws_fetch -s 2024-01-16T14:00:00Z -e 2024-01-16T15:00:00Z -N Y8 -S RO13A -o data.mseed
Thanks, Dino

![image](https://github.com/user-attachments/assets/da75a01a-2bb3-45b7-8919-6553c29a78e4)

**Comment by javiquinte** [comment]
Hi @dbinGFZ 
There is something I cannot understand. From my side this is now working well.

```
$ fdsnws_fetch -s 2024-01-16T14:00:00Z -e 2024-01-16T15:00:00Z -N Y8 -S RO13A -o data.mseed

You received seismic waveform data from the following network(s):
Y8_2022 Adria Array Network

Acknowledgment is extremely important for network operators
providing open data. When preparing publications, please
cite the data appropriately. The FDSN service at

    http://www.fdsn.org/networks/citation/?networks=Y8_2022

provides a helpful guide based on available network
Digital Object Identifiers.

javier@sec24c79:~/Downloads$ ls -l data.mseed 
-rw-rw-r-- 1 javier javier 2584064 Sep 16 12:09 data.mseed
```

My token looks also similar as yours:

```
$ cat ~/.eidatoken 
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2024-10-02T14:26:26.691809Z", "cn": "Javier Quinteros", "memberof": "/epos/JZKWQ;/epos/Y0HBP;/epos/L68ZH;/epos/alparray;/B2DROP-user;/;/epos", "sn": "Quinteros", "issued": "2024-09-02T14:26:26.691813Z", "mail": "javier@gfz-potsdam.de", "givenName": "Javier", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1
[...]
```
 Can you run again the request but with `-vvv` to debug it?

```
$ fdsnws_fetch -vvv -s 2024-01-16T14:00:00Z -e 2024-01-16T15:00:00Z -N Y8 -S RO13A -o data.mseed
```

**Comment by dbinGFZ** [comment]
Hi @javiquinte @cristianneagoe , yes now works!!! thanks to everybody for the support!!
following a suggestion of Ludek, I tried with obspy client and in works:
![image](https://github.com/user-attachments/assets/1a1b722f-6a12-4c44-9561-60a8ad733115)
it works also with other tools:
![image](https://github.com/user-attachments/assets/793fc19f-27fb-4850-a8b0-afd8657a55da)

![image](https://github.com/user-attachments/assets/3be0d8ed-f2fd-4fc2-bf5c-f6b10be90a32)

**Comment by javiquinte** [comment]
Hi @dbinGFZ 
Happy to hear that it is now working. Just one comment, it would be better if you save your token under:

```/home/bindi/.eidatoken```

Pay attention to the dot at the beginning of the filename!
That is the default location for `fdsnws_fetch` to search it and automatically use it.

Good luck with the data!

**Comment by cristianneagoe** [comment]
Hi @dbinGFZ. 
Perfect, I am glad that everything is ok now.
Hi @javiquinte, thank you for the help and for the testing.
