### ISSUE TITLE
[Metadata] ICGC part station metadata from list #166

### ISSUE THREAD

**Issue by JoseAntonioJara** [EIDA/userfeedback#177]
This is the ICGC part from issue https://github.com/EIDA/userfeedback/issues/166 .

Deconvolution gives zero multiplication/division for the 2015-2018 epoch
http://ws.icgc.cat/fdsnws/station/1/query?net=CA&station=CGAR&channel=???&level=response

**Comment by JoseAntonioJara** [comment]
Neither the CA.CGAR station nor the mentioned error appear at the summary tables.
Metadata and response have been both reviewed, and checked using the IRIS validator.

**Comment by luvec** [comment]
There will probably be a problem with complex conjugated poles in the metadata, at first glance, I can see e.g. in epoch 
```
<Channel code="HHZ" startDate="2015-12-02T12:00:00" endDate="2018-07-18T10:00:00" restrictedStatus="open" locationCode="">
...
<Field number="2">
<Real>-339.292</Real>
<Imaginary>115.611</Imaginary>
</Field>
<Field number="3">
<Real>-339.292</Real>
<Imaginary>115.611</Imaginary>
</Field>
```

**Comment by PetrColinSky** [comment]
@JoseAntonioJara: thank you for checking this. Yes, CA.CGAR is not in the summary tables, as they only list the stations inside the AdriaArray region, which CA.CGAR is not. I listed the issues here, some of them in addition to what we did for the AdriaArray region, see the explanation in the #166 : "I am listing some stations with metadata issues, which are partly already included in the summary table, partly are found in addition."

**Comment by JoseAntonioJara** [comment]
Thanks @luvec and @PetrColinSky for your comments. 
Finally I found and corrected the problem. Besides conjugates issues pointed out by @luvec there was a phantom stage at the HHN channel response.
Now the response should be correct.
