### ISSUE TITLE
Download of Greek Stations Severely Limited in Volume

### ISSUE THREAD

**Issue by tesch** [EIDA/userfeedback#19]
*Client*: ObsPy 1.1.1 FDSN Client, Python 3.7.3
*Network*: HL
*Auth*: none
*Date*: 2019-06-17

When downloading waveform data directly from `http://eida.gein.noa.gr`, requests underlie a hard limit of 30M samples. If this limit is exceeded the requestes will be denied, and no data is downloaded. I find this quite restrictive, and cumbersome to work around, especially considering that no other service in Europe behaves in this way. I think a rate limiting of the download itself would be a more appropriate means to manage resources. Having a valid request be denied, can easily lead to bugs, and false assumptions of no data being available at all!

```
from obspy import UTCDateTime
from obspy.clients.fdsn import Client

client = Client('http://eida.gein.noa.gr')

start_time = UTCDateTime('2018-01-28 16:03:10') - 5 * 60
end_time = start_time + 3 * 60 * 60

stream = client.get_waveforms(
    network='HL',
    channel='HHZ',

    station='*',
    location='*',

    starttime=start_time,
    endtime=end_time)
```

The above script will fail, resulting in the following error:

```
obspy.clients.fdsn.header.FDSNException: Request would result in too much data. Denied by the datacenter. Split the request in smaller parts
Detailed response of server:

Error 413: Request Entity Too Large
maximum number of 30.0M samples exceeded
```

**Comment by javiquinte** [comment]
Hi @nikosT !
Could you please take a look at this? You could compare the value with the ones in the online document we had from the ETC. (Hopefully these values are there :roll_eyes: )

**Comment by nikosT** [comment]
Hi,
We have decided to change the value from 30M to 1000M, following a similar policy that is being used by most of the EIDA contributors. Please, let us know if you still experience similar problems.

Thank you,
Nikos

On behalf of the ETC of NOA,
Nikolaos Triantafyllis
