### ISSUE TITLE
FDSNWS error messages not consistent among nodes

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#2]
Hi,
while testing the token system, I realized that the different EIDA nodes do not provide the same error messages for FDSNWS requests to restricted data without a token.

ODC, LMU and INGV node correctly return a _"Access denied"_ message, when not using a token for Z3 data.

ETH and RESIF node simply return a _"No data available"_ message, when not using a token for Z3 data, which is somewhat misleading.

I did not test any other nodes. It's not a big deal, but correct messages will help the users identify the reason why they cannot download any data.

**Comment by javiquinte** [comment]
@sheimers Could you post your SC3 version and details about the python file where this error comes from? (size, date, line where this error can be found)
@jschaeff Can you check if the code you run is capable of returning "Access denied" in case no token (or an invalid one) is presented?

**Comment by Jollyfant** [comment]
This was changed in SeisComP3 by @andres-h here https://github.com/SeisComP3/seiscomp3/commit/e4187beb8b4454a532cfe99fad1113dc54b1a3f2. It should be fixed with the newest version of SC3.

**Comment by flofux** [comment]
I also noted that when I request data which is not available the ObsPy RoutingClient sometimes returns and empty stream and sometimes returns an error message, e.g.: No data available for request.

Ideally this should also be consistent ... I spotted it today on the ODC node, but haven't checked other nodes systematically.

**Comment by Jollyfant** [comment]
Do you think that is an effect of the way ObsPy implements the APIs?

**Comment by sheimers** [comment]
Currently we run Seiscomp3 217.124 on eida.ethz.ch. We plan to upgrade to 2018.327 within a few days. We postponed the update because we had some software depending on the old database scheme, but this is now solved.

The "no data available" seems to come from lib/python/seiscomp/sds.py, line 298. 

```
sysop@eida:/usr/local/lib/python/seiscomp$ ls -la sds.py
-rw-rw-r-- 1 sysop sysop 12741 Oct 12  2016 sds.py

```

But in the new version 2018.327 it is still "no data available". 

```
sysop@sc3d:/usr/local/lib/python/seiscomp$ ls -la  sds.py
-rw-rw-r-- 1 sysop sysop 12654 Mar 29 11:04 sds.py
```

**Comment by sheimers** [comment]
Today we have upgraded eida.ethz.ch to Ubuntu 18.04 and Seiscomp3 2018.327.p10. We have also upgraded the eidaws routing service to the latest git release.

**Comment by javiquinte** [comment]
I tested it and it seems solved at ETH. Thanks @sheimers !
Let's wait for RESIF.

> `HTTP error 403`, reason Forbidden, while downloading 'http://www.orfeus-eu.org/fdsnws/dataselect/1/query': b'Error 403: Forbidden\n\naccess denied
`HTTP error 403`, reason Forbidden, while downloading 'http://erde.geophysik.uni-muenchen.de/fdsnws/dataselect/1/query': b'Error 403: Forbidden\n\naccess denied
`HTTP error 403`, reason Forbidden, while downloading 'http://eida.ethz.ch/fdsnws/dataselect/1/query': b'Error 403: Forbidden\n\naccess denied
`HTTP error 403`, reason Forbidden, while downloading 'http://webservices.ingv.it/fdsnws/dataselect/1/query': b'Error 403: Forbidden\n\naccess denied
Downloaded http://ws.resif.fr/fdsnws/dataselect/1/query with `HTTP code: 204`

**Comment by jschaeff** [comment]
From RESIF's perspective, the error message is logical:
The user requested some data, but we can not serve them, either because we don't host it or because the user is not authorized to get them.
I acknowledge that it would help the user to know which of those 2 reasons led to the error, but it's not easy to implement on our side.
Furthermore, I guess our implementation is FDSN compliant even with this problem (am I right here?)
If it's OK with you, I'll treat this issue with lower priority, and come back to you with some solution.

**Comment by javiquinte** [comment]
> From RESIF's perspective, the error message is logical:
> The user requested some data, but we can not serve them, either because we don't host it or because the user is not authorized to get them.
> I acknowledge that it would help the user to know which of those 2 reasons led to the error, but it's not easy to implement on our side.
> Furthermore, I guess our implementation is FDSN compliant even with this problem (am I right here?)
> If it's OK with you, I'll treat this issue with lower priority, and come back to you with some solution.

I agree, Jonathan. Keep it with very low priority. I will change this to "wontfix" and close it for the time being, but if you find some time in the future it would be nice to have it.
