### ISSUE TITLE
[Metadata] Missing response from station metadata

### ISSUE THREAD

**Issue by okling** [EIDA/userfeedback#21]
Client: ObsPy 1.1.1, EIDA Routing Client, Python 3.7.3
Network: Z3
Auth: none
Date: July 03, 2019

When I was downloading some AlpArray station waveforms and inventories, I found that the instrumental response of a bunch of stations is missing from the metadata.

This is the setup I have:
```
>>>from obspy.clients.fdsn import RoutingClient 
>>>from obspy import UTCDateTime
>>>rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': '/Users/angelling/Downloads/eidatoken'})
>>>starttime = UTCDateTime(2018,8,15,21,56,0)
>>>endtime   = UTCDateTime(2018,8,15,21,59,0)
```

This is the response from a complete station metadata (example A050A):
```
>>>inv = rsClient.get_stations(starttime=starttime, endtime=endtime, station="A050A", network="Z3", loc="*", channel="HHZ", level="response")
>>>print(inv)
Inventory created at 2019-07-03T10:07:12.122698Z
	Created by: ObsPy 1.1.1.post0+733.g3c1c2530ba
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.1.1.post0+733.g3c1c2530ba,SeisComP3 (SED)
	Contains:
		Networks (1):
			Z3
		Stations (1):
			Z3.A050A (Klekovaca, Republika Srpska - Bosnia and Herzegovina)
		Channels (1):
			Z3.A050A..HHZ

>>> new =inv[0].get_response("Z3.A050A..HHZ", datetime=starttime)
>>> print(new)
Channel Response
	From M/S () to COUNTS ()
	Overall Sensitivity: 5.99998e+08 defined at 1.000 Hz
	7 stages:
		Stage 1: PolesZerosResponseStage from M/S to V, gain: 1500
		Stage 2: PolesZerosResponseStage from V to V, gain: 0.399999
		Stage 3: CoefficientsTypeResponseStage from V to COUNTS, gain: 1
		Stage 4: FIRResponseStage from COUNTS to COUNTS, gain: 1e+06
		Stage 5: FIRResponseStage from COUNTS to COUNTS, gain: 1
		Stage 6: FIRResponseStage from COUNTS to COUNTS, gain: 1
		Stage 7: FIRResponseStage from COUNTS to COUNTS, gain: 1

```

This is the response from an incomplete station metadata (example A360A):
```
>>> inv = rsClient.get_stations(starttime=starttime, endtime=endtime, station="A360A", network="Z3", loc="*", channel="HHZ", level="response")
>>> print(inv)
Inventory created at 2019-07-03T10:10:07.430537Z
	Created by: ObsPy 1.1.1.post0+733.g3c1c2530ba
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.1.1.post0+733.g3c1c2530ba,SeisComP3 (GOF)
	Contains:
		Networks (1):
			Z3
		Stations (1):
			Z3.A360A (Altes Rathaus Auernheim)
		Channels (1):
			Z3.A360A.00.HHZ
>>> new =inv[0].get_response("Z3.A360A.00.HHZ", datetime=starttime)
>>> print(new)
Channel Response
	From M/S () to None ()
	Overall Sensitivity: 4.77413e+08 defined at 1.000 Hz
	0 stages:
```

I did some further investigations (request at a different time, different stations) and made a list of stations with missing response:

- A015A
- A022A, A023A, A025A, A026A, A027A, A028B, A029A
- A030A, A031A, A032A, A033A, A034A, A038A
- A100A, A101B, A102A, A103D, A104C, A105A, A107D, A108A, A109A
- A111A, A112A, A113B, A114A, A115A, A116B, A117A, A118B, A119A
- A121B, A122A, A123A, A124A, A125A, A128A
- A140A, A141A, A143A, A144A, A145A, A146A, A147B, A148B
- A260A, A261A, A262A, A263A, A264A, A265A, 266A, A267A
- A350A, A351B, A352A, A353A, A354A, A355A, A356A, A357B, A358A
- A360A, A361A, A362A, A363A, A364A, A365A, A366A, A367A, A368A, A369A

Any ideas on this? Thanks for your help!

**Comment by javiquinte** [comment]
Hi @okling .
Thanks a lot for the detailed feedback! I'm passing this issue to the people at ETH who is in charge of coordinate the metadata for the Z3 network. @sheimers

**Comment by Jollyfant** [comment]
I checked the metadata for A260A and it seems to be complete. Maybe ObsPy has some problem finding the metadata because of the `datetime` parameter?

www.orfeus-eu.org/fdsnws/station/1/query?station=A260A&level=response

**Comment by sheimers** [comment]
Yes, but indeed A360A does not have the complete response:

http://erde.geophysik.uni-muenchen.de/fdsnws/station/1/query?station=A360A&level=response

Which is rather strange. We do have the response in our Sc3 inventory on eida.ethz.ch, but we actually downloaded it from the same server using the following command:

 http://erde.geophysik.uni-muenchen.de/fdsnws/station/1/query?level=response&format=xml&net=Z3

That means the response was there before and has dissappeared.

**Comment by okling** [comment]
@sheimers Right, I downloaded another group of AlpArray waveforms and inventories about 2 weeks ago using the same ObsPy script and the response was there but has somehow disappeared now.

**Comment by jbienkowski** [comment]
I am unsure if it is related, but few weeks ago waveforms and metadata for A26* stations have been divided between ODC and LMU. For that reason the seiscomp and routing configs have been altered on both sides. If needed, I can provide ODC config files for verification per email.

**Comment by jbienkowski** [comment]
Hello @sheimers,
It seems that something goes wrong when SED is pulling the Z3 metadata from ODC (https://www.orfeus-eu.org/documents/Z3.xml) and is not providing it back during nightly sync so we end up with no Z3 metadata on our end.

**Comment by sheimers** [comment]
I have reimported the ODC metadata, does this solve your problem?

**Comment by okling** [comment]
@sheimers Sorry for the late reply. Just had a chance to check, and it looks like the metadata problem is fixed from the my side (user side).
