### ISSUE TITLE
[Metadata] Getting stations inventory

### ISSUE THREAD

**Issue by CoralieAubert** [EIDA/userfeedback#22]
Hello,

It is not really a problem but I wanted to know if it is normal to get the full inventory of  a network when using the obspy get_stations() function.

Here is my code:

from obspy.clients.fdsn import RoutingClient
from obspy import UTCDateTime
starttime=UTCDateTime(2018, 9, 21, 0, 0, 0)
endtime=UTCDateTime(2018, 9, 22, 0, 0, 0)
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': './eidatoken'})
inv = rsClient.get_stations(starttime=starttime, endtime=endtime,network="Z3", sta="A181A", loc="00", channel="HHZ",level="response")

the following inventory is returned:
Inventory created at 2019-07-11T14:09:09.275926Z
	Created by: ObsPy 1.1.1rc1.post0+555.geb0b1c2343.obspy.master
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.1.1rc1.post0+555.geb0b1c2343.obspy.master,RESIF,SeisComP3,SeisNet-mysql (GOF,INGV-CNT,RESIF,SED)
	Contains:
		Networks (4):
			Z3 (4x)
		Stations (165):
			Z3.A015A (Langauhaeuser, Niederoesterreich, Austria)
			Z3.A022A (Hirschenstein, Niederoesterreich, Austria)
			Z3.A023A (Station Baumgartsaur, Oberoesterreich, Austria)
			Z3.A025A (Baerendorf, Steiermark, Austria)
			Z3.A026A (Unterfahrungsstollen, Kaernten, Austria)
.......

I was excepting to get the inventory of the requested station only.
Is that normal?
Regards,
Coralie

**Comment by okling** [comment]
@CoralieAubert use `station="A181A"` in the code instead of `sta="A181A"`.
