### ISSUE TITLE
[Metadata] fdsnws/station/1/application.wadl lists unsupported "matchtimeseries"-parameters at EIDA-nodes BGR, KOERI, LMU, NIEP, NOA

### ISSUE THREAD

**Issue by flixha** [EIDA/userfeedback#24]
Originally, I reported this issue on the [Obspy-github](https://github.com/obspy/obspy/issues/2366), because I encountered it while using the FDSN mass downloader in Obspy. While researching, I found that the issue apparently occurs due to the following  metadata issue:

* Type of client used: Browser and Obspy 
* copy/paste of the error:
`HTTP error 404, reason Not Found, while downloading 'http://eida.gein.noa.gr/fdsnws/event/1/contributors': b'Error 404: Not Found\n\nThe requested resource does not exist on this server.\n\nUsage details are available from /fdsnws/event/1/\n\nRequest:\n/fdsnws/event/1/contributors\n\nRequest Submitted:\n2019-03-27T14:03:34.016879\n\nService Version:\n1.2.0\n'`
* when was this exactly done? 2019-03-27, repeated today 2019-07-19 before adding to this issue tracker
* What is exactly wrong with the metadata?
The EIDA-nodes BGR, KOERI, LMU, NIEP, and NOA report in the [/fdsnws/station/1/application.wadl (link to NOA)](http://eida.gein.noa.gr/fdsnws/station/1/application.wadl) that they support the parameter "matchtimeseries". However, when including the parameter in a request (see below), the web services do not have a proper reply because they apparently do not support this parameter. In the browser, I get no reply 8blank page), while Obspy reported the error printed above (Error 404: Not Found\n\nThe requested resource does not exist on this server). The following two requests demonstrate the issue:
[does not work: fdsn-station request with matchtimeseries=true](http://eida.gein.noa.gr/fdsnws/station/1/query?starttime=2019-01-01T00%3A00%3A00.000000&endtime=2019-02-01T00%3A00%3A00.000000&level=channel&latitude=38.0&longitude=24.0&minradius=0.0&maxradius=1.0&matchtimeseries=true&format=text)
[works correctly: fdsn-station request without matchtimeseries=true](http://eida.gein.noa.gr/fdsnws/station/1/query?starttime=2019-01-01T00%3A00%3A00.000000&endtime=2019-02-01T00%3A00%3A00.000000&level=channel&latitude=38.0&longitude=24.0&minradius=0.0&maxradius=1.0&format=text)

The problem with listing the unsupported parameter "matchtimeseries" is that other tools such as the Obspy FDSN mass downloader try to use the parameter in requests, believing that it is supported. It appears that this issue occurs for EIDA nodes that updated their SeisComP3 to version 1.2.0. At the ODC-KNMI EIDA node, an admin already resolved the issue in response to the issue on the Obspy-github. I think they simply removed in the application.wadl-file the line `<param name="matchtimeseries" style="query" type="xsd:boolean" default="false"/>`.

**Comment by javiquinte** [comment]
Thanks @flixha for your feedback!
We contacted all the persons realted to this issue and we will come back to you as soon as we have more information.

**Comment by megies** [comment]
We removed the `matchtimeseries` parameter from LMU station WS wadl.

**Comment by nikosT** [comment]
> We removed the `matchtimeseries` parameter from LMU station WS wadl.

Could you, please, describe the procedure you followed in order to make it work?
Thanks

**Comment by megies** [comment]
@nikosT strictly speaking this is not about making something work, but rather telling automated routines that `matchtimeseries` is not supported (actually it's rather *not telling that it is supported* ;)

In any case, you can remove the `matchtimeseries` parameter tag in `~/seiscomp3/share/fdsnws/station.wadl` and restart seiscomp. Although, we'll see what comes out of the upstream report I made at SeisComP3/seiscomp3#237

**Comment by flixha** [comment]
Thanks a lot for taking care of this issue, and for reporting it also int he SeisComP3 issue tracker! 
I noticed that one of the above links didn't include a `http://` and hence didn't work on just clicking.
Also, I was a bit confused by my tests earlier and thought that only the `matchtimeseries`-parameter was problematic right now. However, it appears that the adding `includeavailability=true` leads to no response (or an empty response, I don't get an error code) as well.

**Comment by nikosT** [comment]
> @nikosT strictly speaking this is not about making something work, but rather telling automated routines that `matchtimeseries` is not supported (actually it's rather _not telling that it is supported_ ;)
> 
> In any case, you can remove the `matchtimeseries` parameter tag in `~/seiscomp3/share/fdsnws/station.wadl` and restart seiscomp. Although, we'll see what comes out of the upstream report I made at [SeisComP3/seiscomp3#237](https://github.com/SeisComP3/seiscomp3/issues/237)

thanks @megies! Unfortunately,  it doesn't work for us.

**Comment by nikosT** [comment]
> Thanks a lot for taking care of this issue, and for reporting it also int he SeisComP3 issue tracker!
> 
> I noticed that one of the above links didn't include a `http://` and hence didn't work on just clicking - fixed that now.
> 
> Also, I was a bit confused by my tests earlier and thought that only the `matchtimeseries`-parameter was problematic right now. However, it appears that the adding `includeavailability=true` leads to no response (or an empty response, I don't get an error code) as well.

I confirm that too. So, there 2 variables to be removed!

**Comment by nikosT** [comment]
The issue has been resolved in SeisComP v4.
I think the ticket should be closed now.
