### ISSUE TITLE
No Z3 Data received with fdsn RoutingClient and eas token

### ISSUE THREAD

**Issue by apaul-uga** [EIDA/userfeedback#26]
I have been trying to download Z3 data with the new fdsn RoutingClient and eas token for some time (first try end of July), then again yesterday (Sep. 2) and today, and never succeeded. I checked that the Python3.7 command lines that I am using do work to download data of permanent stations.
The tests were made on a number of Z3 stations from different datacenters, for which I could get data using other clients (arclink with python2.7, or fdsn client with personal user/passwd in RESIF-DC). With debug=True (see one example below), I get different error messages from different datacenters, but no data.
I also tested the set of python lines given as examples (for Z3 data) in the readme file of this github, but it does not work either.

Python command lines (and output):
$ python
Python 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from obspy.core import UTCDateTime
>>> import obspy.clients.fdsn
>>> from obspy.clients.fdsn import RoutingClient
>>> tstart=UTCDateTime(2019, 1, 8, 12, 39, 31)
>>> tend=tstart+600
>>> rsClient = RoutingClient("eida-routing", debug=False, credentials={'EIDA_TOKEN': '/home/paulan/eidatoken'})
>>> st_eas = rsClient.get_waveforms(network="Z3", station="A282A", channel="*", starttime=tstart, endtime=tend)
>>> print(st_eas)
0 Trace(s) in Stream:

>>>

With debug=True:

>>> st_eas = rsClient.get_waveforms(network="Z3", station="A282A", channel="*", starttime=tstart, endtime=tend)
Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:
----------------------------------------------------------------------
service=station
format=post
alternative=false
Z3 A282A * * 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
----------------------------------------------------------------------
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f8d191b7e80>]
Base URL: http://eida.ethz.ch
Request Headers: {'User-Agent': 'ObsPy/1.1.0 (Linux-4.19.0-5-amd64-x86_64-with-debian-10.0, Python 3.7.3)'}
Loading discovered services from cache.
Downloading https://eida.ethz.ch/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2019-09-29T12:28:34.827474Z", "cn": "Anne PAUL", "memberof": "/epos/alparray;/epos;/", "sn": "PAUL", "issued": "2019-08-30T12:28:34.827478Z", "mail": "anne.paul@univ-grenoble-alpes.fr", "givenName": "Anne", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

...
-----END PGP SIGNATURE-----

----------------------------------------------------------------------
Downloaded https://eida.ethz.ch/fdsnws/dataselect/1/auth with HTTP code: 200
Got temporary user/pw: t6SaYDQ3AAGlXIeyBBd5oDa8/fXZoceDUX0WSBdld
Installed new opener with handlers: [<urllib.request.HTTPDigestAuthHandler object at 0x7f8d191dbc18>, <obspy.clients.fdsn.client.NoRedirectionHandler object at 0x7f8d191dbd30>]
Downloading http://eida.ethz.ch/fdsnws/station/1/query with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
format=text
level=channel
Z3 A282A * * 2019-01-08T12:39:31 2019-01-08T12:49:31
----------------------------------------------------------------------
Uncompressing gzipped response for http://eida.ethz.ch/fdsnws/station/1/query
Downloaded http://eida.ethz.ch/fdsnws/station/1/query with HTTP code: 200
Downloading http://www.orfeus-eu.org/eidaws/routing/1/query ...
Sending along the following payload:
----------------------------------------------------------------------
service=dataselect
format=post
Z3 A282A -- BHE 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- BHN 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- BHZ 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- HHE 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- HHN 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- HHZ 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- LHE 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- LHN 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
Z3 A282A -- LHZ 2019-01-08T12:39:31.000000 2019-01-08T12:49:31.000000
----------------------------------------------------------------------
Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler object at 0x7f8d191c8198>]
Base URL: http://eida.ethz.ch
Request Headers: {'User-Agent': 'ObsPy/1.1.0 (Linux-4.19.0-5-amd64-x86_64-with-debian-10.0, Python 3.7.3)'}
Loading discovered services from cache.
Downloading https://eida.ethz.ch/fdsnws/dataselect/1/auth with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2019-09-29T12:28:34.827474Z", "cn": "Anne PAUL", "memberof": "/epos/alparray;/epos;/", "sn": "PAUL", "issued": "2019-08-30T12:28:34.827478Z", "mail": "anne.paul@univ-grenoble-alpes.fr", "givenName": "Anne", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

...
-----END PGP SIGNATURE-----

----------------------------------------------------------------------
Downloaded https://eida.ethz.ch/fdsnws/dataselect/1/auth with HTTP code: 200
Got temporary user/pw: t6SaYDQ3AAGlXIeyBBd5oDa8/fXZoceDUX0WSBdld
Installed new opener with handlers: [<urllib.request.HTTPDigestAuthHandler object at 0x7f8d191c8d68>, <obspy.clients.fdsn.client.NoRedirectionHandler object at 0x7f8d191c89e8>]
Downloading http://eida.ethz.ch/fdsnws/dataselect/1/query with requesting gzip compression
Sending along the following payload:
----------------------------------------------------------------------
Z3 A282A -- BHE 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- BHN 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- BHZ 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- HHE 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- HHN 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- HHZ 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- LHE 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- LHN 2019-01-08T12:39:31 2019-01-08T12:49:31
Z3 A282A -- LHZ 2019-01-08T12:39:31 2019-01-08T12:49:31
----------------------------------------------------------------------
HTTP error 403, reason Forbidden, while downloading 'http://eida.ethz.ch/fdsnws/dataselect/1/query': b'Error 403: Forbidden\n\naccess denied\n\nUsage details are available from /fdsnws/dataselect/1/\n\nRequest:\n/fdsnws/dataselect/1/query\n\nRequest Submitted:\n2019-09-03T14:34:34.14592\n\nService Version:\n1.2.0\n'
>>> print(st_eas)
0 Trace(s) in Stream:

>>> 

Thanks for your help.

**Comment by javiquinte** [comment]
Hi @apaul-uga !
I tried the same command and got the expected data. There are only two differences I can see:
* you are running an older Obspy version,
* we (obviously) have a different token.

I will send via mail my personal one-day token, so that you can test if your token is the problem.
If that's not the problem, then you should try to upgrade Obspy.
Let us know the outcome of these tests.

**Comment by apaul-uga** [comment]
Hi javiquinte,
The token you sent me did not make a better job, BUT the update of Obspy 1.1.0 --> 1.1.1 did. I now have my data. Thanks for your help!
