### ISSUE TITLE
[WFCatalog] missing entries for several stations/nodes

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#28]
Hello everyone,

recently I was trying to get availability information for all stations on EIDA using the WFCatalog features. While trying so I found several stations that do not have a valid WFCatalog entry. It's not a very big deal, but anyways I thought I'd report it here.

I attach the files that list all stations for channels BHZ and HHZ and the years 2015 - 2018.

Here's an overview of how many stations are affected on each node in each year/channel:

Node - Year - Channel - # Stations
---------------------------------------------
RESIF - 2015 - BHZ - 3
RESIF - 2016 - BHZ - 7
RESIF - 2016 - HHZ - 26
RESIF - 2017 - BHZ - 15
RESIF - 2017 - HHZ - 30
RESIF - 2018 - BHZ - 29
RESIF - 2018 - HHZ - 53

INGV - 2015 - BHZ - 13
INGV - 2015 - HHZ - 74
INGV - 2016 - HHZ - 39
INGV - 2017 - HHZ - 18
INGV - 2018 - BHZ - 41
INGV - 2018 - HHZ - 12

ODC - 2015 - HHZ - 1
ODC - 2016 - BHZ - 2
ODC - 2016 - HHZ - 1
ODC - 2017 - BHZ - 2
ODC - 2017 - HHZ - 1
ODC - 2018 - HHZ - 2

LMU - 2018 - HHZ - 3

GFZ - 2015 - HHZ - 2
GFZ - 2016 - BHZ - 6
GFZ - 2016 - HHZ - 6
GFZ - 2017 - BHZ - 2
GFZ - 2017 - HHZ - 2
GFZ - 2018 - BHZ - 3
GFZ - 2018 - HHZ - 3

BGR - 2016 - HHZ - 1
BGR - 2016 - BHZ - 1
BGR - 2017 - BHZ - 1
BGR - 2017 - HHZ - 1

NIEP - 2015 - BHZ - 21
NIEP - 2015 - HHZ - 31
NIEP - 2016 - BHZ - 21
NIEP - 2016 - HHZ - 30
NIEP - 2017 - BHZ - 21
NIEP - 2017 - HHZ - 34
NIEP - 2018 - BHZ - 24
NIEP - 2018 - HHZ - 35

[missing_wfc_entries_2015_BHZ.txt](https://github.com/EIDA/userfeedback/files/3657940/missing_wfc_entries_2015_BHZ.txt)
[missing_wfc_entries_2015_HHZ.txt](https://github.com/EIDA/userfeedback/files/3657941/missing_wfc_entries_2015_HHZ.txt)
[missing_wfc_entries_2016_BHZ.txt](https://github.com/EIDA/userfeedback/files/3657942/missing_wfc_entries_2016_BHZ.txt)
[missing_wfc_entries_2016_HHZ.txt](https://github.com/EIDA/userfeedback/files/3657943/missing_wfc_entries_2016_HHZ.txt)
[missing_wfc_entries_2017_BHZ.txt](https://github.com/EIDA/userfeedback/files/3657944/missing_wfc_entries_2017_BHZ.txt)
[missing_wfc_entries_2017_HHZ.txt](https://github.com/EIDA/userfeedback/files/3657945/missing_wfc_entries_2017_HHZ.txt)
[missing_wfc_entries_2018_BHZ.txt](https://github.com/EIDA/userfeedback/files/3657946/missing_wfc_entries_2018_BHZ.txt)
[missing_wfc_entries_2018_HHZ.txt](https://github.com/EIDA/userfeedback/files/3657947/missing_wfc_entries_2018_HHZ.txt)

**Comment by jschaeff** [comment]
As for RESIF, the reason why wfcatalog does not report any data for those station/channels is because of the quality (D : raw data).

I invite you to use the availability webservice to see the difference:

https://ws.resif.fr/fdsnws/availability/1/extent?network=WI&station=BIM&channel=HHE&starttime=2015-01-01&endtime=2015-12-01

```
#Network Station Location Channel Quality SampleRate           Earliest                     Latest                     Updated           TimeSpans Restriction
      WI     BIM       00     HHE       Q      100.0 2015-01-01T00:00:00.370000Z 2015-12-01T23:59:00.000000Z 2017-12-12T11:34:26.082161Z       969        OPEN
```

https://ws.resif.fr/fdsnws/availability/1/extent?network=WI&station=BIM&channel=BHZ&starttime=2015-01-01&endtime=2015-12-01
```
#Network Station Location Channel Quality SampleRate           Earliest                     Latest                     Updated           TimeSpans Restriction
      WI     BIM       00     BHZ       D       20.0 2015-01-01T00:00:00.000000Z 2015-12-01T23:59:00.000000Z 2019-01-29T14:52:51.974520Z      1757        OPEN
```
```

**Comment by flofux** [comment]
Aha, I didn't even know such thing as availability webservice exists. Would make some people life much easier! Is it only at RESIF or at other nodes, too?

And I admit I'm not familiar with the quality flags. What do Q/D actually indicate?

**Comment by jschaeff** [comment]
availability has been validated by the FDSN this summer, and is being implemented in EIDA nodes. As for now, RESIF is the only DC providing this webservice, but we lack some media to advertize it to the users.

The quality codes are described in the SEED manual, somewhere. I'm not an expert, but you should find your answers there : https://www.fdsn.org/seed_manual/SEEDManual_V2.4.pdf

cheers

**Comment by flofux** [comment]
D — The state of quality control of the data is indeterminate.
R — Raw Waveform Data with no Quality Control
Q — Quality Controlled Data, some processes have been applied to the data.
M — Data center modified, time-series values have not been changed.

**Comment by jbienkowski** [comment]
Hi all,
On the ODC side it happened because owners of the Dutch stations re-organized them a bit, so for example J01 and J02 have been moved from network EC to NL and WFCatalog has not been triggered for their old data.
Anyway, the metrics for stations mentioned by @flofux have just been recalculated, so from our perspective that should be it.

**Comment by jschaeff** [comment]
Old issue. Cleaning and closing
