### ISSUE TITLE
[Service] Webservices down at INGV node

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#30]
INGV webservices are currently not available.

```
from obspy.clients.fdsn import Client
client = Client('INGV')
```
FDSNException: No FDSN services could be discovered at 'http://webservices.ingv.it'. This could be due to a temporary service outage or an invalid FDSN service address.

Interestingly, ORFEUS page still thinks it's working ... https://www.orfeus-eu.org/data/eida/webservices/

**Comment by javiquinte** [comment]
I'll contact @massimo1962 to get an update on this. Thanks for reporting @flofux !

**Comment by massimo1962** [comment]
Hi guys, I take this issue and will inform you asap.

**Comment by massimo1962** [comment]
Dears, I have performed these tests and they works; @flofux : please could you post the exact reply of the services/obspy (if any)? many thanks in advance.

If the request blocks or hits a timeouts please let us know your IP (or better send me a direct e-mail)

INVOKED:
```
curl --data-binary "@payload-IV" -X POST 'http://webservices.ingv.it/fdsnws/station/1/query'

wget "http://webservices.ingv.it/fdsnws/dataselect/1/query?starttime=2017-01-01T00:00:00Z&endtime=2017-01-01T12:00:00Z&network=IV&station=ACER" -O data-noaut.mseed
```

**Comment by flofux** [comment]
Still the same behaviour:

`In [3]: client = Client('INGV', debug=True)`

Installed new opener with handlers: [<obspy.clients.fdsn.client.CustomRedirectHandler instance at 0x7f4aeb13bdd0>]
Base URL: http://webservices.ingv.it
Request Headers: {u'User-Agent': u'ObsPy/1.1.1 (Linux-4.4.0-21-generic-x86_64-with-debian-stretch-sid, Python 2.7.12)'}
Downloading http://webservices.ingv.it/fdsnws/dataselect/1/application.wadl with requesting gzip compression
Downloading http://webservices.ingv.it/fdsnws/event/1/application.wadl with requesting gzip compression
Downloading http://webservices.ingv.it/fdsnws/station/1/application.wadl with requesting gzip compression
Downloading http://webservices.ingv.it/fdsnws/event/1/catalogs with requesting gzip compression
Downloading http://webservices.ingv.it/fdsnws/event/1/contributors with requesting gzip compression
Error while downloading: http://webservices.ingv.it/fdsnws/dataselect/1/application.wadl
Error while downloading: http://webservices.ingv.it/fdsnws/event/1/application.wadl
Error while downloading: http://webservices.ingv.it/fdsnws/station/1/application.wadl
Error while downloading: http://webservices.ingv.it/fdsnws/event/1/catalogs
Error while downloading: http://webservices.ingv.it/fdsnws/event/1/contributors

FDSNException                             Traceback (most recent call last)
<ipython-input-3-0f6c5d167600> in <module>()
----> 1 client = Client('INGV', debug=True)

/home/fuchs/anaconda2/lib/python2.7/site-packages/obspy/clients/fdsn/client.pyc in __init__(self, base_url, major_versions, user, password, user_agent, debug, timeout, service_mappings, force_redirect, eida_token)
    254             print("Request Headers: %s" % str(self.request_headers))
    255 
--> 256         self._discover_services()
    257 
    258         # Use EIDA token if provided - this requires setting new url openers.

/home/fuchs/anaconda2/lib/python2.7/site-packages/obspy/clients/fdsn/client.pyc in _discover_services(self)
   1531                    "be due to a temporary service outage or an invalid FDSN "
   1532                    "service address." % self.base_url)
-> 1533             raise FDSNException(msg)
   1534 
   1535         # Cache.

FDSNException: No FDSN services could be discovered at 'http://webservices.ingv.it'. This could be due to a temporary service outage or an invalid FDSN service address.

**Comment by flofux** [comment]
I realized it's only on my computer, so likely I am blocked. I'll send you an E-Mail
