### ISSUE TITLE
[Service][WFCatalog] currently not available at GFZ and NIEP node?

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#31]
Hello again,

it seems the WFCatalog is currently not available at GFZ and NIEP node? When I try to access it, I get the following message:

Error 500: Internal Server Error
The connection to the database could not be established

Edit: I see that NIEP has the GFZ server listed as WFCatalog address - is that intended?
https://www.orfeus-eu.org/data/eida/webservices/

**Comment by javiquinte** [comment]
I'm contacting Cristian (NIEP) via email.

**Comment by Jollyfant** [comment]
> Edit: I see that NIEP has the GFZ server listed as WFCatalog address - is that intended?

Nope @jbienkowski

**Comment by cristianneagoe** [comment]
Hi, I just checked WFcatalog and is running without any problems. Maybe it was a temporary error.
I checked with a request and is working. 
Can you please tell me the exact request and to try to duplicate the problem?

Thank you and sorry for the inconvenience

**Comment by flofux** [comment]
Hi, yes - everything seems operating again. Thank you very much!

**Comment by jbienkowski** [comment]
Just updated the WFCatalog address for NIEP (http://eida-sc3.infp.ro/eidaws/wfcatalog/alpha).
This is what I found on the NIEP page, let me know in case it is not the right one.
https://www.orfeus-eu.org/data/eida/webservices/

**Comment by cristianneagoe** [comment]
Hi, yes is the right address.
