### ISSUE TITLE
Missing DOIs for CR, HS, PL, SI

### ISSUE THREAD

**Issue by tesch** [EIDA/userfeedback#33]
I'm not sure this is the right place to put this, but while compiling a list of citations for all participating AlpArray networks, I noticed that some of them - specifically the ones listed in the title - have no registered DOIs.

How is one expected to cite the usage of such networks, and / or can these DOIs be amended?

**Comment by javiquinte** [comment]
Indeed, this is a very good point @tesch !
I'm forwarding this to the one sin charge of the Administration of the project.
I'll come back to you as soon as I have news.

**Comment by petrrr** [comment]
INGV per rete `SI`.

**Comment by javiquinte** [comment]
Hi @tesch . A suggestion I recevied from the EIDA Management Board was the following:
if the network does not have a DOI, please just give the network code and full network name (perhaps dig out some information to see if there is a reference hanging around somewhere).
In the meantime we are working to mint the missing DOIs (e.g. INGV with SI as @petrrr mentioned) and will come back to you in case there is any change.
And again, thanks for the feedback!
