### ISSUE TITLE
2 types of token for the same user

### ISSUE THREAD

**Issue by apaul-uga** [EIDA/userfeedback#34]
I have 2 different institutional logins (eduGAIN) that I use more or less randomly, for example to connect to the eas system to get an Eida token. Unfortunately, only one of these institutional logins allows me to get a correct token, with access right to AlpArray data. Although I am registered with a single email address (but starting with or without capital letters), it seems that I have 2 different user names ("cn") in eas, one in capital letters (Anne PAUL) that gives me access to AA data, and one in small letters (Anne Paul) that does not (see below). 
Can you please help? Regards. Anne

Right token:
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2019-10-30T08:58:36.669680Z", "cn": "Anne PAUL", "memberof": "/epos/alparray;/epos;/", "sn": "PAUL", "issued": "2019-09-30T08:58:36.669687Z", "mail": "anne.paul@univ-grenoble-alpes.fr", "givenName": "Anne", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

-----END PGP SIGNATURE-----

"Wrong" token:
BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1

{"valid_until": "2019-12-06T15:14:13.531146Z", "cn": "Anne Paul", "memberof": "/epos;/", "sn": "Paul", "issued": "2019-11-06T15:14
:13.531154Z", "mail": "Anne.Paul@univ-grenoble-alpes.fr", "givenName": "Anne", "expiration": "1m"}
-----BEGIN PGP SIGNATURE-----
Version: GnuPG v1

-----END PGP SIGNATURE-----

**Comment by javiquinte** [comment]
Hi @apaul-uga 
I see 2 users:

- Number 2659: with Surname "PAUL" and email anne.paul@univ-grenoble-alpes.fr (with access to AA)
- Number 3049: with Surname "Paul" and email Anne.Paul@univ-grenoble-alpes.fr (no access to AA)

One way to solve it is to authorize both. But actually you created two accounts, one from CNRS and one from the University.
Let me know if we should authorize both.

The other improvement **on our side** would be to make it case-insensitive. I'll see if we can implement this.
Thanks!

**Comment by javiquinte** [comment]
On behalf of @apaul-uga 

> The case-insensitive option would be fine. In the meantime, I'd like you to give access to AA to both accounts, that both correspond to me. Thanks!

**Comment by javiquinte** [comment]
OK. I contacted already the AA admins to do it. Thanks!
