### ISSUE TITLE
[EIDA token]

### ISSUE THREAD

**Issue by stephenmonna** [EIDA/userfeedback#42]
Dear all,
I am an authorized person to download Z3 (AA-AlpArray) data. I have created a token as user part of the EPOS group, as instructed. I attach the readable part of the token below:

BEGIN PGP MESSAGE
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA1
{"valid_until": "2020-02-07T11:04:06.322722Z", "cn": "Stephen Monna", "memberof": "/epos;/", "sn": "Monna", "issued": "2020-01-08T11:04:06.322730Z", "mail": "stephen.monna@ingv.it", "expiration": "1m"}

I was able in the past to download data managed by INGV (my institution) with 
fdsnws_fetch -f $event.txt -a /home/stephen/eidatoken -v -o $event.mseed
But when I try to download data from AA French stations (both permanent and temporary) I fail and receive for all data a message of the type

2016-04-13T13.55.17.txt
requesting AA stations for 2016-04-13T13.55.17.txt - event 16 out of 526
Wed Jan  8 12:06:21 CET 2020
using token in /home/stephen/eidatoken:
{"valid_until": "2020-02-07T11:04:06.322722Z", "cn": "Stephen Monna", "memberof": "/epos;/", "sn": "Monna", "issued": "2020-01-08T11:04:06.322730Z", "mail": "stephen.monna@ingv.it", "expiration": "1m"}
getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query
authenticating at https://ws.resif.fr/fdsnws/dataselect/1/auth
invalid auth response: **This token does not grant access to any data hosted at RESIF. You are member of /epos;/. Please contact the PI of the data you are looking for to grant you access.**
did not receive data from Z3.A193A.*.BH?, Z3.A193A.*.HH?

How to solve this problem ?

Thank you for your help! Best regards,
Stephen

**Comment by javiquinte** [comment]
Dear @stephenmonna ,
In the field `memberof` the group `/epos/alparray` is missing. This means that you actually don't have access to AA data. I'm including @sheimers in this issue, so that he can give you access again(?).
Just by curiosity, do you have the old token which you used to download data from INGV? Can you post the readable part?

Thanks for the feedback!

**Comment by sheimers** [comment]
Stephen Monna was missing from the Alparray group, I have added him today. Please get a new token and try again.

**Comment by stephenmonna** [comment]
Problem solved, thank you!
