### ISSUE TITLE
[EIDA token] No access to AA data with token

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#43]
_On behalf of Pasquale De Gori_

I am one of the researchers of AASN Core Group taking part to  the INGV group  of Claudia Piromallo.
I would like to inform you that my token, downloaded  at  https://geofon.gfz-potsdam.de/eas doesn't work properly and I don't have access to data.

Typical warning messages are `Error 403: Forbidden, access denied` 

I am registered in b2access as member EPOS.
I am doing something wrong?
How can solve the problem?

Here you can read the token

`{"valid_until": "2020-02-12T21:41:00.019564Z", "cn": "Pasquale De Gori", "memberof": "/epos;/", "sn": "De Gori", "issued": "2020-01-13T21:41:00.019572Z", "mail": "pasquale.degori@ingv.it", "givenName": "Pasquale", "expiration": "1m"}`

**Comment by javiquinte** [comment]
Hi Pasquale.
From what I can see, you don't actually have access (`"memberof": "/epos;/"`), as there is no alparray group which you are member of.
@sheimers Could you check permissions and fix in case is needed?

**Comment by PasqualeDeGori** [comment]
Hi Javier and Stefan 
at http://www.alparray.ethz.ch/en/seismic_network/backbone/management
I am part of the registered researchers (Claudia Piromallo INGV group, 5th row)
Thanks for help

**Comment by sheimers** [comment]
Hi Javier and Pasquale,
I have added PasqualeDeGori to the Alparray group at b2access.
Stefan

**Comment by PasqualeDeGori** [comment]
Hi Javier and Stefan
using a new token I am now able to get data.
Many thanks for help
Ciao
Pasquale
