### ISSUE TITLE
[EIDA token] / dataselect issue with restricted data / different behaviour of obspy 1.1.0 vs. 1.1.1

### ISSUE THREAD

**Issue by kaestli** [EIDA/userfeedback#44]
[this may as well be an obspy issue, however maybe you have seen it or know it from your own experience.]

Hi
i am debugging an alparray user trying to download large amounts of closed data (day- and channel-wise) all across Z3 using the obspy routing client and token authentication.
The error description is:
1. typically it does not work
2. sometimes a few day files can be retrieved, with obspy 1.1.1 more often than with 1.1.0, but not repeatable.

what i can see:

- the token is valid
- when presenting it at dataselect/auth, different EIDA nodes (i have not checked all) provide valid credentials
- when mimicrying the process with curl, it actually works.

In eida.ethz.ch logs, i observe: 

in the case of obspy 1.1.0:

1. obspy sends a request to station (http 200 response) (to check for open or closed data? the user script does not contain that station request.)
2. obspy sends the token to auth (http 200 response with temporary credentials)
3. obspy sends post request to query (http 403 - forbidden / access blocked to restricted data
4. (2 and 3 may repeat several times)

in the case of obspy 1.1.1:

1. obspy sends a request to station (http 200 response) 
2. obspy sends the token to auth (http 200 response with temporary credentials)
3. obspy sends post to queryauth (http 401 - auth required)
4. obspy sends post to queryauth (http 200 - auth required) (the standard two-step digest challenge)

(looks like with our the obspy 1.1.0 client erraneously looks for encrypted data at query than queryauth.)

(the randomness of the issue reported i could not observe, at least not with regards to our logs)

According to obspy release notes, obspy 1.1.0 should support both token based authentication and the routing client, so it may also be a configuration issue with our and potentially other eida endpoints.

Has anybody seen, or solved similar issues?

**Comment by flofux** [comment]
Hi @kaestli ,

from my experience the token system does not work reliably with ObsPy 1.1.0 and you should always use ObsPy 1.1.1 or newer.

Concerning the randomness of request success ... well, that's something that's hard to formulate and reproduce, but we basically observe the same behaviour (and other people report it to me as well). Still, when running one request over a bunch of stations/days it's far from guaranteed that actually all available data will land on your disk. Usually we run any download script many many times and we slowly iterate towards completeness ... most data is usually downloaded at first try, but something is always missing. And each time we repeate the download we will get little additional data until eventually we call it "complete" and do not try any longer.

**Comment by kaestli** [comment]
hi @flofux 

Thanks for sharing your experience!

Although all-in-all this does not sound very promising (everybody is crying for good old arclink here), I'll take it as an answer and recommend to use ObsPy 1.1.1 (if at all obspy)

just for your full documentation: a reproducable (if not systematic) part of the behaviour seems to be the following:

from the side of the data center I see the following behaviour when an user tries to download a channel requiring authentication:

with obspy 1.1.0
- handshake
- auth
- station request (presumably to check the openness of the data)
- auth
- query - with 403 response
(looks like the client does not understand that the data is closed and should be requested on queryauth rather than auth):
129.132.152.156 - - [21/Jan/2020:17:12:13 +0000] "GET /fdsnws/station/1/application.wadl HTTP/1.1" 200 722 15957 "-" "ObsPy/1.1.0 (Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial, Python 3.5.2)"
129.132.152.156 - - [21/Jan/2020:17:12:13 +0000] "POST /fdsnws/dataselect/1/auth HTTP/1.1" 200 41 95350 "-" "ObsPy/1.1.0 (Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial, Python 3.5.2)"
129.132.152.156 - - [21/Jan/2020:17:12:13 +0000] "POST /fdsnws/station/1/query HTTP/1.1" 200 229 13011 "-" "ObsPy/1.1.0 (Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial, Python 3.5.2)"
129.132.152.156 - - [21/Jan/2020:17:12:14 +0000] "POST /fdsnws/dataselect/1/auth HTTP/1.1" 200 41 75269 "-" "ObsPy/1.1.0 (Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial, Python 3.5.2)"
129.132.152.156 - - [21/Jan/2020:17:12:14 +0000] "POST /fdsnws/dataselect/1/query HTTP/1.1" 403 200 14153 "-" "ObsPy/1.1.0 (Linux-4.4.0-116-generic-x86_64-with-Ubuntu-16.04-xenial, Python 3.5.2)"



with obspy 1.1.1:
- handshake
- auth
- station request (presumably to check the openness of the data)
- auth
- queryauth
129.132.152.156 - - [21/Jan/2020:17:41:14 +0000] "GET /fdsnws/station/1/application.wadl HTTP/1.1" 200 722 18269 "-" "ObsPy/1.1.1 (Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid, Python 3.7.6)"
129.132.152.156 - - [21/Jan/2020:17:41:14 +0000] "POST /fdsnws/dataselect/1/auth HTTP/1.1" 200 41 98062 "-" "ObsPy/1.1.1 (Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid, Python 3.7.6)"
129.132.152.156 - - [21/Jan/2020:17:41:14 +0000] "POST /fdsnws/station/1/query HTTP/1.1" 200 229 21043 "-" "ObsPy/1.1.1 (Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid, Python 3.7.6)"
129.132.152.156 - - [21/Jan/2020:17:41:14 +0000] "POST /fdsnws/dataselect/1/auth HTTP/1.1" 200 41 85021 "-" "ObsPy/1.1.1 (Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid, Python 3.7.6)"
129.132.152.156 - - [21/Jan/2020:17:41:14 +0000] "POST /fdsnws/dataselect/1/queryauth HTTP/1.1" 401 12 5256 "-" "ObsPy/1.1.1 (Linux-4.4.0-116-generic-x86_64-with-debian-stretch-sid, Python 3.7.6)"

We will discuss this also with obspy people.

**Comment by javiquinte** [comment]
Hi @kaestli 
In the README file of this repository we wrote 9 months ago that there are issues with the authentication with Obspy 1.1.0, so 1.1.1 should be used.
In the same README file we recommend Obspy and fdsnws_fetch (from the `fdsnwsscripts` package) to download data. As can be seen from the issue tracker, there are no issues with these two packages regarding download of restricted data.
Thanks @kaestli and @flofux for the feedback!
