### ISSUE TITLE
Request to access Alparray data

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#47]
On behalf of @Tahiraaaa

Hey everyone,

I also react to this issue, because unfortunately I have the same problem even if Stefan added me yesterday to the AlpArray group. After requesting today a new token.( Tried it using the Obspy example, but no success in retrieving data: I get 0 Traces in stream). I would like to know if there is sth wrong with my token?

The token has the following details:

```
{"valid_until": "2020-02-07T09:32:19.161208Z", "cn": "Tahira Ashruf", "memberof": "/epos;/", "sn": "Ashruf", "issued": "2020-02-06T09:32:19.161212Z", "mail": "tahira.ashruf@ingv.it", "givenName": "Tahira", "expiration": "1d"}
```

Kind regards,
Tahira

_Originally posted by @Tahiraaaa in https://github.com/EIDA/userfeedback/issues/45#issuecomment-582817666_

**Comment by javiquinte** [comment]
Hi @Tahiraaaa
I opened a new issue as the previous one  ( #45 ) had been solved. Just to keep track properly of what is still open and solved.
@sheimers can give you access after checking that you are in the list of users.

Thanks!

**Comment by sheimers** [comment]
Hello Tahira, I see you actually have two accounts at epos. One with the name "Tahira Ashruf" and the other one "Tahira Nicole Ashruf". Yesterday I only added the second one to the alparray group (I didn't realize there were two or the other was added later). You probably have requested the token above with your other account. I have now (2 mihnutes ago) added the other one to alparray too. Please try again.

**Comment by sheimers** [comment]
In general: The groups are in the token, eg:  "memberof": "/epos/alparray;/epos/esm;/epos;/"

If you don't see alparray in the token then you can't download alparray data. That's why you need a new token after you have been added to the group.

**Comment by Tahiraaaa** [comment]
Yes it is working now. Thanks a lot :)
