### ISSUE TITLE
[No Data] No data received but stations operational

### ISSUE THREAD

**Issue by grajh** [EIDA/userfeedback#48]
Hi!

I was trying to obtain some data through fdsnws service using both Obspy (v1.1.1) and 'fdsnws_fetch'. It would seem I am missing quite a lot of data (see attached plot at the bottom).

See for example MN.TRI..HHZ. Station metadata (below) says the channel was operational in the requested timeline. I also checked for any restriction and there is none. The data is freely available (http://webservices.ingv.it/fdsnws/station/1/query?network=MN&station=TRI&level=channel).

MN|TRI||HHZ|45.709|13.764|161|100|0|-90|STRECKEISEN STS-1H-VBB|942841000|0.02|M/S|100|2005-04-08T08:00:00|2017-08-16T10:00:00

See also OE.OBKA..HHZ. I am getting no data until 2016, despite the station being in operation from the end of the year 1998.

OE|OBKA||HHZ|46.5092|14.5489|1074.7|0.0|0.0|-90.0|STS-2|620017000.0|0.3|M/S|80.0|1998-12-04T00:00:00|

An example of fdsnws_fetch line and corresponding output.

```
$ fdsnws_fetch -v -r 2 -w 5 -t 15 -N "OE" -S "OBKA" -L "*" -C "H*" -s "2014-04-19T11:31:31:100000" -e "2014-04-19T11:37:01:100000" -o "./events_fs/20140419113201/seismograms/fdsnws_fetch/OE.OBKA..H*.2014.4.19.11.31.31.MSEED" -a "/home/gregor/eidatoken"
using token in /home/gregor/eidatoken:
{"valid_until": "2020-02-12T20:14:30.901327Z", "cn": "Gregor Rajh", "memberof": "/epos/alparray;/epos;/", "sn": "Rajh", "issued": "2020-01-13T20:14:30.901331Z", "mail": "gregor.rajh@ntf.uni-lj.si", "givenName": "Gregor", "expiration": "1m"}

getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?station=OBKA&network=OE&starttime=2014-04-19T11%3A31%3A31%3A100000&endtime=2014-04-19T11%3A37%3A01%3A100000&channel=H%2A&location=%2A&format=post
authenticating at https://www.orfeus-eu.org/fdsnws/dataselect/1/auth
authentication at https://www.orfeus-eu.org/fdsnws/dataselect/1/auth successful
getting data from http://www.orfeus-eu.org/fdsnws/dataselect/1/queryauth
received no data from http://www.orfeus-eu.org/fdsnws/dataselect/1/queryauth
did not receive data from OE.OBKA.*.H*

In case of problems with your request, plese use the contact form at

    http://www.orfeus-eu.org/organization/contact/form/?recipient=EIDA
```

In obspy I am **not** getting "no content" exception, but no data is parsed to a stream. I have also tried quality indicator option in Obspy to no avail.

 OE.OBKA..HHZ.2004.3.20.5.29.35
0 Trace(s) in Stream:

This is an excerpt from my code for Obspy fdsnws client.

```
if import_bool:
            from obspy.clients.fdsn import RoutingClient

            client = RoutingClient(
                "eida-routing", credentials=credentials,
                debug=debug
                )
        else:
            file_write = open(root_folder + f'fdsnws_fetch_{timestamp}', 'a')
            file_write.truncate()

if import_bool:
    try:
        strm = client.get_waveforms(network=ntwrk,
            station=acrym, location='*', channel=chn,
            starttime=stime, endtime=etime)
        print('\n', fn)
        print(strm)
        log_write.write('\n' + fn)
        log_write.write('\n' + str(strm))
        log_write.write('\n')
        if len(strm) > 0:
            strm.merge(method=1, fill_value=0)
            for trc in strm:
                print('\t', trc.id)
                log_write.write('\t' + trc.id)
                log_write.write('\n')
                trc_save = \
                    root_folder + wf_name + trc.id + fnt
                trc.write(trc_save, format='MSEED')
        else:
            pass
    except Exception as e:
        print('\n', fn)
        print(e)
        log_write.write('\n' + fn)
        log_write.write('\n' + str(e))
        log_write.write('\n')
```

By the way. What 'retry', 'wait' and 'timeout' argument values do you recommend setting in 'fdsnws_fetch' script? I set them to 1, 5, 5 respectively, in order to speed up the process, because I have a lot of requests generated by Python file and the default values really seemed too high.

One thing I noticed. The 'fdsnws_fetch' script seems more reliable. In the first try it downloaded more data than the Obspy client.

Thank you for your help.

Gregor

![downloaded_data](https://user-images.githubusercontent.com/32673009/74111704-fa9d1e80-4b96-11ea-905a-04ac673e0e74.png)

**Comment by javiquinte** [comment]
Hi Gregor.
Thanks for the feedback! We really need it.
I've checked the availability at http://www.orfeus-eu.org/data/eida/quality/availability/ of OE.OBKA and it seems that for HHZ there is only data from Oct 2015. @jbienkowski Could you confirm that?
Regarding MN.TRI, could you @massimo1962 tell Gregor which data is available? I could not find much information from that station in WFCatalog.

**Comment by grajh** [comment]
I see. I thought there was something wrong on my side. It seems I will have to get in touch with people responsible for these networks to obtain some more data.

**Comment by jbienkowski** [comment]
Hi @javiquinte and @grajh,

I have just checked it directly in our archive (ODC) - for OE.OBKA, HH* channels are available since 2015, before that we have only broadband (BH*).

Cheers,
Jarek

**Comment by massimo1962** [comment]
Hi everybody,
I have just try this
https://webservices.ingv.it/fdsnws/dataselect/1/query?network=MN&station=TRI&starttime=2014-04-19T11:31:31&endtime=2014-04-19T11:37:01
 and it works; 

@grajh probably I need a more specific query in order to better understand where is the problem (likely for some date we have some missing data but I don't understand which);

@javiquinte regards to the wfcatalog probably we have to check something about our availability (seems that some years are not inserted into db but are present into repo) I'll investigate on it.

Cheers,
Massimo

**Comment by javiquinte** [comment]
Hi @massimo1962 !
Actually, there is no `HH` data for the dates you used in the query. The channel filter was missing in your link. And according to the metadata there should be data from 2005 to 2017. Could you tell us what's the situation for the HH components?
Thanks!

**Comment by massimo1962** [comment]
Hi, sorry if I don't understand the question.
now I have check into our repo and  the HH* data are available only since 2017; before of this date there are only the BH* data.
Thanks.

**Comment by grajh** [comment]
Thank you all for your help. I will try to obtain this data in some other way.

Do you think that in the future the older data with higher sampling rates will also be included in the repository?

**Comment by javiquinte** [comment]
Thanks @massimo1962 !
I guess that explains the huge gap in the plot added by @grajh (~2011-~2017).
@grajh I'll consider this solved but we can open it if there is something pending.
Cheers,
