### ISSUE TITLE
[Metadata] missing Z3 stations: A110A, A356A

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#49]
Hello,

there's no metadata available for these two AlpArray stations (both in Germany, so should be hosted by LMU):

A110A
A356A

Waveform data is available, but no metadata can be found with direct or routed requests. Stationbook and WebDC also don't know these two stations.

**Comment by javiquinte** [comment]
I already sent this to our LMU contacts. Thanks @flofux for the feedback!

**Comment by aschloem** [comment]
Hey,
I fixed it. The metadata of A110A and A356A are now available on our server.
Thank you for the feedback.
