### ISSUE TITLE
FR + MT metadata producing zeros

### ISSUE THREAD

**Issue by PetrColinSky** [EIDA/userfeedback#52]
Dear all,
continuing with my AlpArray data processing, I found another issues. Keeping issue #51 open, I am submitting another one, since this problem is bit different. I found 25 stations, where after deconvolving the response, on the output, there are only zeros. 1 is MT station, 24 are FR stations, see attached table. Every row is a day, where I am looking for an earthquake. The starting time gives a window of 2 minutes, which I used to produce the table. Whenever there is a red cell, the output is zero. Whenever there is a green cell, its OK. I checked visually, that the raw data are NOT zero, there is a signal. White means the station was not deployed and yellow means, there was another reason why I did not investigate the data (no file = no data for the whole day; no-data = no data for the 2 mins window, miss = missing trace; ... - not important in the moment). I looked into the metadata and I found a clear correlation with the sensor change. Whenever there is a change from red cell to green cell for a given station, it corresponds to a change of the sensor. These are schematically noted below the table. Red sensor means zeros, green sensor means its OK. I don't see clear correlation with the type of the sensor, just maybe, if its Trillium 120PH and Trillium 120QA, its always OK. The red sensors look random. There is one station, where there is a change from red to green WITHOUT a change of sensor, its OGRV. Here I found, that the response information differs by an additional stage for the "red" epoch, where the NormalizationFactor is = 0. I then scanned the whole thing for the NormalizationFactor and found a clear correlation with these NormalizationFactor=0 with the red epochs. I still dont know how exactly this happened and why there are these additional stages in the xml file.

thanks for looking at it
stay healthy and fine
cheers
petr

[zeros.pdf](https://github.com/EIDA/userfeedback/files/4375030/zeros.pdf)

**Comment by javiquinte** [comment]
Thanks again for the detailed feedback @PetrColinSky !
Let's wait for an answer from @jschaeff 

And yes, stay healthy!

**Comment by PetrColinSky** [comment]
As mentioned in my comment to issue #51, when downloading the xml directly from the RESIF portal, it works fine. The problem of the 25 stations reported above (FR+MT) was really the NormalizationFactor, which has a finite reasonable value in the xmls from RESIF, and which is =zero in the xml from EIDA. In addition to these 25 stations, I had a similar issue with RD.SAVF and RD.ETNF, where the application of the metadata blew up the records to infinity. I think it has something to do with zeros/missing entries somewhere in the FIR filter coefficients. After deconvolving using the xml from RESIF, it works fine. I did not investigate the details of the difference in the xmls for these two stations. So, for the 27 AA temporary Z3 stations as well as for the 27 (FR+MT+RD) stations reported here, it works if you get the xml from RESIF. It does not, if you get it from EIDA. So, I am fine with processing the data now, however, the EIDA problem remains.
cheers
Petr

**Comment by javiquinte** [comment]
Hi @PetrColinSky 
Check also here my comment in the other issue 
https://github.com/EIDA/userfeedback/issues/51#issuecomment-606664216

**Comment by petrrr** [comment]
@PetrColinSky same question here, what do you mean with:

>    [...] t does not, if you get it from EIDA. [...]

How exactly do you download these data?
* Is it the portal?
* the federator?
* some intelligent client?

It might help to understand better what exactly is (was) going on. Just in case there is some hide problem.

**Comment by PetrColinSky** [comment]
@petrrr : see my reply for issue #51. "from EIDA" I mean using ObsPy 1.1.1 routing client. By "directly" I mean typing the command to URL pointing directly to the node (RESIF, or other) like

http://ws.resif.fr/fdsnws/station/1/query?network=Z3&station=A151A&channel=???&level=response
or
http://erde.geophysik.uni-muenchen.de/fdsnws/station/1/query?network=Z3&station=A145A&channel=???&level=response

cheers
petr

**Comment by javiquinte** [comment]
Considering what @PetrColinSky posted in
https://github.com/EIDA/userfeedback/issues/51#issuecomment-607199639
I will close this issue for the time being. Issue #52 is still open because some clarifications are needed between @PetrColinSky and Antje (LMU).
If new inconsistencies are discovered between data and metadata we can always open a new issue.
