### ISSUE TITLE
[WFcatalog] Availability interface: dropdown-menu limited to 20 SCNL-objects?

### ISSUE THREAD

**Issue by flixha** [EIDA/userfeedback#53]
I would like to report a small issue with the WFcatalog data availability user interface at: https://www.orfeus-eu.org/data/eida/quality/availability/ 
(sorry for posting without template - but I couldn't see that this report would fit one of the categories)

The availability interface is a great tool to explore data and understand the metadata changes at a station. But it appears that no more than 20 channel-location combinations can be selected from the drop-down menu, even if more such combinations exist. As an example, please check the display for the following request (see screenshot below): 
DK    COP     2004-12-01     2014-12-31

![dropdownmenu_EIDA_availability](https://user-images.githubusercontent.com/16126887/79128024-24471180-7da3-11ea-9b05-bb9c120e58a8.png)

**Expected behavior:**
The dropdown-menu should list all available location-channel combinations, even if these are more than 20 (in this case, at least "HHZ" is missing). 
If this limit is required due to service capacity or display limitations, then I think there should be a warning and the interface should allow filtering by channel or location code. 

I wasn't able to directly compare the list to the output of an availability-webservice (like http://service.iris.edu/fdsnws/availability or https://ws.resif.fr/fdsnws/availability), because I don't know whether that is already implemented at ODC and GFZ, and what their address would be. 

If there needs to be a limit, a suitable value would have to be at least 100. Station IU.KONO ([IRIS's availability web service](http://service.iris.edu/fdsnws/availability/1/extent?station=KONO&network=IU&endtime=2009-09-28T00%3A00%3A00&starttime=1995-09-13T12%3A00%3A00)), for example returns 98 different channel/location combinations between 2000 and 2020, while the EIDA availability interface is also limited to 20 (not sure if it should show 98, however). 

Desktop: Ubuntu 18.04 LTS, Firefox 75.0

**Comment by javiquinte** [comment]
Hi @flixha 
First, thanks for the feedback!
You can see here the list of channels:
[http://geofon.gfz-potsdam.de/fdsnws/station/1/query?net=DK&station=COP&start=2004-01-01&end=2004-12-31&format=text&level=channel](http://geofon.gfz-potsdam.de/fdsnws/station/1/query?net=DK&station=COP&start=2004-01-01&end=2004-12-31&format=text&level=channel)

```
#Network|Station|Location|Channel|Latitude|Longitude|Elevation|Depth|Azimuth|Dip|SensorDescription|Scale|ScaleFreq|ScaleUnits|SampleRate|StartTime|EndTime
DK|COP||BHE|55.6853|12.4325|13.0|0.0|90.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|20.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||BHN|55.6853|12.4325|13.0|0.0|0.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|20.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||BHZ|55.6853|12.4325|13.0|0.0|0.0|-90.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|20.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||HHE|55.6853|12.4325|13.0|0.0|90.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|100.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||HHN|55.6853|12.4325|13.0|0.0|0.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|100.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||HHZ|55.6853|12.4325|13.0|0.0|0.0|-90.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|100.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||LHE|55.6853|12.4325|13.0|0.0|90.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|1.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||LHN|55.6853|12.4325|13.0|0.0|0.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|1.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||LHZ|55.6853|12.4325|13.0|0.0|0.0|-90.0|GFZ:DK1980:STS-1/VBB/g=2400|1017508210.0|0.02|M/S|1.0|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||VHE|55.6853|12.4325|13.0|0.0|90.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|4070032838.0|0.02|M/S|0.1|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||VHN|55.6853|12.4325|13.0|0.0|0.0|0.0|GFZ:DK1980:STS-1/VBB/g=2400|4070032838.0|0.02|M/S|0.1|2004-12-04T00:00:00|2011-09-16T00:00:00
DK|COP||VHZ|55.6853|12.4325|13.0|0.0|0.0|-90.0|GFZ:DK1980:STS-1/VBB/g=2400|4070032838.0|0.02|M/S|0.1|2004-12-04T00:00:00|2011-09-16T00:00:00
```
They are not 20 and seem to be properly displayed on my browser (see below).

<img width="896" alt="Screenshot 2020-04-14 at 11 39 51" src="https://user-images.githubusercontent.com/4611428/79210835-b6075b00-7e45-11ea-811a-95cb1132592a.png">

What is actually weird is that you can see locations "00", which started in 2011. Could you try again? Probably clearing the cache/cookies? Another browser?

@jbienkowski Could you give us an idea if there is a strict limit (20) in the drop-down list?

**Comment by flixha** [comment]
Hi @javiquinte and thanks for the quick reply!
If you check a longer period like 2004-2014 (see link), you can see that they changed the location code from empty to "00", and installed a "10" instrument later:
http://geofon.gfz-potsdam.de/fdsnws/station/1/query?net=DK&station=COP&start=2004-01-01&end=2014-12-31&format=text&level=channel

That makes it 36 location-channel comtbinations, of which I can only see 20. I'm not sure in which order those displayed are chosen though.

**Comment by javiquinte** [comment]
I checked this and extending the time window shows me more channels. However, as you can see from my screenshot there is no limit of 20 channels

<img width="882" alt="Screenshot 2020-04-14 at 13 50 34" src="https://user-images.githubusercontent.com/4611428/79221939-f6230980-7e56-11ea-8b18-8feb8b2b8f61.png">

What it is actually wrong is that some streams are missing, but that seems to be related to some missing processing on the GFZ side. (I'm opening a new issue for this)

Routing is not the problem as it can be seen from the Obspy client.

```
>>> from obspy.clients.fdsn import RoutingClient
>>> from obspy import UTCDateTime
>>> rsClient = RoutingClient("eida-routing")
>>> st = rsClient.get_stations(network="DK", station="COP", level="channel", starttime=UTCDateTime(2004, 1, 1), endtime=UTCDateTime(2014, 12, 31))
>>> print(st)
Inventory created at 2020-04-14T11:59:08.981411Z
	Created by: ObsPy 1.1.1
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.1.1,SeisComP3 (GFZ)
	Contains:
		Networks (1):
			DK
		Stations (1):
			DK.COP (Station Copenhagen, Denmark)
		Channels (36):
			DK.COP..BHZ, DK.COP..BHN, DK.COP..BHE, DK.COP..HHZ, DK.COP..HHN,
			DK.COP..HHE, DK.COP..LHZ, DK.COP..LHN, DK.COP..LHE, DK.COP..VHZ,
			DK.COP..VHN, DK.COP..VHE, DK.COP.00.BHZ, DK.COP.00.BHN,
			DK.COP.00.BHE, DK.COP.00.HHZ, DK.COP.00.HHN, DK.COP.00.HHE,
			DK.COP.00.LHZ, DK.COP.00.LHN, DK.COP.00.LHE, DK.COP.00.VHZ,
			DK.COP.00.VHN, DK.COP.00.VHE, DK.COP.10.BHZ, DK.COP.10.BHN,
			DK.COP.10.BHE, DK.COP.10.HHZ, DK.COP.10.HHN, DK.COP.10.HHE,
			DK.COP.10.LHZ, DK.COP.10.LHN, DK.COP.10.LHE, DK.COP.10.VHZ,
			DK.COP.10.VHN, DK.COP.10.VHE
```

**Comment by flixha** [comment]
Thanks a lot for checking. I guess I should have checked this in another browser as well. In Chrome all the channels appear as they are supposed to. And I think they also do in firefox, but on my system the scroll bar apparently was hardly visible. So that solves why I didn't find the other channels. Sorry and thanks for solving!
