### ISSUE TITLE
[WFCatalog] Probably missing information for some DK.COP channels in WFCatalog

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#54]
I checked this and extending the time window shows me more channels. However, as you can see from my screenshot there is no limit of 20 channels

<img width="882" alt="Screenshot 2020-04-14 at 13 50 34" src="https://user-images.githubusercontent.com/4611428/79221939-f6230980-7e56-11ea-8b18-8feb8b2b8f61.png">

What it is actually wrong is that some streams are missing, but that seems to be related to some missing processing on the GFZ side. (I'm opening a new issue for this)

Routing is not the problem as it can be seen from the Obspy client.

```
>>> from obspy.clients.fdsn import RoutingClient
>>> from obspy import UTCDateTime
>>> rsClient = RoutingClient("eida-routing")
>>> st = rsClient.get_stations(network="DK", station="COP", level="channel", starttime=UTCDateTime(2004, 1, 1), endtime=UTCDateTime(2014, 12, 31))
>>> print(st)
Inventory created at 2020-04-14T11:59:08.981411Z
	Created by: ObsPy 1.1.1
		    https://www.obspy.org
	Sending institution: ObsPy FDSN Routing 1.1.1,SeisComP3 (GFZ)
	Contains:
		Networks (1):
			DK
		Stations (1):
			DK.COP (Station Copenhagen, Denmark)
		Channels (36):
			DK.COP..BHZ, DK.COP..BHN, DK.COP..BHE, DK.COP..HHZ, DK.COP..HHN,
			DK.COP..HHE, DK.COP..LHZ, DK.COP..LHN, DK.COP..LHE, DK.COP..VHZ,
			DK.COP..VHN, DK.COP..VHE, DK.COP.00.BHZ, DK.COP.00.BHN,
			DK.COP.00.BHE, DK.COP.00.HHZ, DK.COP.00.HHN, DK.COP.00.HHE,
			DK.COP.00.LHZ, DK.COP.00.LHN, DK.COP.00.LHE, DK.COP.00.VHZ,
			DK.COP.00.VHN, DK.COP.00.VHE, DK.COP.10.BHZ, DK.COP.10.BHN,
			DK.COP.10.BHE, DK.COP.10.HHZ, DK.COP.10.HHN, DK.COP.10.HHE,
			DK.COP.10.LHZ, DK.COP.10.LHN, DK.COP.10.LHE, DK.COP.10.VHZ,
			DK.COP.10.VHN, DK.COP.10.VHE
```

_Originally posted by @javiquinte in https://github.com/EIDA/userfeedback/issues/53#issuecomment-613401681_

**Comment by andres-h** [comment]
Availability is correct. Inventory includes some extra channels that are not archived at GEOFON according to an agreement with data provider.
