### ISSUE TITLE
[ODC][StationWS] Reponse information for GB.PGB1 missing

### ISSUE THREAD

**Issue by flixha** [EIDA/userfeedback#55]
Hi,
the response information for station GB.PGB1 contains no response stages, which I believe is an error: 
http://www.orfeus-eu.org/fdsnws/station/1/query?network=GB&station=PGB1&channel=*H*&starttime=2000-01-01&endtime=2021-01-01&level=response

I'm not sure whether zero response stages could make a valid response at all - shouldn't there always be at least 1 stage if there is a `<Response>` in the stationXML-file?
In this case, I believe the information is known and just missing (see the dataless Seed-files listed on here: ftp://seiswav.bgs.ac.uk/dataless/). Judging from these dataless-seed-files, station GB.PGB1 should possibly also contain more than just one version of the HH?-channels (updated in 2014 and 2017?).

~~Just a note for anyone trying to debug the problem: 
While the [quality metrics interface](https://www.orfeus-eu.org/data/eida/quality/metrics/) returns that data for this station is available since 2012, the [availability interface](https://www.orfeus-eu.org/data/eida/quality/availability/) currently doesn't show any data availability for network GB for me (even though that worked recently). I could open a new issue for that if it's a persistent issue.~~

Cheers,
Felix

**Comment by Jollyfant** [comment]
I've noticed that the availability page returns 204 when the end-date is in the future. Requesting data between 2019-01-01 and 2020-01-01 works fine.

![image](https://user-images.githubusercontent.com/10128244/80630106-01c82000-8a54-11ea-9762-670c41284c3d.png)

**Comment by flixha** [comment]
Sometimes I feel a bit dumb ;-)... I thought i tested several date ranges, and compared against another network.. well, apparently the availability tool works just fine! Thanks for checking!

**Comment by javiquinte** [comment]
Hi @jbienkowski 
I think that probably the first part from @flixha 's question is still unanswered. Am I right?

**Comment by jbienkowski** [comment]
Sorry, I totally missed that. Let me ask station owners if there is a newer version of the metadata available for GB stations.

**Comment by jbienkowski** [comment]
Hi @flixha 
I have just updated GB metadata, please let me know if the responses are satisfactory now.

**Comment by flixha** [comment]
Hi @jbienkowski 
thanks a lot for the quick updating of the GB metadata! I tried the new response information for station PGB1 and that response that caused errors works well.

One thing that I noticed:
When I request response information for stations from the GB network now, I only receive information for the most recent instrumentation at each station (that is, only one set of HH[ZNE] channels). As an example, [a request for Station GAL1](http://www.orfeus-eu.org/fdsnws/station/1/query?network=GB&station=GAL1&channel=*&starttime=2000-01-01&endtime=2021-01-01&level=response) returns only the newest response, but not those for previous setups any more. When I did the request a few weeks ago, I got multiple sets of responses at each station (for GAL1, two sets starting in 2006 and 2009, respectively).

**Comment by jbienkowski** [comment]
This is something I am currently trying to clarify. For some stations I was not able to merge multiple versions of metadata because of conflicts and overlaps. Those tasks normally are pretty laborious, so it might take weeks before everything is patched and agreed with the network owners.
Anyway, I am going to review everything once again to pick best out of those two datasets for the time being.

**Comment by flixha** [comment]
Thanks for the explanation. I see that there's small differences between the old and new versions of the metadata (e.g., different precision for station coordinates). The new metadata is very useful for me, as I can decide myself which version to use.

I understand that only the network maintainers can decide which version is "correct" and should hence be provided through the web service that you have control of, and that that can be a task that takes a lot of forth- and back. Thanks for the work you put into this, as I'm convinced it can benefit quite a few people!

One comment on the two versions of the metadata (potential question to the network maintainers, nothing you can solve): If these two versions are merged, then what may still be missing are information for instrumentations that are no longer operating, but that were not complete in the old version of the metadata. With "not complete" I mean that in the old version, they were either not yet included, or they were somehow problematic (e.g., empty response for station PGB1 for 2012-2017). 

Cheers,
Felix

**Comment by flixha** [comment]
Hi @jbienkowski,
I just noticed one more difference to the old inventory: While the old inventory had empty location codes, in the new inventory all location codes are set to "00". 

All continuous data from network GB are distributed with empty location code via both EIDA and IRIS, so the new response-location codes do not match any waveform-location codes.

**Comment by jbienkowski** [comment]
Hi @flixha,
I actually spent some time last week and managed to prepare a complete set of GB metadata which I merged into our inventory this morning, so you should be able to see it by now. Please verify it against your older results and let me know if it is satisfactory.
Regarding the "00" location, let me first discuss it with my colleagues and the owners to see what are the possibilities.
Cheers,
Jarek

**Comment by flixha** [comment]
Hi @jbienkowski,
thanks a lot for merging these inventories - I know that this is a lot of work!
From generally scanning some stations, this looks to resolve quite a few issues. I see that the inventory now contains the old responses, the newest ones, but also the ones inbetween that were not online originally. All station lat/lon/elevation now look consistent across channels and stations.  That's great!

I notice that several channels do not have an end date set, even though the newer reponse information for these channels should likely supercede the old version. I believe these end-dates are already missing in the SEED-files that I saw on BGS's ftp, so this is of course not an issue of the merging of inventories.

As a small difference to before, I observe that in the new inventory, each station appears multiple times, once for each set of channel start dates. Previously, all channels were grouped under one station. That does not affect the functionality of the inventory, so I'm not saying that it should be different. It only really changes the browsing behavior for me.

Big thanks for taking care of this!

**Comment by flixha** [comment]
I also noticed that there appear to be only HH? channels in the response information, while continuous data is also available for plenty of BH? channels.

**Comment by flixha** [comment]
The response for station PGB1 that is currently valid (starting 2017-05) has some very unusual troughs at high frequencies (plotted with Obspy1.2.2):
![PGB1_HHZ_response_Obspy1 2 2](https://user-images.githubusercontent.com/16126887/104573163-e0947780-5654-11eb-967d-65ca3a5bbebc.png)

As the noise PDF for the station as a result also contains these troughs as spikes, I'm guessing there is something wrong with the response:
![GB PGB1 HHZ 2020-01-01_2020-12-31_PDF](https://user-images.githubusercontent.com/16126887/104573699-7cbe7e80-5655-11eb-94bf-4f00102ddb72.png)

The response-plot cannot be reproduced by the [EIDA-response tool](https://www.orfeus-eu.org/data/eida/quality/response/) because the tool probably selects a different, no longer valid response where no endtime is specified.
