### ISSUE TITLE
[WFCatalog] no WFCatalog data for Z3 network on LMU node?

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#6]
Hi,

I tried to query the WFCatalog for Z3 stations at the LMU node, but I can't get any information. No files are created for download. I tested only Z3 stations and LHZ stream (data is existing).

Sample request, looks e.g. like this:
```
http://erde.geophysik.uni-muenchen.de/eidaws/wfcatalog/1/query?network=Z3&channel=LHZ&start=2018-01-01&end=2018-12-31&include=sample
```

**Comment by javiquinte** [comment]
I contacted Joachim Wassermann to check where could this come from.
I made another request and the system itself seems to be working. No LHZ data at WFCatalog though.

http://erde.geophysik.uni-muenchen.de/eidaws/wfcatalog/1/query?net=Z3&channel=*HZ&start=2016-03-02&end=2016-03-02

> $ grep station ~/Downloads/LMU-WFCATALOG-2019-04-29T10_32_49.733Z.json
    "station": "A030A",
    "station": "A030A",
    "station": "A032A",
    "station": "A033A",
    "station": "A033A",
    "station": "A035A",
    "station": "A035A",
    "station": "A036A",
    "station": "A036A",
    "station": "A037A",
    "station": "A037A",

> $ grep channel ~/Downloads/LMU-WFCATALOG-2019-04-29T10_32_49.733Z.json
    "channel": "HHZ",
    "channel": "BHZ",
    "channel": "HHZ",
    "channel": "HHZ",
    "channel": "BHZ",
    "channel": "HHZ",
    "channel": "BHZ",
    "channel": "HHZ",
    "channel": "BHZ",
    "channel": "HHZ",
    "channel": "BHZ",

**Comment by flofux** [comment]
Sorry, I should have been more specific. Not all stations at LMU node are affected. For example all the Z3.A03xA stations are accessible with WFCatalog (they do only provide HH* streams, thus of course no LH* info can be retrieved).

Stations in the range A100A to A109A (including the B/C/D replacements) do not have WFCatalog entries for any of their channels.

**Comment by megies** [comment]
I will have a look as soon as possible.

**Comment by megies** [comment]
So it turns out, the problem was that the WFCatalog collector ignores symbolic links and we use symlinks for Z3 data in our regular SDS for LMU network.
I will reprocess all Z3 data but I guess it will take some time to complete, considering this is about several years of data on many stations.

**Comment by javiquinte** [comment]
Any hint to make it as easy as possible, @Jollyfant ? Or just re-processing from scratch Z3 is the solution?

**Comment by megies** [comment]
I can feed the collector the missing Z3 files one by one. No worries.

**Comment by Jollyfant** [comment]
> I can feed the collector the missing Z3 files one by one. No worries.

or pass it the directory using `--dir`.

**Comment by megies** [comment]
So, I'm currently going backwards through all Z3 data from today. The processing is roughly doing 40 days per day wall clock time, so it might take quite a while to go through all data (maybe a month or more?). If that is too long a wait for you I might have to split it up into multiple jobs.

**Comment by javiquinte** [comment]
@megies Is there any chance to go only through the missing stations? (e.g. A10* and friends?)
It seems that the other stations were OK.

**Comment by Jollyfant** [comment]
@javiquinte the collector skips files that are already in the database so it should by default only reprocess "A10* and friends".

**Comment by javiquinte** [comment]
I've checked and data is already available for those stations. Now we only need to wait for the process to be finished, so I'm closing this issue.
Thanks @megies !

**Comment by megies** [comment]
> @megies Is there any chance to go only through the missing stations? (e.g. A10* and friends?)
> It seems that the other stations were OK.

I am going through only the missing data, explicitly specifying to the script which files it should work on.

> the collector skips files that are already in the database

I am assuming you are checking timestamps, though? So that changed files get reprocessed?

**Comment by Jollyfant** [comment]
> I am assuming you are checking timestamps, though? So that changed files get reprocessed?

The collector confirms checksums when you give it `--update`. So use that for updating. By default it doesn't look for files that changed, only for files that are new and have no database entry.

**Comment by megies** [comment]
I started the reprocessing of Z3 with 5 processes now, so I'd guess it will be done in like 8-10 days.

**Comment by megies** [comment]
> The collector confirms checksums when you give it `--update`. So use that for updating. By default it doesn't look for files that changed, only for files that are new and have no database entry.

Oh OK, good to know, I need to put that on some of the cronjobs to be on the safe side

**Comment by megies** [comment]
Uhm actually.. this might mean that all the daily processed data needs to be reprocessed.. since I have (rather had) a cronjob running every 8 hours without the `--update` flag.. :-/

**Comment by Jollyfant** [comment]
Ah right. Our set up is once per night, and then `--update` the previous week.

**Comment by megies** [comment]
@Jollyfant I am a bit confused by the docs of the collector script

https://github.com/EIDA/wfcatalog/blob/82d341d654212a5ee95af609e3770cee87dc81ad/collector/WFCatalogCollector.py#L46-L53

```
   Giving the --update flag does a checksum change detection on  
   all input files. The documents in the database that are dependent 
   on the changed files are removed, reprocessed, and inserted. Updating 
   does NOT insert any new files in the directory. 
    
   An update can be forced by giving --update which skips the checksum change'exampleson and reprocesses all files. 
   Giving --past {day, yesterday, week, fortnight, month} will reprocess the files in 
  the specified window. 
```

I think in the second paragraph it should be `--force` instead of `--update`? So, when using `--update` together with any `--past` option, newly added files are not picked up I take it? How about `--force`? Because from the looks of it I have to reprocess **all** data, and I am a bit unsure which options to use actually (I can not use `--past` for that apparently, so I will likely have to manually specify directories)?

**Comment by megies** [comment]
> It might be a good idea to have `--past` also accept a datestring, like `--past 2018-01-01` or `--past 2018-001` to reprocess specific dates.

Ah nevermind, I saw the `--date` flag now. I didn't saw it earlier because I was looking at the docstring on top of the collector script (which only states a subset of all flags) but not the `--help` output.
