### ISSUE TITLE
Overlapping channel epochs NO.BRBA.00.HH?

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#60]
Station `BRBA` which is part of the `NO` network has some overlapping channel epochs defined w.r.t. its `HH?` channels. The corresponding `fdsnws-station` URL is:

http://eida.geo.uib.no/fdsnws/station/1/query?net=NO&sta=BRBA&cha=HH?&level=channel

**Comment by jan-michalek** [comment]
Resolved by updating NO metadata at UIB node.
