### ISSUE TITLE
Overlapping channel epochs for VI.ASB..HHZ

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#62]
Channel epochs are overlapping for

http://orfeus-eu.org/fdsnws/station/1/query?net=VI&sta=ASB&cha=HHZ&level=channel

Most probably this is a typo since the other channels of the station are configured correctly. Could you fix this, please?

**Comment by jbienkowski** [comment]
On hold, network owner waiting for manpower to fix it.
