### ISSUE TITLE
Overlapping channel epochs for HP.VLX..HHN,HHZ

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#65]
Overlapping channel epochs are defined for

http://eida.gein.noa.gr/fdsnws/station/1/query?net=HP&sta=VLX&cha=HHN,HHZ&level=channel

Multiple channels with the same channel code are configured without providing an `endDate`. Thus, overlapping.

**Comment by nikosT** [comment]
The issue is now fixed.
Thank you!
