### ISSUE TITLE
Overlapping channel epochs for station of net=ZB

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#66]
Overlapping channel epochs are defined for

http://geofon.gfz-potsdam.de/fdsnws/station/1/query?net=ZB&sta=SKEGG&level=channel

Could you fix this, please?

**Comment by damb** [comment]
Additional stations with overlapping channel epochs of `net=ZB` are:

- [EDA](http://geofon.gfz-potsdam.de/fdsnws/station/1/query?net=ZB&sta=EDA&level=channel)
- [KRIST](http://geofon.gfz-potsdam.de/fdsnws/station/1/query?net=ZB&sta=KRIST&level=channel)
- [INNST](http://geofon.gfz-potsdam.de/fdsnws/station/1/query?net=ZB&sta=INNST&level=channel)

**Comment by andres-h** [comment]
It's a 3rd-party network. I've added a Redmine ticket, so hopefully the network operator can provide corrected metadata.
