### ISSUE TITLE
[Federator] Error in WFCatalogue request

### ISSUE THREAD

**Issue by xrise75** [EIDA/userfeedback#69]
**Describe the problem**
Trying to get data availability from WFCatalogue through the WFCatalog Data Availability Interface i get the following error:

OOPS! The WFCatalog returned the following error:

```
Error 413: Request too large

Request too large

Usage details are available from http://www.fdsn.org/webservices/

Request:
http://eida-federator.ethz.ch/eidaws/wfcatalog/json/1/query?include=sample&net=HL&sta=ATH&start=2019-01-01&end=2020-06-30&cha=HG?,?H?,?DF&include=sample&net=HL&sta=ATH&start=2019-01-01&end=2020-06-30&cha=HG?,?H?,?DF

Request Submitted:
2020-06-18T08:19:35.084341

Service version:
0.11
```

**To Reproduce**
http://eida-federator.ethz.ch/eidaws/wfcatalog/json/1/query?include=sample&net=HL&sta=ATH&start=2019-01-01&end=2020-06-30&cha=HG?,?H?,?DF&include=sample&net=HL&sta=ATH&start=2019-01-01&end=2020-06-30&cha=HG?,?H?,?DF

**Comment by damb** [comment]
Thanks for your report, @xrise75.

This issue you reported is rather a configuration issue. Currently the service returns this error if `>=1000` stream epoch days are requested. We can relax this configuration for the service, however, there will be some limit for sure.

**Comment by xrise75** [comment]
Thank you fro your prompt responce @damp

I think it should be relaxed because the user can not even make a request for a full year data availability.

**To Reproduce**
http://eida-federator.ethz.ch/eidaws/wfcatalog/json/1/query?include=sample&net=CL&sta=MALA&start=2019-01-01&end=2019-12-31&cha=HG?,?H?,?DF&include=sample&net=CL&sta=MALA&start=2019-01-01&end=2019-12-31&cha=HG?,?H?,?DF

The usual request might even require 5-10 years availability for each station

**Comment by damb** [comment]
Ok. Assuming station `MALA` has an average number of channels which is `9` in the time window above including an average amount of related waveform metadata.
`~2.2M` of  `json` data is returned by `eidaws-wfcatalog` for all channels for 1 year (with `include=sample`). Hence, for ten years `~22M`.

At `eidaws-federator` side we should be fine buffering up to `200M` for a `/eidaws/wfcatalog/1/query` request i.e. 10 avarage stations for ~10 years. This would result in roughly 330000 stream epoch days.

Could you live with that number?

BTW: The path in the URL from above is not correct. Instead it should be:

http://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?include=sample&net=CL&sta=MALA&start=2019-01-01&end=2019-12-31&cha=HG?,?H?,?DF

**Comment by damb** [comment]
@xrise75, could you give it once more a try? I deployed a fix.

**Comment by xrise75** [comment]
@damp It is ok now! Thank you!

I am requesting data from the past 7 years through the ORFEUS  WFCatalog Data Availability tool  and I get them!

http://eida-federator.ethz.ch/eidaws/wfcatalog/1/query?include=sample&net=CL&sta=MALA&start=2013-01-01&end=2020-06-01&cha=HG?,?H?,?DF
