### ISSUE TITLE
[Metadata] Z3.A003A still missing

### ISSUE THREAD

**Issue by flofux** [EIDA/userfeedback#7]
http://www.orfeus-eu.org/fdsnws/station/1/query?&net=Z3&station=*&format=text&level=station

still not showing A003A :-/

Same as discussed here: Issue #4 (I wasn't able to re-open it)

**Comment by javiquinte** [comment]
Issue #4 is reopened

**Comment by Jollyfant** [comment]
Confirmed: http://www.orfeus-eu.org/fdsnws/station/1/query?station=A003A
