### ISSUE TITLE
[Metadata] Missing response information for GE.DAG.00.HH?, DK.COP.10.BH? 

### ISSUE THREAD

**Issue by flixha** [EIDA/userfeedback#70]
The stationws -service does not return any response information for the following channels, even though there are data available for the channels at the indicated times:

DK.COP.10.BH? - years 2017-now [link to responses since 2017 - no BH?-channels for location code 10](geofon.gfz-potsdam.de/fdsnws/station/1/query?network=DK&station=COP&channel=*H*&location=10&starttime=2017-01-01&endtime=2021-01-01&level=response)

GE.DAG..HH? - years 2017-2019 [link to responses since 2010 -  no HH-channels](http://geofon.gfz-potsdam.de/fdsnws/station/1/query?network=GE&station=DAG&channel=*H*&starttime=2019-01-01&endtime=2023-01-01&level=response)

(I checked availability with the [EIDA-availability tool](https://www.orfeus-eu.org/data/eida/quality/availability/) and got proper availability 10 minutes ago, while it's not returning any values for GFZ-hosted data right now. ALternative service to compare actual availability is [Geofon's waveform archive](https://geofon.gfz-potsdam.de/waveform/archive/data.php?network=76&station=2502&year=2019&day=28&month=12).

From the [IRISDMC](http://ds.iris.edu/mda/GE/DAG/), there are matching responses for GE.DAG..HH? with starttime in 1997 and no endtime. But as all others channels (e.g. BH) have later been changed, I don't think the HH?-responses listed there should be used for the new HH-channels for which data is available. I have the impression that the Geofon-node is more up-to-date on the metadata for the GE-network than IRISDMC, but if the data can also be requested from the IRISDMC then it would be good if users could get the up-to-data metadata independent of the datacenter they choose.

**Comment by javiquinte** [comment]
Hi @flixha 
First of all, thanks a lot for the feedback!
We will take a look at it ASAP and let you know.
Regarding IRISDMC and GEOFON, you can always check from the FDSN website which data centre is authoritative for a particular network. For instance,
http://www.fdsn.org/networks/detail/GE/

There, you can see that is GEOFON the authoritative data centre and where you should get the (meta)data from. You could find some data replicated in IRIS, but as you have well supposed, metadata could be outdated/wrong and data could be seriously incomplete.

**Comment by flixha** [comment]
Thanks for your quick reply!
I didn't know that there was usually one authoritative metadata source defined, so thanks a lot for answering that. For the Geofon network that was kind of obvious of course.
Just our of interest, is there a way to find the authorative source for metadata for networks that are not obviously associated with one or the other data centre, e.g., [network GB](http://www.fdsn.org/networks/detail/GB/)(data available through both EIDA and IRIS), from the FDSN-webpage?

**Comment by javiquinte** [comment]
Hi @flixha 
I've checked the case of GB. The formal decision between both data centres is that ODC is the authoritative one. That means that data and metadata should be read from there. Of course, you can always check in the replica if there is something more updated.

**Comment by andres-h** [comment]
According the the station operator, DK.COP.10.BH? is just noise at the moment.

Regarding DAG, there were triggered HH channels until 2010-01-17. We started to transfer continuous HH channels on 2019-04-22. I added those channels to the metadata now.

**Comment by javiquinte** [comment]
Thanks @andres-h !
@flixha Can you confirm that this issue can be closed?

**Comment by flixha** [comment]
Thanks a lot for adding the responses for GE.DAG.00.HH?, and for the information regarding DK.COP.10.BH?. I tested the response from GE.DAG for the HH-channels and they work.
Cheers!
