### ISSUE TITLE
routing: NOA problems with localconfig

### ISSUE THREAD

**Issue by petrrr** [EIDA/userfeedback#71]
**Describe the problem**
During work on the routing service we observe an issue with the routing service of NOA.
Ti regards **only** the `localconfig` 

**To Reproduce**
http://eida.gein.noa.gr/eidaws/routing/1/localconfig

It fails with the following message:
```
XML Parsing Error: syntax error
Location: http://eida.gein.noa.gr/eidaws/routing/1/localconfig
Line Number 1, Column 1:
Trying to connect to eida.gein.noa.gr ...
^
```

**Screenshots**

<img width="824" alt="Screenshot 2020-07-14 at 16 47 20" src="https://user-images.githubusercontent.com/3065632/87440063-ce784480-c5f1-11ea-9bb1-4f5e7cd802dc.png">

**Client**

Occured with routing service routines (UpdateAll), tested with browser.

**Comment by nikosT** [comment]
The issue has been resolved. Thank you for your feedback.

**Comment by petrrr** [comment]
Great!
