### ISSUE TITLE
AlpArray + permanent stations metadata issues - continued

### ISSUE THREAD

**Issue by PetrColinSky** [EIDA/userfeedback#72]
Dear colleagues,
I am following my metadata report of issue #68. That one was based on 3 earthquakes. Now, I have processed 31 EQs from mid 2016 to mid 2019. It confirmed what I was reporting in June and now I am adding more detailed information. Some comments are about the same stations as before, some are new. I see some of the reported issues corrected already in the metadata on EIDA (like the missing “minus” in the A12xA station xmls). It is nice, thanks. Maybe, it should have been communicated as a comment to the issue #68, that the things are solved already and that there are new xmls to download, so that folks can refresh their copies of xml to use to corrected ones. I also see, that some other errors have not been corrected yet.

Stations for which I have identified a possible problem (in addition to those mentioned in issue #68):

Z3.A104C
http://erde.geophysik.uni-muenchen.de/fdsnws/station/1/query/?net=Z3&station=A104C&channel=???&level=response
The header for epoch 2017 – 2018 says: “CMG-3ESP, 120 s, 2000 V/m/s-PR6-24, Very Low gain” meaning Guralp 120s, but the PaZ are given for STS2 - 3. generation. The characteristics are kind of similar, true, but not really the same. I cannot decide, which is correct.

FR.VAL4    4.8920   44.9057  1924.3  1922.8  1921.5  1919.2  1916.2  1912.1
This station is off the phase by around 11 seconds at 100s wave. The label in the xml reads
&lt;Description&gt;GURALP CMG-3T 120S&lt;/Description&gt;
but the PaZ are not giving a response of 120s Guralp. Also, there are two stages with PaZ, and they are different for the horizontals and for the vertical, which is suspicious. There is one additional Pole in stage2 for the vertical, and one Pole and one Zero in the stage2 for the horizontals. When deleting the stage2 and replacing the stage1 with PaZ for Guralp 120s, the data is much closer to what is expected from the surrounding stations, but still several (2 - 3) seconds off the phase of the 100s wave. However, this station was available only for two EQs, so my comment here is not really well-founded.

CZ.KRLC
http://geofon.gfz-potsdam.de/fdsnws/station/1/query/?net=CZ&station=KRLC&channel=???&level=response
PaZ are given for 30s Guralp. The web page of the station operator
https://www.ig.cas.cz/en/observatories/czech-regional-seismic-network/kraliky-krlc/
reads Guralp 120s. That station is giving nice data up to August 2018 and is off later. The xml has only one epoch for the investigated time range, but there is a clear moment from which the station is off the phase.

Z3.A412A
http://geofon.gfz-potsdam.de/fdsnws/station/1/query/?net=Z3&station=A412A&channel=???&level=response
It has wrong coordinates in the xml. It has already been communicated with Anke D. The proper values are:
&lt;Latitude &gt;41.647583&lt;/Latitude&gt;
&lt;Longitude &gt;4.744833&lt;/Longitude&gt;

GU.RORO
http://webservices.ingv.it/fdsnws/station/1/query?net=GU&station=RORO&channel=???&level=response
This station was mentioned in the is #68, it had the HERTZ-RADIANS problem (and it still has). In addition to this, the polarity of the vertical is always flipped.

For the other stations, I am reporting the issues in the form of a table, see the attached pdf. Each row is for an EQ (sorted by time), each column is for a station. Red cell means, the data was off the phase. “OK” means it was alright. “-----” means no data available, so I cannot say anything. “-----X” means, the data was available, but was of such a bad quality, that I could not reliably estimate the phase. “flip” means, I needed to flip the vertical component. I first list the permanent stations, sorted by the number of red cells. Then I list the AlpArray temporary stations sorted by their names. There are three “blocks” of AA stations (A030A – A038A; A100A – A109A and A112A – A116A), where close-by stations (in space), have issues for common EQs (in time). This I also already partly reported in the issue #68, and now I am giving more clear view on the same thing.

I am not listing here the stations, for which I have corrected the xml and which after this correction work fine, see issue #68.

I found many more stations with similar issues, but found only for several EQs randomly (in time), which looks like accidental feature and I am not reporting these here. If somebody is interested in such an overview, let me know.

Note to OBS (1): the French OBS xml files have correctly labeled the channels like Z/1/2 as the data is not oriented, however, the numbers given as the &lt;Azimuth&gt; read “0” and “90” which may look like they are oriented. So, be careful (communication with Anne P.).

Note to OBS (2): the German OBS xml have the orientations to north and east given in the xml properly. I tested the values confirming that the components nicely split into radial and transverse when rotating them to the EQs backazimuth. Just refresh your xml copy so that you get these orientations. Thanks, Anke.

cheers
petr, UniWien
[blacklist.pdf](https://github.com/EIDA/userfeedback/files/4971727/blacklist.pdf)

**Comment by massimo1962** [comment]
I talked to @petrrr . is already aware of this issue and started the interaction with our data provides. Peter takes over this issue. However, it might take a while to have a resolution due to holiday time.

**Comment by petrrr** [comment]
Dear @PetrColinSky I am trying to sort out some of the issues you are reporting here and also #68. For the moment I would like to focus on the GU network. We also informed our colleagues from Uni Genova which provide these stations to get some more insights. 

In any case I would have a questions for you, which might be more relevant here:

Apparently the instrumentation of the station has not changes, so the nominal response *should* be okay. The T40 is very frequently used in our inventory. However, I also note that the problem is not seen consistently for the two GU stations reported in the blacklist. If I understand correctly your analysis is based on 100s  period  Rayleigh, while the sensors cut-off is 40 s. So could this observation not be explained by limitations of the sensor vs. method used, SN ratio, signal strength, etc. I know the T40 can often be uses well below its corner, but of cause this also has some limits. 

Would it be possible to shift the your analysis some what up the spectrum towards the sensors flat response to understand this better?

**Comment by PetrColinSky** [comment]
@petrrr Yes, good idea, I will look at shorter-periods at GU.BURY and GU.CANO (in the blacklist). Btw, also GU.GRAM, GU.RNCA, GU.MAIM and GU.POPM have randomly showed some issues. I did not include those in the blacklist, as they are good most of the time. I will look at all of them and will be back to you next week. It is true that it could be simply data issue. There are, however, many other stations (in the AlpArray region) with T40, where the records are really nice at 100s. I am looking at the big earthquakes only, where the SNR at 100s is still very good. But yes, I will do it as you suggest.
cheers
petr

**Comment by PetrColinSky** [comment]
I have found the problem with stations
A030A
A032A
A033A
A036A
A037A
A100A
A101B
A102A
A104A
A108A
A109A
reported above. It is a weird combination of something in the MSeed file (data file) and the particular ObsPy version (1.2.1), which does not allow to deconvolve. On the output, one gets exactly the same signal as on the input, but no error is rised. I noticed it when upgrading to ObsPy 1.2.2 and deconvolving again. Then everything is fine. It is not only the ObsPy problem, because hundreds of stations were deconvolved properly with 1.2.1, and it is also not the data problem only, as with the new ObsPy, these are also deconvolved alright. The metadata are correct.

This DOES NOT apply for A038A, which is still off the phase as reported above, and as well it DOES NOT apply for A112A, A113A and A116A, which are also still off. In addition, A032A is in general better, but for several EQs, it is still of, but just few seconds of in phase at 100s wave.

Those reported above are four sets of stations deployed by four Universities (A030A - A037A = LMU; A038A = Kiel; A100A - A109A = Bochum; A112A - A116A = Frankfurt). So, two sets are solved, two are still a mystery.

I tested this "new ObSpy deconvolution" process to all the affected stations mentioned above, and it did not help for the others.

@petrrr Sorry, GU.* investigation still pending ...

ciao
petr

**Comment by megies** [comment]
@PetrColinSky you have some minimal reproducible example code what exactly seems to be the problem?

**Comment by PetrColinSky** [comment]
@megies Yes, it looks odd, I agree. I can only say, what I did. First, I run the deconvolution for all 31 earthquakes and all stations (around 600 for each EQ), I plotted the wavefronts, which resulted in the "blacklist" presented above. There were these striking portions of bad records grouped in space and time for AxxxA stations, see above. Recently, I started to dig again into these, as I knew, these are good stations, because with my own "stone-age" deconvolution method, these were working fine and I have used them in my papers already. After checking again the metadata, the raw data and everthing, I noticed, that on the output of the deconvolution, I had the same records as on the input. I have no idea how this happened, but it was not random, see the red cells in the blacklist. So I started the deconvolution again, and it got deconvolved properly. The only change I am aware of, was the upgrade of ObsPy. But again, I can be completely wrong. It clearly has something to do with the data files themselves (as I mentioned 5 day ago), because most of the other records even from the same stations were deconvolved properly. I also checked the headers of the MiniSeed files of the "good" and "wrong" days, and I did not find any difference.
I use classical:
inv = read_inventory(path+stream[indexiZ[k]].stats.station+'.xml')
pre_filt = [frmin*0.8, frmin, frmax, frmax*1.4]
stream[indexiZ[k]].remove_response(inventory=inv, pre_filt=pre_filt)
But this is certainly not an issue, as for thousands of records it worked well. I already do not have the previous ObsPy version.
Thanks for taking care of ObsPy, btw, the downloading now works really good and I appreciate it much as I am downloading tons of data (see issue #56).
best
petr

**Comment by megies** [comment]
@PetrColinSky At this point I have to assume that something else was going wrong and there was no obspy problem. Like I said 1.2.1 and 1.2.2 only differ by a handful of minor bugfixes ([changelog](https://github.com/obspy/obspy/blob/6d321f491a63925365b9686e6d034dbab2a2f9fa/CHANGELOG.txt#L34-L61)). We'd need to have a reproducible mini example to prove there is an issue.

**Comment by PetrColinSky** [comment]
@petrrr I have ploted the wavefronts from 36s to 102s for a big earthquake in Greece, 2018-10-25, Mouzaki, M=6.8, nice signal-to-noise over the whole AlpArray. I focused on station GU.BURY. The figures are here:
https://www.dropbox.com/s/npyq42t5btoyt2u/contoursBURY.zip?dl=0
I plotted always one map including GU.BURY and the same map without it. When you compare these pairs, it is clear, that GU.BURY makes some distortion. If you go over the period range, the distortion is the bigger, the longer the period is. So it is probably NOT a timing issue, because it would create the same shift for all periods. The distortion is dispersive, meaning, there is probably something wrong with the deconvolution. I deconvolved it freshly today to make sure that it is not the issue discussed with @megies above, whatever the issue was. For GU.BURY, I always (older and newer ObsPy) got the same result of deconvolution. I also made sure that when deconvolving the data with my stone-age method (using my own nominal databse of Poles and Zeros), and deconvolving the data with ObsPy and station xml, I got more-or-less the same results (it differs in time by less than 1 second at the period of 100s, which is below the resolution of the wavefront maps). Meaning, the stations xml looks allright in the sense that nominally it corresponds to T40 sensor. The question is, if it is a proper characteristics of the sensor, which is in place at GU.Bury. Theoretically, it still can be a timing issue, which is smeared in time by the filtering. I use zero-phase filters, which should keep the phase in the right time, but they are non-causal, meaning, they create some artifacts in front of the signal. According to my knowledge, that should not matter in case of surface waves, where the signal is not abrupt. And again, I am anyway picking the phase, which should be alright.

The wavefronts are always plotted by 5s of propagation for all periods. At the shortest and at the longest periods, the picking did not go well for some other AlpArray regions (I would need to tune the setting for each period differently, which I was lazy to do), which luckily do not disturb the region around GU.BURY. SNR at BURY is nice over the whole period range, it has very clear fundamental mode. It is all Z component. For this EQ, GU.RORO has flipped Z polarity (as always). I do not have nice records of GU.CANO for this EQ, there is some long-period noise there. I can do the same exercise with GU.RNCA, which is also off for this EQ. The other GU.* stations are alright for this EQ.
If there is something more I can help you with concerning the investigation, let me know.
ciao
petr

**Comment by petrrr** [comment]
@PetrColinSky: For GU stations there should have been some progress. A colleague and the GU network colleagues have work on a new set of metadata for the problematic stations. Hopefully this solves the issues with these stations.

**Comment by petrrr** [comment]
I also would like to comment on the observations regarding the two blacklisted OX stations, which I have not done yet. There might to be a mismatch regarding the sensors model wrt. to our inventory. We are trying to clarify this with the network manager.

**Comment by PetrColinSky** [comment]
@petrrr Thanks again for all your effort. I will also look at the GU stations and maybe add them to my analysis. If you discover something about the OX stations, please, let me know.
cheers
p
