### ISSUE TITLE
[Metadata] IB network - Problem with response information in some stations

### ISSUE THREAD

**Issue by miguelj-neves** [EIDA/userfeedback#73]
When attempting to use remove_response on obspy for some stations of the IberArray IB network I get an error message saying no response information is available.

**Stations:** E032, E033, E034, E035, E062, E072, E073, E081, E083, E091, E103, E117, E115, E932
**Type of client used:** I tried both Obspy and the WebDC3 Web Interface. Both give the same result.

I think the problem is related to the lack of gain information, although poles and zeros are in the stationxml file:
<img width="509" alt="E033_resp_info" src="https://user-images.githubusercontent.com/36202483/89240479-2d662380-d5ca-11ea-9b4d-4062f9782f75.png">

Error message:
<img width="890" alt="error_message" src="https://user-images.githubusercontent.com/36202483/89240496-38b94f00-d5ca-11ea-9598-840d29aa1612.png">

Thank you

**Comment by javiquinte** [comment]
Hi @miguelj-neves 
We are contacting people in charge of this and will come back to you as soon as we have more information.
Thanks for the feedback!

**Comment by jbienkowski** [comment]
Dear @miguelj-neves,
We have received updated metadata from the network operator, it will be soon available online.
Cheers,
Jarek
