### ISSUE TITLE
[Metadata] Station start/end time conflicts

### ISSUE THREAD

**Issue by rizac** [EIDA/userfeedback#75]
We found metadata problem: the same station was returned with conflicting start times (no need to use a specific client, wget or the browsers are sufficient). Example:

http://webservices.ingv.it/fdsnws/station/1/query?starttime=1990-01-01T00:00:00&endtime=2020-12-31T00:00:00&format=text&level=channel&channel=EHZ,HGZ,HHZ,HLZ,HNZ&station=BOTM

Output problems (see below):

1 both rows have the same (network, station, same start time)
2 in second tow's start time == end time

```
IV|BOTM||HNZ|45.5416|10.3213|157|0|0|-90|KINEMETRICS EPISENSOR-FBA-ES-T-CL-2G-FS-40-VPP|320770|0.2|M/S**2|100|2014-11-14T14:00:00|2014-11-14T14:00:00
IV|BOTM||HNZ|45.5416|10.3213|157|0|0|-90|KINEMETRICS EPISENSOR-FBA-ES-T-CL-2G-FS-40-VPP|320770|0.2|M/S**2|100|2014-11-14T14:00:00|2019-08-30T15:01:00
```

**Comment by javiquinte** [comment]
Thanks @rizac for the feedback!
@massimo1962 will for sure take a look at this and post here the an answer.

**Comment by petrrr** [comment]
Solved!

* http://webservices.ingv.it/fdsnws/station/1/query?starttime=1990-01-01T00:00:00&endtime=2020-12-31T00:00:00&format=text&level=channel&channel=EHZ,HGZ,HHZ,HLZ,HNZ&station=BOTM

```
#Network | Station | location | Channel | Latitude | Longitude | Elevation | Depth | Azimuth | Dip | SensorDescription | Scale | ScaleFreq | ScaleUnits | SampleRate | StartTime | EndTime
IV|BOTM||HNZ|45.5416|10.3213|157|0|0|-90|KINEMETRICS EPISENSOR-FBA-ES-T-CL-2G-FS-40-VPP|320770|0.2|M/S**2|100|2014-11-14T14:00:00|2019-08-30T15:01:00
```

**Comment by petrrr** [comment]
@javiquinte: I think this can be closed, but I leave it to you to do so.
