### ISSUE TITLE
[No Data] Data cannot be downloaded for PL.SUW and PL.KWP

### ISSUE THREAD

**Issue by jbienkowski** [EIDA/userfeedback#79]
Issue created on user's behalf:

It concerns two Polish stations (PL.SUW and PL.KWP) hosted at GFZ. According to WFCatalog, data availability for PL.SUW in 2020 is close to 99.6%, but FDSNWS-Dataselect requests end up with 204 No Content.

> Until 2010 these stations belonged to the GE network and since 2010 they belong to the PL network. Old data with the GE network name can be downloaded but the new one with the PL network cannot.

![Screenshot from 2021-01-13 08-14-57](https://user-images.githubusercontent.com/8037752/104418703-a0ab9280-5577-11eb-8f55-5dc4e021e194.png)
FDSNWS-Dataselect: http://geofon.gfz-potsdam.de/fdsnws/dataselect/1/query?network=PL&station=SUW&start=2020-03-18&end=2020-03-19
FDSNWS-Station: http://geofon.gfz-potsdam.de/fdsnws/station/1/query?network=PL&station=SUW

**Comment by javiquinte** [comment]
Thanks for letting us know, @jbienkowski !
@andres-h is working on that

**Comment by andres-h** [comment]
There was a mistake in metadata (wrong archiveNetworkCode), which is now fixed.
