### ISSUE TITLE
FAIRsharing query - EIDA in FAIRsharing

### ISSUE THREAD

**Issue by allysonlister** [EIDA/userfeedback#81]
Dear EIDA Team,

I’m contacting you on behalf of FAIRsharing, the online registry of scientific data standards, databases and policies[1]. Our aim is to make your resource as visible as possible to as large an audience as possible.

Recently, our curation team has been creating and updating records within our Earth Science theme. As part of this work, we would like to let you know about the FAIRsharing record we have for your resource[2].

To ensure our information is as correct and up to date as possible, would you or someone from your team claim[3] the record and make any necessary updates? There are a number of benefits to claiming ownership of your FAIRsharing record.

1. Metadata editing and notifications. Claiming a record (as an individual or with an institutional account) allows you to edit the record, giving you control over how your resource is described in FAIRsharing. Maintainers are also notified if our curation team edits the record, if users ask questions, or if the record is linked to another record, such as from a journal publisher data policy.  
2. Resource FAIRness and discoverability. FAIRsharing is about making your resource more FAIR, making it discoverable to a variety of users, so it can be used by more researchers, adopted by more communities, endorsed in journal and funder data policies and placed into context in a wider infrastructure ecosystem.  

Once you have claimed your record, you can begin to edit its metadata on FAIRsharing. To do this, click on the “Edit” option available within the "Actions" menu found to the top right of your record. This will present you with an editable form. Please look over the existing data and make any necessary modifications. All changes to records are reviewed by our experienced curators. In addition, you can link your resource to any standards you may use or data policies that endorse your resource.

Please don’t hesitate to contact us if you are unsure as to where a piece of information should go, we are happy to help you curate and maintain your record.

Thank you and best wishes,
Allyson and The FAIRsharing team

[1] https://fairsharing.org, https://doi.org/10.1038/s41587-019-0080-8
[2] https://fairsharing.org/biodbcore-000918/
[3] https://fairsharing.org/own/biodbcore/claim/biodbcore-000918
[4] https://fairsharing.org/communities

**Comment by jbienkowski** [comment]
Reference: https://fairsharing.org/FAIRsharing.vmq5yj
