### ISSUE TITLE
[EIDA token]

### ISSUE THREAD

**Issue by aubercor** [EIDA/userfeedback#86]
Hello,

I am working with a program already written that downloads massive data using 
`client.get_waveforms_bulk(bulk,attach_response = True) `

I need to modify this program to add the possibility to download data from opened networks but also data from Z3 network using eida token as follow:
```
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': str(token)})
st=rsClient.get_waveforms_bulk(bulk) 
```
However, I would like to attach the response to the waveforms as the program remove the response from the data after downloading them.

It did work with the usual fdsn Client as follow: `st = client.get_waveforms_bulk(bulk_rq,attach_response = True)`

But it does not work when the Client is opened with eida token.

As the  constructed bulk will contain both data from opened permanent network and data from Z3 network (eida token), do you have any suggestions to help me to modify the program to be able to download data from both ways and attach the response as well?

I do not have any idea.

Regards,
Coralie

**Comment by javiquinte** [comment]
Hi Coralie @aubercor !
After checking the documentation I realised that probably you could use the following:

* Call `get_stations_bulk` after `get_waveforms_bulk`. That will give you the needed inventory. Probably just add the parameter `level="response"`. That should give you an `Inventory` object [1].
* Then you could call the method `attach_response` for the Stream with the `Inventory` object as parameter [2].

Please, let me know if this helps.

Cheers,

Javier

[1] https://docs.obspy.org/packages/autogen/obspy.clients.fdsn.routing.eidaws_routing_client.EIDAWSRoutingClient.get_stations_bulk.html#obspy.clients.fdsn.routing.eidaws_routing_client.EIDAWSRoutingClient.get_stations_bulk

[2] https://docs.obspy.org/packages/autogen/obspy.core.stream.Stream.attach_response.html

**Comment by aubercor** [comment]
Hi Javier,

It helped me a lot.

Here is the code I tested which worked for me:
```
rsClient = RoutingClient("eida-routing", credentials={'EIDA_TOKEN': './eidatoken'})
starttime=UTCDateTime(2018, 3, 1)
endtime=UTCDateTime(2018, 3, 1, 2, 0, 0)
bulk = [("Z3", "A183A", "00", "HHZ", starttime, endtime),("Z3", "A181A", "00", "HHZ", starttime, endtime),
("FR", "OGAG", "00", "HHZ", starttime, endtime)]
st = rsClient.get_waveforms_bulk(bulk)
inv = rsClient.get_stations_bulk(bulk, level="response")
st.attach_response(inv)
st.remove_response(output="VEL")
```
Regards,
Coralie

**Comment by aubercor** [comment]
Javier,

I benefit from this issue to ask you one more thing related to Eida token.

Is it possible to access data from restricted network that required login and password when opening fdsn client?
For example:
`client = obspy.clients.fdsn.Client("RESIF", user=username, password=pwd)`

I would like to download data from mixed networks: 
- Z3 accessible with EIDA token
- open networks
- restricted networks 

I would like to open a single client which would be client from eida-routing with token as it allows to download Z3 data and data from opened networks.

Would it be possible to access data from such restricted networks?

Regards,
Coralie
