### ISSUE TITLE
Certificate problem with domain ph5ws.resif.fr

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#88]
Many thanks for the fix, now the URL is at:

```
http://ph5ws.resif.fr/fdsnws/dataselect/1/query
```

which is standard FDSN.

However, with our client software, when downloading with token, we get now a SSL certificate error:

```
ssl.CertificateError: hostname 'ph5ws.resif.fr' doesn't match either of 'ws.resif.fr', 'www.ws.resif.fr'
```

If the fix is not easy, then *better restore the previous non standard FDSN URL*, because this can be handled by client software quite easily (e.g.: check and exclude non standard URLs), whereas the error above is out of control

_Originally posted by @rizac in https://github.com/EIDA/userfeedback/issues/80#issuecomment-822256104_

**Comment by javiquinte** [comment]
Hi. I'm bringing a new comment we received a couple of days ago as a new issue.
@jschaeff : If you estimate that this could take more than 24 hours to solve, the best thing to do is to remove these URLs from your Routing Service routes. You can always add them later when everything works again.

Another quick question regarding this. It is clear that the URL is FDSN compliant and that the API follows the dataselect specification, but does it return miniSEED, doesn't it? Just to be sure.

**Comment by jschaeff** [comment]
Hi @javiquinte , I'm going to remove it from the routing service. I don't know why it takes so long for the university to deliver the certificate (it has been 3 weeks now). Sorry about the inconvenience.

http://ph5ws.resif.fr/fdsnws/dataselect/1/query returns pure miniseed data.

**Comment by javiquinte** [comment]
Thanks @jschaeff !
Please, let us know when your routes are updated to check the output of the Routing Server.

**Comment by jschaeff** [comment]
Routes are updated

**Comment by javiquinte** [comment]
Thanks! I've checked the published routes and they look OK. So, we should see the problem solved in the update tonight.

Thanks!
