### ISSUE TITLE
Invalid `fdsnws-station` response

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#89]
Hi,

there seems to be an issue with the `fdsnws-station` service implementation at RESIF, e.g.:

```
$ curl -s -o - "http://ws.resif.fr/fdsnws/station/1/query?net=FR&level=network&format=xml"
<?xml version="1.0" encoding="UTF-8"?>
<FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1" schemaVersion="1.1" xsi:schemaLocation="http://www.fdsn.org/xml/station/1 http://www.fdsn.org/xml/station/fdsn-station-1.1.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:resif="http://www.fdsn.org/xml/station/1/resif">
<Source>RESIF-SI</Source><Sender>RESIF-DC</Sender>
<Module>RESIF WEB SERVICE: fdsnws-station | version: 1.1.1 </Module>
<ModuleURI>http://k8s-worker.resif.fr/fdsnws/station/1/query?net=FR&amp;level=network&amp;format=xml</ModuleURI> 
<Created>2021-04-29T15:27:29Z</Created>
<Network code="FR" alternateCode="RLBP" startDate="1962-01-01T00:00:00" endDate="2500-12-31T23:59:59" restrictedStatus="open"><Description>RESIF and other Broad-band and accelerometric permanent networks in metropolitan France</Description><Identifier type="DOI">10.15778/RESIF.FR</Identifier><Comment><Value>DOI:http://dx.doi.org/10.15778/RESIF.FR</Value></Comment><Comment><Value>DOI : https://doi.org/10.15778/RESIF.FR</Value><BeginEffectiveTime>1962-01-01T00:00:00</BeginEffectiveTime><Author><Name>Observatoire de la Côte d'Azur</Name><Email>network.oca@resif.fr</Email></Author></Comment><TotalNumberStations>170</TotalNumberStations><SelectedNumberStations>170</SelectedNumberStations></Network>
</FDSNStationXML>
1
```

and

```
$ curl -s -o - "http://ws.resif.fr/fdsnws/station/1/query?net=FR&level=network&format=text"
#Network|Description|StartTime|EndTime|TotalStations
FR|RESIF and other Broad-band and accelerometric permanent networks in metropolitan France|1962-01-01T00:00:00|2500-12-31T23:59:59|170
1
```

All queries, I've tested so far return a response including a trailing `1`.

**Comment by jschaeff** [comment]
Thank you for reporting this. I'll fix it tonight 

Le 29 avril 2021 17:33:59 GMT+02:00, Daniel Armbruster ***@***.***> a écrit :
>Hi,>
>>
>there seems to be an issue with the `fdsnws-station` service
>implementation at RESIF, e.g.:>
>>
>```>
>$ curl -s -o -
>"http://ws.resif.fr/fdsnws/station/1/query?net=FR&level=network&format=xml">
><?xml version="1.0" encoding="UTF-8"?>>
><FDSNStationXML xmlns="http://www.fdsn.org/xml/station/1"
>schemaVersion="1.1"
>xsi:schemaLocation="http://www.fdsn.org/xml/station/1
>http://www.fdsn.org/xml/station/fdsn-station-1.1.xsd"
>xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
>xmlns:resif="http://www.fdsn.org/xml/station/1/resif">>
><Source>RESIF-SI</Source><Sender>RESIF-DC</Sender>>
><Module>RESIF WEB SERVICE: fdsnws-station | version: 1.1.1 </Module>>
><ModuleURI>http://k8s-worker.resif.fr/fdsnws/station/1/query?net=FR&amp;level=network&amp;format=xml</ModuleURI>
>>
><Created>2021-04-29T15:27:29Z</Created>>
><Network code="FR" alternateCode="RLBP" startDate="1962-01-01T00:00:00"
>endDate="2500-12-31T23:59:59"
>restrictedStatus="open"><Description>RESIF and other Broad-band and
>accelerometric permanent networks in metropolitan
>France</Description><Identifier
>type="DOI">10.15778/RESIF.FR</Identifier><Comment><Value>DOI:http://dx.doi.org/10.15778/RESIF.FR</Value></Comment><Comment><Value>DOI
>:
>https://doi.org/10.15778/RESIF.FR</Value><BeginEffectiveTime>1962-01-01T00:00:00</BeginEffectiveTime><Author><Name>Observatoire
>de la Côte
***@***.***</Email></Author></Comment><TotalNumberStations>170</TotalNumberStations><SelectedNumberStations>170</SelectedNumberStations></Network>>
></FDSNStationXML>>
>1>
>```>
>>
>and>
>>
>```>
>$ curl -s -o -
>"http://ws.resif.fr/fdsnws/station/1/query?net=FR&level=network&format=text">
>#Network|Description|StartTime|EndTime|TotalStations>
>FR|RESIF and other Broad-band and accelerometric permanent networks in
>metropolitan France|1962-01-01T00:00:00|2500-12-31T23:59:59|170>
>1>
>```>
>>
>All queries, I've tested so far return a response including a trailing
>`1`.>
>>
>>
>-- >
>You are receiving this because you are subscribed to this thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/EIDA/userfeedback/issues/89

-- 
Envoyé de mon appareil Android avec Courriel K-9 Mail. Veuillez excuser ma brièveté.

**Comment by damb** [comment]
Thanks for fixing, @jschaeff.
