### ISSUE TITLE
No RESIF stations in Alparray

### ISSUE THREAD

**Issue by javiquinte** [EIDA/userfeedback#92]
RESIF does not seem to work with "fdsnws_fetch" even though the RESIF ObsPy FDSN Client works for the exact same station and time.

```
python fdsnws_fetch.py -N 'Z3' -S 'A156A' -L '*' -C '*' -s "2017-01-01T07:00:00Z" -e "2017-01-01T07:05:00Z" -a 'eidatoken' -v -o data.mseed
using token in eidatoken:
{"valid_until": "2021-06-03T09:15:01.979991Z", "cn": "Benedikt Braszus", "memberof": "/epos;/epos/alparray;/", "sn": "Braszus", "issued": "2021-05-04T09:15:01.979996Z", "mail": "benedikt.braszus@kit.edu", "givenName": "Benedikt", "expiration": "1m"}

getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?network=Z3&station=A156A&location=%2A&channel=%2A&starttime=2017-01-01T07%3A00%3A00Z&endtime=2017-01-01T07%3A05%3A00Z&format=post
received no routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query?network=Z3&station=A156A&location=%2A&channel=%2A&starttime=2017-01-01T07%3A00%3A00Z&endtime=2017-01-01T07%3A05%3A00Z&format=post
did not receive routes to Z3.A156A.*.*

In case of problems with your request, please use the contact form at

    http://www.orfeus-eu.org/organization/contact/form/?recipient=EIDA
```

Are these problems reproducible for you or is there an error somewhere on my side ? 

Cheers,
Benedikt

_Originally posted by @BeneBraszus in https://github.com/EIDA/userfeedback/issues/91#issuecomment-836360264_

**Comment by javiquinte** [comment]
Probably the error is that the route to Z3 in the RESIF Routing Service is wrongly declared
```
<ns0:route networkCode="Z3" stationCode="" locationCode="*" streamCode="*">
<ns0:station address="http://ws.resif.fr/fdsnws/station/1/query" priority="1" start="2015-01-01T00:00:00" end="2022-12-31T23:59:59"/>
<ns0:dataselect address="http://ws.resif.fr/fdsnws/dataselect/1/query" priority="1" start="2015-01-01T00:00:00" end="2022-12-31T23:59:59"/>
<ns0:availability address="http://ws.resif.fr/fdsnws/availability/1/query" priority="1" start="2015-01-01T00:00:00" end="2022-12-31T23:59:59"/>
<ns0:timeseries address="http://ws.resif.fr/resifws/timeseries/1/query" priority="1" start="2015-01-01T00:00:00" end="2022-12-31T23:59:59"/>
<ns0:timeseriesplot address="http://ws.resif.fr/resifws/timeseriesplot/1/query" priority="1" start="2015-01-01T00:00:00" end="2022-12-31T23:59:59"/>
<ns0:wfcatalog address="http://ws.resif.fr/eidaws/wfcatalog/1/query" priority="1" start="2015-01-01T00:00:00" end="2022-12-31T23:59:59"/>
</ns0:route>
```

**Comment by jschaeff** [comment]
Hi @javiquinte 
The routes for Z3 where not advertised at station level, as before.
I corrected this. My bad, an environment variable was not correctly setup.
Our route xml file is fixed now.

**Comment by damb** [comment]
@javiquinte, @jschaeff, is there a reason why routes of distributed physical networks (e.g. `Z3`) need to be declared at *station level*? Is this a requirement/limitation for `eidaws-routing`? I mean, the `eidaws-routing` harvesting facilities resolve the routing definition with `fdsnws-station`, anyway.

**Comment by javiquinte** [comment]
Hi @damb
The main reason is that stations could be duplicated, or hosted in a node but not ready to be shared, or actually not meant to be shared at all, there could also be secondary routes, etc. On addition to that, the sharing status with EIDA is sometimes supported by an MoU.
