### ISSUE TITLE
Network `CA` description

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#95]
This is a minor issue. However, we should fix this, anyway.

http://ws.icgc.cat/fdsnws/station/1/query?net=CA&format=text&level=network returns

```
#Network|Description|StartTime|EndTime|TotalStations
CA|x|1980-01-01T00:00:00||42
```

where the `Description` is set to `x`. Please, provide a more meaningful network description, instead. Thanks.

**Comment by JoseAntonioJara** [comment]
Hi all, thanks damb for reporting this issue.
It is now fixed.

Cheers.
