### ISSUE TITLE
Cannot download AlpArray data from France

### ISSUE THREAD

**Issue by stephenmonna** [EIDA/userfeedback#96]
Hi, I haven't been able to download data from the French AA side, both temporary and permanent.
I have the access token and am able to download other data.
I receive messages from fdsnws_fetch such as the one you can find below

2000-11-29T10.25.13
origin time=2000-11-29 10:25:13.26
end time=2000,11,29,10,55,13
start time=2000,11,29,10,25,13
10.25.13
2000-11-29T10.25.13.txt
requesting AA stations for 2000-11-29T10.25.13.txt - event 52 out of 3197
Mon May 17 18:18:55 CEST 2021
using token in /home/stephen/eidatoken:
{"valid_until": "2021-06-13T10:15:35.113207Z", "cn": "Stephen Monna", "memberof": "/epos;/epos/alparray;/", "sn": "Monna", "issued": "2021-05-14T10:15:35.113213Z", "mail": "stephen.monna@ingv.it", "expiration": "1m"}

getting routes from http://geofon.gfz-potsdam.de/eidaws/routing/1/query
authenticating at https://ws.resif.fr/fdsnws/dataselect/1/auth
authentication at https://ws.resif.fr/fdsnws/dataselect/1/auth successful
getting data from http://ws.resif.fr/fdsnws/dataselect/1/queryauth
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/fdsnwsscripts/fdsnws_fetch.py", line 883, in fetch
    resp = e.read()
AttributeError: 'HTTPError' object has no attribute 'read'

did not receive data from FR.SAOF.*.BH?, FR.SAOF.*.HH?

In case of problems with your request, plese use the contact form at

    http://www.orfeus-eu.org/organization/contact/form/?recipient=EIDA

I hope this is enough information, thanks for any help,
Stephen

**Comment by jschaeff** [comment]
Hi, thank you for reporting this issue.
There were a mixup in my dataselect webservice configuration. 
It's fixed.
Sorry for the inconvenience.
