### ISSUE TITLE
Station `JAVC`

### ISSUE THREAD

**Issue by damb** [EIDA/userfeedback#97]
Hi,

interestingly station `JAVC` is both part of the network `OE` (http://orfeus-eu.org/fdsnws/station/1/query?net=OE&sta=JAVC&level=channel) and the network `CZ` (http://geofon.gfz-potsdam.de/fdsnws/station/1/query?sta=CZ&sta=JAVC&level=channel).

From the metadata it is not 100% clear if it refers to the same instrument. Thus, my question: Is it the same instrument, or not? If yes, we should align the metadata (if possible).

Daniel

**Comment by javiquinte** [comment]
There are many stations that appear in two networks at the same time. There are institutional reasons for that and usually it should remain like this. However, you are totally right that the metadata should be exactly the same (if they have the same channels, of course).

**Comment by javiquinte** [comment]
I'll check on our side if this looks reasonable

**Comment by andres-h** [comment]
Trying to get metadata from authoritative source.

**Comment by jbienkowski** [comment]
Parallel investigation ongoing at ODC.
