### ISSUE TITLE
2015/Z3 (AlpArray): review high level metadata & routing 

### ISSUE THREAD

**Issue by petrrr** [EIDA/userfeedback#99]
* Type of client used (Obspy, fdsnws_fetch, arclink_fetch)

  * No client; 
  * reviewing FDSN (IRIS) MetaData Aggregator results for some networks related to the Italian node; 
  * for see [2015/Z3](http://ds.iris.edu/mda/Z3/?starttime=2015-01-01T00:00:00&endtime=2022-12-31T23:59:59)

* Stations involved

  * network level: divergent description field for network
  * stations `A260A` .. `A267A` -> LMU vs. ODC;
  * stations `A271A` .. `A273A` -> LMU vs. SED; 

* What is exactly wrong with the metadata?

1. network level
The network metadata are diverging across nodes, at least the description of the network. These metadata should be unified;

  *  `AlpArray Seismic Network (AASN) temporary component`
vs.
  * `Alpine area 2015,ALPARRAY Seismic Network (AASN) temporary component`

2. multiple station entries
Several station (see above) are offered by multiple nodes and the metadata seem not to be in sync.   I would assume this is easiest fixed by removing the non authoritative entry.

**Comment by kaestli** [comment]
There is no overlap between SED and LMU  on stations A271..3A
- SED route refer to 2015-17, LMU to 2019-22

**Comment by jbienkowski** [comment]
Hi Peter,

Stations mentioned by you indeed exist at LMU and ODC, but with different epochs. End date at ODC is just before start date at LMU. The network description might indeed be slightly different. We follow the [citation](https://data.crosscite.org/application/vnd.datacite.datacite+json/10.12686/alparray/z3_2015) description ("AlpArray Seismic Network (AASN) temporary component").

Cheers,
Jarek

**Comment by jschaeff** [comment]
I was not involved in the issue but I see that RESIF advertises: 

```xml
    <Description>Alpine area 2015,ALPARRAY Seismic Network (AASN) temporary component</Description>
```
I will validate with PI before making the adjustment to follow the DOI title and be consistent with ODC and LMU.

**Comment by jschaeff** [comment]
Fixed on RESIF side.

I guess it's consistent now. I close the issue.
